#configinfo Standard-Erweiterung der Compose-Definitionen
# standard Definitions by Neo keyboard layout

# diacritical marks
<dead_circumflex> <nobreakspace>           : "ˆ"   U02C6 # MODIFIER LETTER CIRCUMFLEX ACCENT 227
<dead_caron> <nobreakspace>                : "ˇ"   U02C7 # CARON 110
<dead_breve> <nobreakspace>                : "˘"   U02D8 # BREVE 105
<dead_acute> <nobreakspace>                : "´"   U00B4 # ACUTE  229
<dead_grave> <nobreakspace>                : "`"   U0060 # GRAVE ACCENT 231
<dead_cedilla> <nobreakspace>              : "¸"   U00B8 # CEDILLA 125
<U21BB> <dead_cedilla> <nobreakspace>      : "˛"   U02DB # OGONEK 140 deadCedilaa = l2Equal
<dead_abovedot> <nobreakspace>             : "˙"   U02D9 # DOT ABOVE 175
<dead_abovering> <nobreakspace>            : "˚"   U02DA # RING ABOVE 178
<dead_tilde> <nobreakspace>                : "˜"   U02DC # SMALL TILDE 180
<dead_macron> <nobreakspace>               : "¯"   U00AF # MACRON 184
<dead_diaeresis> <nobreakspace>            : "¨"   U00A8 # DIAERESIS 207
<dead_stroke> <nobreakspace>               : "/"   U002F # SOLIDUS 209
<dead_doubleacute> <nobreakspace>          : "˝"   U02DD # DOUBLE ACUTE ACCENT
<dead_psili> <nobreakspace>                : "᾿"   U1FBF # GREEK PSILI
<dead_dasia> <nobreakspace>                : "῾"   U1FFE # GREEK DASIA
<U02F5> <nobreakspace>                     : "˵"   U02F5 # MODIFIER LETTER MIDDLE DOUBLE GRAVE ACCENT 
<U21BB> <dead_doubleacute> <nobreakspace>  : "˵"   U02F5 # MODIFIER LETTER MIDDLE DOUBLE GRAVE ACCENT 141
<U21BB> <nobreakspace>                     : "↻"   U21BB # CLOCKWISE OPEN CIRCLE ARROW 139
<U02DE> <nobreakspace>                     : "˞"   U02DE # MODIFIER LETTER RHOTIC HOOK 226
<dead_belowdot> <nobreakspace>             : "."   U002E # FULL STOP
˜˜˜˜
# combining characters
<Multi_key> <o> <space>                    : "◌"   U25CC # DOTTED CIRCLE
<Multi_key> <ellipsis> <o>                 : "◌"   U25CC # DOTTED CIRCLE
<dead_circumflex> <dead_circumflex>        : "̂"   U0302 # COMBINING CIRCUMFLEX ACCENT 228
<dead_caron> <dead_caron>                  : "̌"   U030c # COMBINING CARON 111
<dead_breve> <dead_breve>                  : "̆"   U0306 # COMBINING BREVE 106
<U21BB> <dead_breve> <dead_breve>          : "̑"   U0311 # COMBINING INVERTED BREVE 142 deadbreve = L6RBr
<dead_acute> <dead_acute>                  : "́"   U0301 # COMBINING ACUTE ACCENT 230
<dead_grave> <dead_grave>                  : "̀"   U0300 # COMBINING GRAVE ACCENT 232
<dead_cedilla> <dead_cedilla>              : "̧"   U0327 # COMBINING CEDILLA 126
<U21BB> <dead_cedilla> <dead_cedilla>      : "̨"   U0328 # COMBINING OGONEK    143
<dead_abovedot> <dead_abovedot>            : "̇"   U0307 # COMBINING DOT ABOVE 176
<dead_abovering> <dead_abovering>          : "̊"   U030A # COMBINING RING ABOVE 179
<dead_tilde> <dead_tilde>                  : "̃"   U0303 # COMBINING TILDE 181
<dead_macron> <dead_macron>                : "̄"   U0304 # COMBINING MACRON 185
<dead_diaeresis> <dead_diaeresis>          : "̈"   U0308 # COMBINING DIAERESIS 208
<dead_stroke> <dead_stroke>                : "̷"   U0338 # COMBINING SHORT SOLIDUS OVERLAY 210
<dead_doubleacute> <dead_doubleacute>      : "̋"   U030B # COMBINING DOUBLE ACUTE ACCENT 129
<dead_psili> <dead_psili>                  : "̓"   U0313 # COMBINING COMMA ABOVE 220
<dead_dasia> <dead_dasia>                  : "̔"   U0314 # COMBINING REVERSED COMMA ABOVE 222
<U02F5> <U02F5>                            : "̏"   U030F # COMBINING DOUBLE GRAVE ACCENT
<U21BB> <dead_doubleacute> <dead_doubleacute>  : "̏"   U030F # COMBINING DOUBLE GRAVE ACCENT 144
<U02DE> <U02DE>                            : "˞"   U02DE # MODIFIER LETTER RHOTIC HOOK
<dead_belowdot> <dead_belowdot>            : "̣"   U0323 # COMBINING DOT BELOW 224
<Multi_key> <underscore> <underscore>      : "̲"   U0332 # COMBINING LOW LINE
<Multi_key> <rightsinglequotemark> <rightsinglequotemark> : "ʼ" U02BC # MODIFIER LETTER APOSTROPHE

# in standard Compose missing dead keys with spaces
<dead_stroke> <space>                      : "‐"   U2010 # HYPHEN 
<dead_doubleacute> <space>                 : "˝"   U02DD # DOUBLE ACUTE ACCENT 130
<dead_psili> <space>                       : "᾿"   U1FBF # GREEK PSILI 221
<dead_dasia> <space>                       : "῾"   U1FFE # GREEK DASIA 223
<U21BB> <space>                            : "↻"   U21BB # CLOCKWISE OPEN CIRCLE ARROW 139
<U02DE> <space>                            : "˞"   U02DE # MODIFIER LETTER RHOTIC HOOK
<U21BB> <dead_cedilla> <space>             : "˛"   U02DB # OGONEK 140
<dead_belowdot> <space>                    : "."   U002E # FULL STOP 225

# letters
# latin letters with ogonek (simplifying the keyboard ogonek and cedilla are on the same place)
<dead_cedilla> <A>                           : "Ą"   U0104 # LATIN CAPITAL LETTER A WITH OGONEK 127
<dead_cedilla> <a>                           : "ą"   U0105 # LATIN SMALL LETTER A WITH OGONEK 128

<dead_cedilla> <E>                           : "Ę"   U0118 # LATIN CAPITAL LETTER E WITH OGONEK 131
<dead_cedilla> <e>                           : "ę"   U0119 # LATIN SMALL LETTER E WITH OGONEK   132
<dead_cedilla> <I>                           : "Į"   U012E # LATIN CAPITAL LETTER I WITH OGONEK 133
<dead_cedilla> <i>                           : "į"   U012F # LATIN SMALL LETTER I WITH OGONEK   134
<dead_cedilla> <U>                           : "Ų"   U0172 # LATIN CAPITAL LETTER U WITH OGONEK 135
<dead_cedilla> <u>                           : "ų"   U0173 # LATIN SMALL LETTER U WITH OGONEK   136
<dead_cedilla> <O>                           : "Ǫ"   U01EA # LATIN CAPITAL LETTER O WITH OGONEK 137
<dead_cedilla> <o>                           : "ǫ"   U01EB # LATIN SMALL LETTER O WITH OGONEK   138
<dead_macron> <dead_cedilla> <O>             : "Ǭ"   U01EC # LATIN CAPITAL LETTER O WITH OGONEK AND MACRON 186
<dead_macron> <dead_cedilla> <o>             : "ǭ"   U01ED # LATIN SMALL LETTER O WITH OGONEK AND MACRON 187
<U21BB> <dead_cedilla> <E>                   : "Ȩ"   U0228 # LATIN CAPITAL LETTER E WITH CEDILLA 145
<U21BB> <dead_cedilla> <e>                   : "ȩ"   U0229 # LATIN SMALL LETTER E WITH CEDILLA  146

# latin letters with line below (simplifying the keyboard line below and macron are on the same place)
<dead_macron> <B>                            : "Ḇ"   U1E06 # LATIN CAPITAL LETTER B WITH LINE BELOW 188
<dead_macron> <b>                            : "ḇ"   U1E07 # LATIN SMALL LETTER B WITH LINE BELOW   189
<dead_macron> <D>                            : "Ḏ"   U1E0E # LATIN CAPITAL LETTER D WITH LINE BELOW 190
<dead_macron> <d>                            : "ḏ"   U1E0F # LATIN SMALL LETTER D WITH LINE BELOW   191
<dead_macron> <K>                            : "Ḵ"   U1E34 # LATIN CAPITAL LETTER K WITH LINE BELOW 192
<dead_macron> <k>                            : "ḵ"   U1E35 # LATIN SMALL LETTER K WITH LINE BELOW   193
<dead_macron> <L>                            : "Ḻ"   U1E3A # LATIN CAPITAL LETTER L WITH LINE BELOW 194
<dead_macron> <l>                            : "ḻ"   U1E3B # LATIN SMALL LETTER L WITH LINE BELOW   195
<dead_macron> <N>                            : "Ṉ"   U1E48 # LATIN CAPITAL LETTER N WITH LINE BELOW 196
<dead_macron> <n>                            : "ṉ"   U1E49 # LATIN SMALL LETTER N WITH LINE BELOW   197
<dead_macron> <R>                            : "Ṟ"   U1E5E # LATIN CAPITAL LETTER R WITH LINE BELOW 198
<dead_macron> <r>                            : "ṟ"   U1E5F # LATIN SMALL LETTER R WITH LINE BELOW   199
<dead_macron> <T>                            : "Ṯ"   U1E6E # LATIN CAPITAL LETTER T WITH LINE BELOW 200
<dead_macron> <t>                            : "ṯ"   U1E6F # LATIN SMALL LETTER T WITH LINE BELOW   201
<dead_macron> <Z>                            : "Ẕ"   U1E94 # LATIN CAPITAL LETTER Z WITH LINE BELOW 202
<dead_macron> <z>                            : "ẕ"   U1E95 # LATIN SMALL LETTER Z WITH LINE BELOW   203
<dead_macron> <h>                            : "ẖ"   U1E96 # LATIN SMALL LETTER H WITH LINE BELOW   204

# letters with stroke
<dead_stroke> <D>                        : "Đ"   0x0110 Dstroke # LATIN CAPITAL LETTER D WITH STROKE 212
<dead_stroke> <d>                        : "đ"   0x0111dstroke # LATIN SMALL LETTER D WITH STROKE   213
<dead_stroke> <H>                        : "Ħ"   Hstroke # LATIN CAPITAL LETTER H WITH STROKE 5
<Multi_key> <minus> <H>                  : "Ħ"   U0126 # LATIN CAPITAL LETTER H WITH STROKE   5
<dead_stroke> <h>                        : "ħ"   hstroke # LATIN SMALL LETTER H WITH STROKE   4
<Multi_key> <minus> <h>                  : "ħ"   U0127 # LATIN SMALL LETTER H WITH STROKE     4
<dead_stroke> <L>                        : "Ł"   0x0141 Lstroke # LATIN CAPITAL LETTER L WITH STROKE 214
<dead_stroke> <l>                        : "ł"   0x0142 lstroke # LATIN SMALL LETTER L WITH STROKE   215
<dead_stroke> <O>                        : "Ø"   0x00D8 Ooblique # LATIN CAPITAL LETTER O WITH STROKE 216
<dead_stroke> <o>                        : "ø"   0x00F8 oslash  # LATIN SMALL LETTER O WITH STROKE   217
<dead_acute> <dead_stroke> <O>           : "Ǿ"   U01FE # LATIN CAPITAL LETTER O WITH STROKE AND ACUTE 233
<dead_acute> <dead_stroke> <o>           : "ǿ"   U01FF # LATIN SMALL LETTER O WITH STROKE AND ACUTE 234

# if you want to have ð and Ð with dead stroke instead of đ and Đ you should uncomment the next two lines
# <dead_stroke> <d>                      : "ð"   U00F0 # LATIN SMALL LETTER ETH
# <dead_stroke> <D>                      : "Ð"   U00D0 # LATIN CAPITAL LETTER ETH

# letters with double grave
<U02F5> <A>                              : "Ȁ"   U0200 # LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
<U02F5> <a>                              : "ȁ"   U0201 # LATIN SMALL LETTER A WITH DOUBLE GRAVE
<U02F5> <E>                              : "Ȅ"   U0204 # LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
<U02F5> <e>                              : "ȅ"   U0205 # LATIN SMALL LETTER E WITH DOUBLE GRAVE
<U02F5> <I>                              : "Ȉ"   U0208 # LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
<U02F5> <i>                              : "ȉ"   U0209 # LATIN SMALL LETTER I WITH DOUBLE GRAVE
<U02F5> <O>                              : "Ȍ"   U020C # LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
<U02F5> <o>                              : "ȍ"   U020D # LATIN SMALL LETTER O WITH DOUBLE GRAVE
<U02F5> <R>                              : "Ȑ"   U0210 # LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
<U02F5> <r>                              : "ȑ"   U0211 # LATIN SMALL LETTER R WITH DOUBLE GRAVE
<U02F5> <U>                              : "Ȕ"   U0214 # LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
<U02F5> <u>                              : "ȕ"   U0215 # LATIN SMALL LETTER U WITH DOUBLE GRAVE
# double grave as turned double acute (will replace double grave)
<U21BB> <dead_doubleacute> <A>           : "Ȁ"   U0200 # LATIN CAPITAL LETTER A WITH DOUBLE GRAVE 147
<U21BB> <dead_doubleacute> <a>           : "ȁ"   U0201 # LATIN SMALL LETTER A WITH DOUBLE GRAVE 148
<U21BB> <dead_doubleacute> <E>           : "Ȅ"   U0204 # LATIN CAPITAL LETTER E WITH DOUBLE GRAVE 149 
<U21BB> <dead_doubleacute> <e>           : "ȅ"   U0205 # LATIN SMALL LETTER E WITH DOUBLE GRAVE 150
<U21BB> <dead_doubleacute> <I>           : "Ȉ"   U0208 # LATIN CAPITAL LETTER I WITH DOUBLE GRAVE 151
<U21BB> <dead_doubleacute> <i>           : "ȉ"   U0209 # LATIN SMALL LETTER I WITH DOUBLE GRAVE   152 
<U21BB> <dead_doubleacute> <O>           : "Ȍ"   U020C # LATIN CAPITAL LETTER O WITH DOUBLE GRAVE 153
<U21BB> <dead_doubleacute> <o>           : "ȍ"   U020D # LATIN SMALL LETTER O WITH DOUBLE GRAVE   154
<U21BB> <dead_doubleacute> <R>           : "Ȑ"   U0210 # LATIN CAPITAL LETTER R WITH DOUBLE GRAVE 155 
<U21BB> <dead_doubleacute> <r>           : "ȑ"   U0211 # LATIN SMALL LETTER R WITH DOUBLE GRAVE   156
<U21BB> <dead_doubleacute> <U>           : "Ȕ"   U0214 # LATIN CAPITAL LETTER U WITH DOUBLE GRAVE 157
<U21BB> <dead_doubleacute> <u>           : "ȕ"   U0215 # LATIN SMALL LETTER U WITH DOUBLE GRAVE   158

# letters with comma below
<Multi_key> <S> <comma>                  : "Ș"   U0218 # LATIN CAPITAL LETTER S WITH COMMA BELOW
<Multi_key> <s> <comma>                  : "ș"   U0219 # LATIN SMALL LETTER S WITH COMMA BELOW
<Multi_key> <T> <comma>                  : "Ț"   U021A # LATIN CAPITAL LETTER T WITH COMMA BELOW
<Multi_key> <t> <comma>                  : "ț"   U021B # LATIN SMALL LETTER T WITH COMMA BELOW

# letters with inverted breve
<U21BB> <dead_breve> <A>                 : "Ȃ"   U0202 # LATIN CAPITAL LETTER A WITH INVERTED BREVE 159
<U21BB> <dead_breve> <a>                 : "ȃ"   U0203 # LATIN SMALL LETTER A WITH INVERTED BREVE   160
<U21BB> <dead_breve> <E>                 : "Ȇ"   U0206 # LATIN CAPITAL LETTER E WITH INVERTED BREVE 161
<U21BB> <dead_breve> <e>                 : "ȇ"   U0207 # LATIN SMALL LETTER E WITH INVERTED BREVE   162
<U21BB> <dead_breve> <I>                 : "Ȋ"   U020A # LATIN CAPITAL LETTER I WITH INVERTED BREVE 163
<U21BB> <dead_breve> <i>                 : "ȋ"   U020B # LATIN SMALL LETTER I WITH INVERTED BREVE   164
<U21BB> <dead_breve> <O>                 : "Ȏ"   U020E # LATIN CAPITAL LETTER O WITH INVERTED BREVE 165
<U21BB> <dead_breve> <o>                 : "ȏ"   U020F # LATIN SMALL LETTER O WITH INVERTED BREVE   166
<U21BB> <dead_breve> <R>                 : "Ȓ"   U0212 # LATIN CAPITAL LETTER R WITH INVERTED BREVE 167
<U21BB> <dead_breve> <r>                 : "ȓ"   U0213 # LATIN SMALL LETTER R WITH INVERTED BREVE   168
<U21BB> <dead_breve> <U>                 : "Ȗ"   U0216 # LATIN CAPITAL LETTER U WITH INVERTED BREVE 169
<U21BB> <dead_breve> <u>                 : "ȗ"   U0217 # LATIN SMALL LETTER U WITH INVERTED BREVE   170

# other letters
<Multi_key> <E> <E>                      : "Ə"   U018F # LATIN CAPITAL LETTER SCHWA
<Multi_key> <L> <period>                 : "Ŀ"   U013F # LATIN CAPITAL LETTER L WITH MIDDLE DOT
<Multi_key> <l> <period>                 : "ŀ"   U0140 # LATIN SMALL LETTER L WITH MIDDLE DOT
<dead_abovedot> <L>                      : "Ŀ"   U013F # LATIN CAPITAL LETTER L WITH MIDDLE DOT 12
<dead_abovedot> <l>                      : "ŀ"   U0140 # LATIN SMALL LETTER L WITH MIDDLE DOT 11
<dead_tilde> <L>                         : "Ɫ"   U2C62 # LATIN CAPITAL LETTER L WITH MIDDLE TILDE 182
<dead_tilde> <l>                         : "ɫ"   U026B # LATIN SMALL LETTER L WITH MIDDLE TILDE 183
<dead_breve> <H>                         : "Ḫ"   U1E2A # LATIN CAPITAL LETTER H WITH BREVE BELOW 107
<dead_breve> <h>                         : "ḫ"   U1E2B # LATIN SMALL LETTER H WITH BREVE BELOW 108
<Multi_key> <i> <i>                      : "ı"   U0131 # LATIN SMALL LETTER DOTLESS I
<Multi_key> <I> <I>                      : "İ"   U0130 # LATIN CAPITAL LETTER I WITH DOT ABOVE
<dead_abovedot> <j>                      : "ȷ"   U0237 # LATIN SMALL LETTER DOTLESS J 177
<dead_macron> <Multi_key> <A> <E>        : "Ǣ"   U01E2 # LATIN CAPITAL LETTER AE WITH MACRON 205
<dead_macron> <Multi_key> <a> <e>        : "ǣ"   U01E3 # LATIN SMALL LETTER AE WITH MACRON   206
<dead_acute> <Multi_key> <A> <E>         : "Ǽ"   U01FC # LATIN CAPITAL LETTER AE WITH ACUTE 235
<dead_acute> <Multi_key> <a> <e>         : "ǽ"   U01FD # LATIN SMALL LETTER AE WITH ACUTE 236
<Multi_key> <z> <h>                      : "ʒ"   U0292 # LATIN SMALL LETTER EZH
<Multi_key> <z> <z>                      : "ʒ"   U0292 # LATIN SMALL LETTER EZH

# ligatures
<Multi_key> <f> <f>                      : "ﬀ"   UFB00 # LATIN SMALL LIGATURE FF
<Multi_key> <f> <i>                      : "ﬁ"   UFB01 # LATIN SMALL LIGATURE FI
<Multi_key> <f> <l>                      : "ﬂ"   UFB02 # LATIN SMALL LIGATURE FL
<Multi_key> <F> <i>                      : "ﬃ"   UFB03 # LATIN SMALL LIGATURE FFI
<Multi_key> <F> <l>                      : "ﬄ"   UFB04 # LATIN SMALL LIGATURE FFL
<Multi_key> <U017F> <t>                  : "ﬅ"   UFB05 # LATIN SMALL LIGATURE LONG S T
<Multi_key> <s> <t>                      : "ﬆ"   UFB06 # LATIN SMALL LIGATURE ST
<Multi_key> <I> <J>                      : "Ĳ"   U0132 # LATIN CAPITAL LIGATURE IJ
<Multi_key> <i> <j>                      : "ĳ"   U0133 # LATIN SMALL LIGATURE IJ
<Multi_key> <D> <Z>                      : "Ǳ"   U01F1 # LATIN CAPITAL LETTER DZ
<Multi_key> <D> <z>                      : "ǲ"   U01F2 # LATIN CAPITAL LETTER D WITH SMALL LETTER Z
<Multi_key> <d> <z>                      : "ǳ"   U01F3 # LATIN SMALL LETTER DZ
<dead_caron> <Multi_key> <D> <Z>         : "Ǆ"   U01C4 # LATIN CAPITAL LETTER DZ WITH CARON 112
<dead_caron> <Multi_key> <D> <z>         : "ǅ"   U01C5 # LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON 113
<dead_caron> <Multi_key> <d> <z>         : "ǆ"   U01C6 # LATIN SMALL LETTER DZ WITH CARON 114
<Multi_key> <L> <J>                      : "Ǉ"   U01C7 # LATIN CAPITAL LETTER LJ
<Multi_key> <L> <j>                      : "ǈ"   U01C8 # LATIN CAPITAL LETTER L WITH SMALL LETTER J
<Multi_key> <l> <j>                      : "ǉ"   U01C9 # LATIN SMALL LETTER LJ
<Multi_key> <N> <J>                      : "Ǌ"   U01CA # LATIN CAPITAL LETTER NJ
<Multi_key> <N> <j>                      : "ǋ"   U01CB # LATIN CAPITAL LETTER N WITH SMALL LETTER J
<Multi_key> <n> <j>                      : "ǌ"   U01CC # LATIN SMALL LETTER NJ

<dead_caron> <0>                         : "₀"   U2080 # SUBSCRIPT ZERO 115
<dead_caron> <KP_0>                      : "₀"   U2080 # SUBSCRIPT ZERO
<dead_caron> <1>                         : "₁"   U2081 # SUBSCRIPT ONE 116
<dead_caron> <KP_1>                      : "₁"   U2081 # SUBSCRIPT ONE
<dead_caron> <2>                         : "₂"   U2082 # SUBSCRIPT TWO 117
<dead_caron> <KP_2>                      : "₂"   U2082 # SUBSCRIPT TWO
<dead_caron> <3>                         : "₃"   U2083 # SUBSCRIPT THREE 118
<dead_caron> <KP_3>                      : "₃"   U2083 # SUBSCRIPT THREE
<dead_caron> <4>                         : "₄"   U2084 # SUBSCRIPT FOUR 119
<dead_caron> <KP_4>                      : "₄"   U2084 # SUBSCRIPT FOUR
<dead_caron> <5>                         : "₅"   U2085 # SUBSCRIPT FIVE 120
<dead_caron> <KP_5>                      : "₅"   U2085 # SUBSCRIPT FIVE
<dead_caron> <6>                         : "₆"   U2086 # SUBSCRIPT SIX 121
<dead_caron> <KP_6>                      : "₆"   U2086 # SUBSCRIPT SIX
<dead_caron> <7>                         : "₇"   U2087 # SUBSCRIPT SEVEN 122
<dead_caron> <KP_7>                      : "₇"   U2087 # SUBSCRIPT SEVEN
<dead_caron> <8>                         : "₈"   U2088 # SUBSCRIPT EIGHT 123
<dead_caron> <KP_8>                      : "₈"   U2088 # SUBSCRIPT EIGHT
<dead_caron> <9>                         : "₉"   U2089 # SUBSCRIPT NINE 124
<dead_caron> <KP_9>                      : "₉"   U2089 # SUBSCRIPT NINE

# interpunctation
<Multi_key> <2> <exclam>                         : "‼"   U203C # DOUBLE EXCLAMATION MARK
<Multi_key> <exclam> <2>                         : "‼"   U203C # DOUBLE EXCLAMATION MARK
<Multi_key> <KP_2> <exclam>                      : "‼"   U203C # DOUBLE EXCLAMATION MARK
<Multi_key> <exclam> <KP_2>                      : "‼"   U203C # DOUBLE EXCLAMATION MARK
<Multi_key> <2> <question>                       : "⁇"   U2047 # DOUBLE QUESTION MARK
<Multi_key> <question> <2>                       : "⁇"   U2047 # DOUBLE QUESTION MARK
<Multi_key> <KP_2> <question>                    : "⁇"   U2047 # DOUBLE QUESTION MARK
<Multi_key> <question> <KP_2>                    : "⁇"   U2047 # DOUBLE QUESTION MARK
<Multi_key> <question> <exclam>                  : "⁈"   U2048 # QUESTION EXCLAMATION MARK
<Multi_key> <exclam> <question>                  : "⁉"   U2049 # EXCLAMATION QUESTION MARK
<Multi_key> <1> <question> <exclam>              : "‽"   U203D # INTERROBANG
<Multi_key> <1> <exclam> <question>              : "‽"   U203D # INTERROBANG
<Multi_key> <KP_1> <question> <exclam>           : "‽"   U203D # INTERROBANG
<Multi_key> <KP_1> <exclam> <question>           : "‽"   U203D # INTERROBANG
<Multi_key> <1> <questiondown> <exclamdown>      : "⸘"   U2E18 # INVERTED INTERROBANG
<Multi_key> <1> <exclamdown> <questiondown>      : "⸘"   U2E18 # INVERTED INTERROBANG
<Multi_key> <KP_1> <questiondown> <exclamdown>   : "⸘"   U2E18 # INVERTED INTERROBANG
<Multi_key> <KP_1> <exclamdown> <questiondown>   : "⸘"   U2E18 # INVERTED INTERROBANG
<Multi_key> <dagger> <dagger>                    : "‡"   U2021 # DOUBLE DAGGER
<U21BB> <colon>                                  : "‥"   U2025 # TWO DOT LEADER   171
<U21BB> <ellipsis>                               : "⋮"   U22EE # VERTICAL ELLIPSIS 
<Multi_key> <nobreakspace> <nobreakspace>        : "-"   minus # HYPHEN-MINUS
<Multi_key> <7> <7>                              : "⁊"   U204A # TIRONIAN SIGN ET
<Multi_key> <KP_7> <KP_7>                        : "⁊"   U204A # TIRONIAN SIGN ET
<Multi_key> <ellipsis> <ellipsis>                : "[…]"

# roman numerals
<Multi_key> <R> <1> <space>              : "Ⅰ"   U2160 # ROMAN NUMERAL ONE
<Multi_key> <R> <2>                      : "Ⅱ"   U2161 # ROMAN NUMERAL TWO
<Multi_key> <R> <3>                      : "Ⅲ"   U2162 # ROMAN NUMERAL THREE
<Multi_key> <R> <4>                      : "Ⅳ"   U2163 # ROMAN NUMERAL FOUR
<Multi_key> <R> <5>                      : "Ⅴ"   U2164 # ROMAN NUMERAL FIVE
<Multi_key> <R> <6>                      : "Ⅵ"   U2165 # ROMAN NUMERAL SIX
<Multi_key> <R> <7>                      : "Ⅶ"   U2166 # ROMAN NUMERAL SEVEN
<Multi_key> <R> <8>                      : "Ⅷ"   U2167 # ROMAN NUMERAL EIGHT
<Multi_key> <R> <9>                      : "Ⅸ"   U2168 # ROMAN NUMERAL NINE
<Multi_key> <R> <1> <0>                  : "Ⅹ"   U2169 # ROMAN NUMERAL TEN
<Multi_key> <R> <1> <1>                  : "Ⅺ"   U216A # ROMAN NUMERAL ELEVEN
<Multi_key> <R> <1> <2>                  : "Ⅻ"   U216B # ROMAN NUMERAL TWELVE
<Multi_key> <R> <KP_1> <space>           : "Ⅰ"   U2160 # ROMAN NUMERAL ONE
<Multi_key> <R> <KP_2>                   : "Ⅱ"   U2161 # ROMAN NUMERAL TWO
<Multi_key> <R> <KP_3>                   : "Ⅲ"   U2162 # ROMAN NUMERAL THREE
<Multi_key> <R> <KP_4>                   : "Ⅳ"   U2163 # ROMAN NUMERAL FOUR
<Multi_key> <R> <KP_5>                   : "Ⅴ"   U2164 # ROMAN NUMERAL FIVE
<Multi_key> <R> <KP_6>                   : "Ⅵ"   U2165 # ROMAN NUMERAL SIX
<Multi_key> <R> <KP_7>                   : "Ⅶ"   U2166 # ROMAN NUMERAL SEVEN
<Multi_key> <R> <KP_8>                   : "Ⅷ"   U2167 # ROMAN NUMERAL EIGHT
<Multi_key> <R> <KP_9>                   : "Ⅸ"   U2168 # ROMAN NUMERAL NINE
<Multi_key> <R> <KP_1> <KP_0>            : "Ⅹ"   U2169 # ROMAN NUMERAL TEN
<Multi_key> <R> <KP_1> <KP_1>            : "Ⅺ"   U216A # ROMAN NUMERAL ELEVEN
<Multi_key> <R> <KP_1> <KP_2>            : "Ⅻ"   U216B # ROMAN NUMERAL TWELVE

<Multi_key> <r> <1>  <space>             : "ⅰ"   U2170 # SMALL ROMAN NUMERAL ONE
<Multi_key> <r> <1>  <period>            : "ⅰ."
<Multi_key> <r> <1>  <parenright>        : "ⅰ)"
<Multi_key> <r> <2>                      : "ⅱ"   U2171 # SMALL ROMAN NUMERAL TWO
<Multi_key> <r> <3>                      : "ⅲ"   U2172 # SMALL ROMAN NUMERAL THREE
<Multi_key> <r> <4>                      : "ⅳ"   U2173 # SMALL ROMAN NUMERAL FOUR
<Multi_key> <r> <5>                      : "ⅴ"   U2174 # SMALL ROMAN NUMERAL FIVE
<Multi_key> <r> <6>                      : "ⅵ"   U2175 # SMALL ROMAN NUMERAL SIX
<Multi_key> <r> <7>                      : "ⅶ"   U2176 # SMALL ROMAN NUMERAL SEVEN
<Multi_key> <r> <8>                      : "ⅷ"   U2177 # SMALL ROMAN NUMERAL EIGHT
<Multi_key> <r> <9>                      : "ⅸ"   U2178 # SMALL ROMAN NUMERAL NINE
<Multi_key> <r> <1> <0>                  : "ⅹ"   U2179 # SMALL ROMAN NUMERAL TEN
<Multi_key> <r> <1> <1>                  : "ⅺ"   U217A # SMALL ROMAN NUMERAL ELEVEN
<Multi_key> <r> <1> <2>                  : "ⅻ"   U217B # SMALL ROMAN NUMERAL TWELVE
<Multi_key> <r> <KP_1> <space>           : "ⅰ"   U2170 # SMALL ROMAN NUMERAL ONE
<Multi_key> <r> <KP_2>                   : "ⅱ"   U2171 # SMALL ROMAN NUMERAL TWO
<Multi_key> <r> <KP_3>                   : "ⅲ"   U2172 # SMALL ROMAN NUMERAL THREE
<Multi_key> <r> <KP_4>                   : "ⅳ"   U2173 # SMALL ROMAN NUMERAL FOUR
<Multi_key> <r> <KP_5>                   : "ⅴ"   U2174 # SMALL ROMAN NUMERAL FIVE
<Multi_key> <r> <KP_6>                   : "ⅵ"   U2175 # SMALL ROMAN NUMERAL SIX
<Multi_key> <r> <KP_7>                   : "ⅶ"   U2176 # SMALL ROMAN NUMERAL SEVEN
<Multi_key> <r> <KP_8>                   : "ⅷ"   U2177 # SMALL ROMAN NUMERAL EIGHT
<Multi_key> <r> <KP_9>                   : "ⅸ"   U2178 # SMALL ROMAN NUMERAL NINE
<Multi_key> <r> <KP_1> <KP_0>            : "ⅹ"   U2179 # SMALL ROMAN NUMERAL TEN
<Multi_key> <r> <KP_1> <KP_1>            : "ⅺ"   U217A # SMALL ROMAN NUMERAL ELEVEN
<Multi_key> <r> <KP_1> <KP_2>            : "ⅻ"   U217B # SMALL ROMAN NUMERAL TWELVE

# ordinal numbers in English and French
<Multi_key> <1> <s> <t>                  : "1ˢᵗ"
<Multi_key> <KP_1> <s> <t>               : "1ˢᵗ"
<Multi_key> <2> <n> <d>                  : "2ⁿᵈ"
<Multi_key> <KP_2> <n> <d>               : "2ⁿᵈ"
<Multi_key> <3> <r> <d>                  : "3ʳᵈ"
<Multi_key> <KP_3> <r> <d>               : "3ʳᵈ"
<Multi_key> <4> <t> <h>                  : "4ᵗʰ"
<Multi_key> <KP_4> <t> <h>               : "4ᵗʰ"
<Multi_key> <1> <e> <r>                  : "1ᵉʳ"
<Multi_key> <KP_1> <e> <r>               : "1ᵉʳ"
<Multi_key> <1> <r> <e>                  : "1ʳᵉ"
<Multi_key> <KP_1> <r> <e>               : "1ʳᵉ"
<Multi_key> <2> <e>                      : "2ᵉ"
<Multi_key> <KP_2> <e>                   : "2ᵉ"

# Fractions
<Multi_key> <1> <3>                        : "⅓"   U2153 # VULGAR FRACTION ONE THIRD
<Multi_key> <2> <3>                        : "⅔"   U2154 # VULGAR FRACTION TWO THIRDS
<Multi_key> <1> <5>                        : "⅕"   U2155 # VULGAR FRACTION ONE FIFTH
<Multi_key> <2> <5>                        : "⅖"   U2156 # VULGAR FRACTION TWO FIFTHS
<Multi_key> <3> <5>                        : "⅗"   U2157 # VULGAR FRACTION THREE FIFTHS
<Multi_key> <4> <5>                        : "⅘"   U2158 # VULGAR FRACTION FOUR FIFTHS
<Multi_key> <1> <6>                        : "⅙"   U2159 # VULGAR FRACTION ONE SIXTH
<Multi_key> <5> <6>                        : "⅚"   U215A # VULGAR FRACTION FIVE SIXTHS    74
<Multi_key> <1> <8>                        : "⅛"   U215B # VULGAR FRACTION ONE EIGHTH     75 
<Multi_key> <3> <8>                        : "⅜"   U215C # VULGAR FRACTION THREE EIGHTHS  76
<Multi_key> <5> <8>                        : "⅝"   U215D # VULGAR FRACTION FIVE EIGHTHS   77
<Multi_key> <7> <8>                        : "⅞"   U215E # VULGAR FRACTION SEVEN EIGHTHS  78
<Multi_key> <1> <slash>                    : "⅟"   U215F # FRACTION NUMERATOR ONE          79
<Multi_key> <1> <KP_Divide>                : "⅟"   U215F # FRACTION NUMERATOR ONE
<Multi_key> <KP_1> <KP_3>                  : "⅓"   U2153 # VULGAR FRACTION ONE THIRD
<Multi_key> <KP_2> <KP_3>                  : "⅔"   U2154 # VULGAR FRACTION TWO THIRDS
<Multi_key> <KP_1> <KP_5>                  : "⅕"   U2155 # VULGAR FRACTION ONE FIFTH
<Multi_key> <KP_2> <KP_5>                  : "⅖"   U2156 # VULGAR FRACTION TWO FIFTHS
<Multi_key> <KP_3> <KP_5>                  : "⅗"   U2157 # VULGAR FRACTION THREE FIFTHS
<Multi_key> <KP_4> <KP_5>                  : "⅘"   U2158 # VULGAR FRACTION FOUR FIFTHS
<Multi_key> <KP_1> <KP_6>                  : "⅙"   U2159 # VULGAR FRACTION ONE SIXTH
<Multi_key> <KP_5> <KP_6>                  : "⅚"   U215A # VULGAR FRACTION FIVE SIXTHS
<Multi_key> <KP_1> <KP_8>                  : "⅛"   U215B # VULGAR FRACTION ONE EIGHTHS
<Multi_key> <KP_3> <KP_8>                  : "⅜"   U215C # VULGAR FRACTION THREE EIGHTHS
<Multi_key> <KP_5> <KP_8>                  : "⅝"   U215D # VULGAR FRACTION FIVE EIGHTHS
<Multi_key> <KP_7> <KP_8>                  : "⅞"   U215E # VULGAR FRACTION SEVEN EIGHTHS
<Multi_key> <KP_1> <slash>                 : "⅟"   U215F # FRACTION NUMERATOR ONE
<Multi_key> <KP_1> <KP_Divide>             : "⅟"   U215F # FRACTION NUMERATOR ONE
<Multi_key> <KP_1> <KP_4>                  : "¼"   U00BC # VULGAR FRACTION ONE QUARTER    80
<Multi_key> <KP_1> <KP_2>                  : "½"   U00BD # VULGAR FRACTION ONE HALF       81
<Multi_key> <KP_3> <KP_4>                  : "¾"   U00BE # VULGAR FRACTION THREE QUARTERS 82

# other symbols
<Multi_key> <colon> <parenright>           : "☺"   U263A # WHITE SMILING FACE   83
<Multi_key> <colon> <parenleft>            : "☹"   U2639 # WHITE FROWNING FACE 84
<Multi_key> <t> <m>                        : "™"   trademark # TRADE MARK SIGN  85
<Multi_key> <c> <KP_Divide> <o>            : "℅"   U2105 # CARE OF              86
<Multi_key> <femalesymbol> <femalesymbol>  : "⚢"   U26A2 # DOUBLED FEMALE SIGN   87
<Multi_key> <malesymbol> <malesymbol>      : "⚣"   U26A3 # DOUBLED MALE SIGN     88
<Multi_key> <femalesymbol> <malesymbol>    : "⚤"   U26A4 # INTERLOCKED FEMALE AND MALE SIGN 89
<Multi_key> <malesymbol> <femalesymbol>    : "⚤"   U26A4 # INTERLOCKED FEMALE AND MALE SIGN 89
<dead_stroke> <malesymbol>                 : "⚦"   U26A6 # MALE WITH STROKE SIGN 218
<dead_stroke> <U26A5>                      : "⚧"   U26A7 # MALE WITH STROKE AND MALE AND FEMALE SIGN  219
<dead_breve> <femalesymbol>                : "☿"   U263F # MERCURY 109
<U21BB> <femalesymbol>                     : "♁"   U2641 # EARTH  172
<Multi_key> <Tab>                          : "♫"   U266B # BEAMED EIGHTH NOTE
<Multi_key> <Multi_key>                    : "♫"   U266B # BEAMED EIGHTH NOTE
<U02DE> <slash>                            : "✔"   U2714 # HEAVY CHECK MARK
<U02DE> <KP_Divide>                        : "✔"   U2714 # HEAVY CHECK MARK
<U02DE> <backslash>                        : "✔"   U2714 # HEAVY CHECK MARK
<dead_stroke> <slash>                      : "✘"   U2718 # HEAVY BALLOT X 211
<dead_stroke> <KP_Divide>                  : "✘"   U2718 # HEAVY BALLOT X
<dead_stroke> <backslash>                  : "✘"   U2718 # HEAVY BALLOT X
<Multi_key> <less> <3>                     : "♥"   U2665 # BLACK HEART SUIT 90
<Multi_key> <less> <KP_3>                  : "♥"   U2665 # BLACK HEART SUIT 90
<Multi_key> <C> <N> <D>                    : "☮"   U262E # PEACE SYMBOL    91
<Multi_key> <bracketleft> <bracketright>   : "□"   U25A1 # WHITE SQUARE     92
<Multi_key> <U25A1> <U2714>                : "☑"   U2611 # BALLOT BOX WITH CHECK 93
<Multi_key> <U2714> <U25A1>                : "☑"   U2611 # BALLOT BOX WITH CHECK 93
<Multi_key> <U25A1> <U2718>                : "☒"   U2612 # BALLOT BOX WITH        94
<Multi_key> <U2718> <U25A1>                : "☒"   U2612 # BALLOT BOX WITH X      94
<Multi_key> <Greek_DELTA> <exclam>         : "⚠"   U26A0 # WARNING SIGN          95
<Multi_key> <exclam> <Greek_DELTA>         : "⚠"   U26A0 # WARNING SIGN          95
<U21BB> <bracketright>                     : "␣"   U2423 # OPEN BOX               173
<Multi_key> <U2423> <U2423>                : "⍽"   U237D # SHOULDERED OPEN BOX   96
<Multi_key> <p> <f>                        : "₰"   U20B0 # GERMAN PENNY SIGN     97
<dead_stroke> <sterling>                   : "₤"   U20A4 # LIRA SIGN
<Multi_key> <minus> <sterling>             : "₤"   U20A4 # LIRA SIGN             98
<Multi_key> <p> <o> <i>                    : "⌘"   U2318 # PLACE OF INTEREST SIGN 99
<Multi_key> <o> <p> <t>                    : "⌥"   U2325 # OPTION KEY              100
<Multi_key> <d> <a> <g>                    : "†"   U2020 # DAGGER                  101
<U21BB> <U21CC>                            : "⇋"   U21CB # LEFTWARDS HARPOON OVER RIGHTWARDS HARPOON 174
<Multi_key> <period> <slash> <period>      : "⁒"   U2052 # COMMERCIAL MINUS SIGN   102
<Multi_key> <period> <KP_Divide> <period>  : "⁒"   U2052 # COMMERCIAL MINUS SIGN   102
<Multi_key> <enfilledcircbullet> <enfilledcircbullet> : "‣" U2023 # TRIANGULAR BULLET 103

# End of standard Definitions by Neo keyboard layout
