#most of the stuff from en_US.UTF-8.module

<Multi_key> <plus> <minus>       	: "±"   plusminus # PLUS-MINUS SIGN
<Multi_key> <minus> <plus> 		: "±"   plusminus # PLUS-MINUS SIGN
<Multi_key> <p> <exclam>         	: "¶"   paragraph # PILCROW SIGN
<Multi_key> <P> <exclam>         	: "¶"   paragraph # PILCROW SIGN

<Multi_key> <exclam> <exclam>    	: "¡"   exclamdown # INVERTED EXCLAMATION MARK
<Multi_key> <question> <question> 	: "¿"   questiondown # INVERTED QUESTION MARK

<Multi_key> <s> <s>              	: "ß"   ssharp # LATIN SMALL LETTER SHARP S
<Multi_key> <S> <S>              	: "ẞ"   U1e9e # LATIN CAPITAL LETTER SHARP S
<Multi_key> <o> <e>              	: "œ"   oe # LATIN SMALL LIGATURE OE
<Multi_key> <O> <E>              	: "Œ"   OE # LATIN CAPITAL LIGATURE OE
<Multi_key> <a> <e>              	: "æ"   ae # LATIN SMALL LETTER AE
<Multi_key> <A> <E>              	: "Æ"   AE # LATIN CAPITAL LETTER AE
<Multi_key> <f> <f>              	: "ﬀ"   Ufb00 # LATIN SMALL LIGATURE FF
<Multi_key> <f> <i>              	: "ﬁ"   Ufb01 # LATIN SMALL LIGATURE FI
<Multi_key> <f> <l>              	: "ﬂ"   Ufb02 # LATIN SMALL LIGATURE FL
<Multi_key> <F> <i>              	: "ﬃ"   Ufb03 # LATIN SMALL LIGATURE FFI
<Multi_key> <F> <l>              	: "ﬄ"   Ufb04 # LATIN SMALL LIGATURE FFL
<Multi_key> <I> <J>              	: "Ĳ"   U0132 # LATIN CAPITAL LIGATURE IJ
<Multi_key> <I> <j>              	: "Ĳ"   U0132 # LATIN CAPITAL LIGATURE IJ
<Multi_key> <i> <j>              	: "ĳ"   U0133 # LATIN SMALL LIGATURE IJ

<Multi_key> <1> <4>              	: "¼"   onequarter # VULGAR FRACTION ONE QUARTER
<Multi_key> <1> <2>              	: "½"   onehalf # VULGAR FRACTION ONE HALF
<Multi_key> <3> <4>              	: "¾"   threequarters # VULGAR FRACTION THREE QUARTERS
<Multi_key> <1> <7>			: "⅐"	U2150 # VULGAR FRACTION ONE SEVENTH
<Multi_key> <1> <9>			: "⅑"	U2151 # VULGAR FRACTION ONE NINTH
<Multi_key> <1> <1> <0>			: "⅒"	U2152 # VULGAR FRACTION ONE TENTH
<Multi_key> <1> <3>			: "⅓"	U2153 # VULGAR FRACTION ONE THIRD
<Multi_key> <2> <3>			: "⅔"	U2154 # VULGAR FRACTION TWO THIRDS
<Multi_key> <1> <5>			: "⅕"	U2155 # VULGAR FRACTION ONE FIFTH
<Multi_key> <2> <5>			: "⅖"	U2156 # VULGAR FRACTION TWO FIFTHS
<Multi_key> <3> <5>			: "⅗"	U2157 # VULGAR FRACTION THREE FIFTHS
<Multi_key> <4> <5>			: "⅘"	U2158 # VULGAR FRACTION FOUR FIFTHS
<Multi_key> <1> <6>			: "⅙"	U2159 # VULGAR FRACTION ONE SIXTH
<Multi_key> <5> <6>			: "⅚"	U215A # VULGAR FRACTION FIVE SIXTHS
<Multi_key> <1> <8>			: "⅛"	U215B # VULGAR FRACTION ONE EIGHTH
<Multi_key> <3> <8>			: "⅜"	U215C # VULGAR FRACTION THREE EIGHTHS
<Multi_key> <5> <8>			: "⅝"	U215D # VULGAR FRACTION FIVE EIGHTHS
<Multi_key> <7> <8>			: "⅞"	U215E # VULGAR FRACTION SEVEN EIGHTHS
<Multi_key> <0> <3>			: "↉"	U2189 # VULGAR FRACTION ZERO THIRDS
<Multi_Key> <colon> <minus>      	: "÷"   division # DIVISION SIGN
<Multi_Key> <minus> <colon>      	: "÷"   division # DIVISION SIGN
<dead_circumflex> <0>            	: "⁰"   U2070 # SUPERSCRIPT ZERO
<Multi_key> <asciicircum> <0>    	: "⁰"   U2070 # SUPERSCRIPT ZERO
<dead_circumflex> <KP_0>         	: "⁰"   U2070 # SUPERSCRIPT ZERO
<Multi_key> <asciicircum> <KP_0> 	: "⁰"   U2070 # SUPERSCRIPT ZERO
<dead_circumflex> <Multi_key> <underscore> <i> 	: "ⁱ"   U2071 # SUPERSCRIPT LATIN SMALL LETTER I
<Multi_key> <asciicircum> <underscore> <i> 	: "ⁱ"   U2071 # SUPERSCRIPT LATIN SMALL LETTER I
<dead_circumflex> <2>            	: "²"   twosuperior # SUPERSCRIPT TWO
<Multi_key> <asciicircum> <2>    	: "²"   twosuperior # SUPERSCRIPT TWO
<Multi_key> <2> <asciicircum> 		: "²"   twosuperior # SUPERSCRIPT TWO
<dead_circumflex> <KP_2>         	: "²"   twosuperior # SUPERSCRIPT TWO
<Multi_key> <asciicircum> <KP_2> 	: "²"   twosuperior # SUPERSCRIPT TWO
<dead_circumflex> <3>            	: "³"   threesuperior # SUPERSCRIPT THREE
<Multi_key> <asciicircum> <3>    	: "³"   threesuperior # SUPERSCRIPT THREE
<Multi_key> <3> <asciicircum> 		: "³"   threesuperior # SUPERSCRIPT THREE
<dead_circumflex> <KP_3>         	: "³"   threesuperior # SUPERSCRIPT THREE
<Multi_key> <asciicircum> <KP_3> 	: "³"   threesuperior # SUPERSCRIPT THREE
<Multi_key> <m> <u>              	: "µ"   mu # MICRO SIGN
<dead_circumflex> <1>            	: "¹"   onesuperior # SUPERSCRIPT ONE
<Multi_key> <asciicircum> <1>    	: "¹"   onesuperior # SUPERSCRIPT ONE
<Multi_key> <1> <asciicircum> 		: "¹"   onesuperior # SUPERSCRIPT ONE
<dead_circumflex> <KP_1>         	: "¹"   onesuperior # SUPERSCRIPT ONE
<Multi_key> <asciicircum> <KP_1> 	: "¹"   onesuperior # SUPERSCRIPT ONE
<dead_circumflex> <4>            	: "⁴"   U2074 # SUPERSCRIPT FOUR
<Multi_key> <asciicircum> <4>    	: "⁴"   U2074 # SUPERSCRIPT FOUR
<dead_circumflex> <KP_4>         	: "⁴"   U2074 # SUPERSCRIPT FOUR
<Multi_key> <asciicircum> <KP_4> 	: "⁴"   U2074 # SUPERSCRIPT FOUR
<dead_circumflex> <5>            	: "⁵"   U2075 # SUPERSCRIPT FIVE
<Multi_key> <asciicircum> <5>    	: "⁵"   U2075 # SUPERSCRIPT FIVE
<dead_circumflex> <KP_5>         	: "⁵"   U2075 # SUPERSCRIPT FIVE
<Multi_key> <asciicircum> <KP_5> 	: "⁵"   U2075 # SUPERSCRIPT FIVE
<dead_circumflex> <6>            	: "⁶"   U2076 # SUPERSCRIPT SIX
<Multi_key> <asciicircum> <6>    	: "⁶"   U2076 # SUPERSCRIPT SIX
<dead_circumflex> <KP_6>         	: "⁶"   U2076 # SUPERSCRIPT SIX
<Multi_key> <asciicircum> <KP_6> 	: "⁶"   U2076 # SUPERSCRIPT SIX
<dead_circumflex> <7>            	: "⁷"   U2077 # SUPERSCRIPT SEVEN
<Multi_key> <asciicircum> <7>    	: "⁷"   U2077 # SUPERSCRIPT SEVEN
<dead_circumflex> <KP_7>         	: "⁷"   U2077 # SUPERSCRIPT SEVEN
<Multi_key> <asciicircum> <KP_7> 	: "⁷"   U2077 # SUPERSCRIPT SEVEN
<dead_circumflex> <8>            	: "⁸"   U2078 # SUPERSCRIPT EIGHT
<Multi_key> <asciicircum> <8>    	: "⁸"   U2078 # SUPERSCRIPT EIGHT
<dead_circumflex> <KP_8>         	: "⁸"   U2078 # SUPERSCRIPT EIGHT
<Multi_key> <asciicircum> <KP_8> 	: "⁸"   U2078 # SUPERSCRIPT EIGHT
<dead_circumflex> <9>            	: "⁹"   U2079 # SUPERSCRIPT NINE
<Multi_key> <asciicircum> <9>    	: "⁹"   U2079 # SUPERSCRIPT NINE
<dead_circumflex> <KP_9>         	: "⁹"   U2079 # SUPERSCRIPT NINE
<Multi_key> <asciicircum> <KP_9> 	: "⁹"   U2079 # SUPERSCRIPT NINE
<dead_circumflex> <plus>         	: "⁺"   U207A # SUPERSCRIPT PLUS SIGN
<Multi_key> <asciicircum> <plus> 	: "⁺"   U207A # SUPERSCRIPT PLUS SIGN
<dead_circumflex> <KP_Add>       	: "⁺"   U207A # SUPERSCRIPT PLUS SIGN
<Multi_key> <asciicircum> <KP_Add> 	: "⁺"   U207A # SUPERSCRIPT PLUS SIGN
<dead_circumflex> <minus> 		: "⁻"   U207B # SUPERSCRIPT MINUS
<dead_circumflex> <equal>        	: "⁼"   U207C # SUPERSCRIPT EQUALS SIGN
<Multi_key> <asciicircum> <equal> 	: "⁼"   U207C # SUPERSCRIPT EQUALS SIGN
<dead_circumflex> <parenleft>    	: "⁽"   U207D # SUPERSCRIPT LEFT PARENTHESIS
<Multi_key> <asciicircum> <parenleft> 	: "⁽"   U207D # SUPERSCRIPT LEFT PARENTHESIS
<dead_circumflex> <parenright>   	: "⁾"   U207E # SUPERSCRIPT RIGHT PARENTHESIS
<Multi_key> <asciicircum> <parenright> 	: "⁾"   U207E # SUPERSCRIPT RIGHT PARENTHESIS
<dead_circumflex> <Multi_key> <underscore> <n> 	: "ⁿ"   U207F # SUPERSCRIPT LATIN SMALL LETTER N
<Multi_key> <asciicircum> <underscore> <n> 	: "ⁿ"   U207F # SUPERSCRIPT LATIN SMALL LETTER N
<Multi_key> <underscore> <0>     	: "₀"   U2080 # SUBSCRIPT ZERO
<Multi_key> <underscore> <KP_0>  	: "₀"   U2080 # SUBSCRIPT ZERO
<Multi_key> <underscore> <1>     	: "₁"   U2081 # SUBSCRIPT ONE
<Multi_key> <underscore> <KP_1>  	: "₁"   U2081 # SUBSCRIPT ONE
<Multi_key> <underscore> <2>     	: "₂"   U2082 # SUBSCRIPT TWO
<Multi_key> <underscore> <KP_2>  	: "₂"   U2082 # SUBSCRIPT TWO
<Multi_key> <underscore> <3>     	: "₃"   U2083 # SUBSCRIPT THREE
<Multi_key> <underscore> <KP_3>  	: "₃"   U2083 # SUBSCRIPT THREE
<Multi_key> <underscore> <4>     	: "₄"   U2084 # SUBSCRIPT FOUR
<Multi_key> <underscore> <KP_4>  	: "₄"   U2084 # SUBSCRIPT FOUR
<Multi_key> <underscore> <5>     	: "₅"   U2085 # SUBSCRIPT FIVE
<Multi_key> <underscore> <KP_5>  	: "₅"   U2085 # SUBSCRIPT FIVE
<Multi_key> <underscore> <6>     	: "₆"   U2086 # SUBSCRIPT SIX
<Multi_key> <underscore> <KP_6>  	: "₆"   U2086 # SUBSCRIPT SIX
<Multi_key> <underscore> <7>     	: "₇"   U2087 # SUBSCRIPT SEVEN
<Multi_key> <underscore> <KP_7>  	: "₇"   U2087 # SUBSCRIPT SEVEN
<Multi_key> <underscore> <8>     	: "₈"   U2088 # SUBSCRIPT EIGHT
<Multi_key> <underscore> <KP_8>  	: "₈"   U2088 # SUBSCRIPT EIGHT
<Multi_key> <underscore> <9>     	: "₉"   U2089 # SUBSCRIPT NINE
<Multi_key> <underscore> <KP_9>  	: "₉"   U2089 # SUBSCRIPT NINE
<Multi_key> <underscore> <plus>  	: "₊"   U208A # SUBSCRIPT PLUS SIGN
<Multi_key> <underscore> <KP_Add> 	: "₊"   U208A # SUBSCRIPT PLUS SIGN
<Multi_key> <underscore> <equal> 	: "₌"   U208C # SUBSCRIPT EQUALS SIGN
<Multi_key> <underscore> <parenleft> 	: "₍"   U208D # SUBSCRIPT LEFT PARENTHESIS
<Multi_key> <underscore> <parenright> 	: "₎"   U208E # SUBSCRIPT RIGHT PARENTHESIS
