#most of the stuff from en_US.UTF-8.module

<Multi_key> <o> <c>              	: "©"   copyright # COPYRIGHT SIGN
<Multi_key> <o> <C>              	: "©"   copyright # COPYRIGHT SIGN
<Multi_key> <O> <c>              	: "©"   copyright # COPYRIGHT SIGN
<Multi_key> <O> <C>              	: "©"   copyright # COPYRIGHT SIGN
<Multi_key> <C> <o> 			: "©"   copyright # COPYRIGHT SIGN
<Multi_key> <C> <O> 			: "©"   copyright # COPYRIGHT SIGN

<Multi_key> <o> <r>              	: "®"   registered # REGISTERED SIGN
<Multi_key> <o> <R>              	: "®"   registered # REGISTERED SIGN
<Multi_key> <O> <r>              	: "®"   registered # REGISTERED SIGN
<Multi_key> <O> <R>              	: "®"   registered # REGISTERED SIGN
<Multi_key> <R> <o> 			: "®"   registered # REGISTERED SIGN
<Multi_key> <R> <O> 			: "®"   registered # REGISTERED SIGN

<Multi_key> <plus> <minus>       	: "±"   plusminus # PLUS-MINUS SIGN
<Multi_key> <minus> <plus> 		: "±"   plusminus # PLUS-MINUS SIGN
<Multi_key> <p> <exclam>         	: "¶"   paragraph # PILCROW SIGN
<Multi_key> <P> <exclam>         	: "¶"   paragraph # PILCROW SIGN

<Multi_key> <less> <3>                  : "♥"   U2665 # BLACK HEART SUIT

<Multi_key> <exclam> <exclam>    	: "¡"   exclamdown # INVERTED EXCLAMATION MARK
<Multi_key> <question> <question> 	: "¿"   questiondown # INVERTED QUESTION MARK

# Currencies
<Multi_key> <C> <E>              	: "₠"   U20a0 # EURO-CURRENCY SIGN
<Multi_key> <C> <slash>          	: "₡"   U20a1 # COLON SIGN
<Multi_key> <slash> <C>          	: "₡"   U20a1 # COLON SIGN
<Multi_key> <C> <r>              	: "₢"   U20a2 # CRUZEIRO SIGN
<Multi_key> <F> <r>              	: "₣"   U20a3 # FRENCH FRANC SIGN
<Multi_key> <L> <equal>          	: "₤"   U20a4 # LIRA SIGN
<Multi_key> <equal> <L>          	: "₤"   U20a4 # LIRA SIGN
<Multi_key> <m> <slash>          	: "₥"   U20a5 # MILL SIGN
<Multi_key> <slash> <m>          	: "₥"   U20a5 # MILL SIGN
<Multi_key> <N> <equal>          	: "₦"   U20a6 # NAIRA SIGN
<Multi_key> <equal> <N>          	: "₦"   U20a6 # NAIRA SIGN
<Multi_key> <P> <t>              	: "₧"   U20a7 # PESETA SIGN
<Multi_key> <R> <s>              	: "₨"   U20a8 # RUPEE SIGN
<Multi_key> <W> <equal>          	: "₩"   U20a9 # WON SIGN
<Multi_key> <equal> <W>          	: "₩"   U20a9 # WON SIGN
# "₪" U20aa NEW SHEQEL SIGN
<Multi_key> <d> <equal>          	: "₫"   U20ab # DONG SIGN
<Multi_key> <equal> <d>          	: "₫"   U20ab # DONG SIGN
<Multi_key> <C> <equal>          	: "€"   EuroSign # EURO SIGN
<Multi_key> <equal> <C>          	: "€"   EuroSign # EURO SIGN
<Multi_key> <c> <equal>          	: "€"   EuroSign # EURO SIGN
<Multi_key> <equal> <c>          	: "€"   EuroSign # EURO SIGN
<Multi_key> <E> <equal>          	: "€"   EuroSign # EURO SIGN
<Multi_key> <equal> <E>          	: "€"   EuroSign # EURO SIGN
<Multi_key> <e> <equal>          	: "€"   EuroSign # EURO SIGN
<Multi_key> <equal> <e>          	: "€"   EuroSign # EURO SIGN
<Multi_key> <Cyrillic_ES> <equal>	: "€"   EuroSign # EURO SIGN
<Multi_key> <equal> <Cyrillic_ES>	: "€"   EuroSign # EURO SIGN
<Multi_key> <Cyrillic_IE> <equal>	: "€"   EuroSign # EURO SIGN
<Multi_key> <equal> <Cyrillic_IE>	: "€"   EuroSign # EURO SIGN
<Multi_key> <P> <equal>          	: "₽"   U20bd # ROUBLE SIGN
<Multi_key> <p> <equal>          	: "₽"   U20bd # ROUBLE SIGN
<Multi_key> <equal> <P>          	: "₽"   U20bd # ROUBLE SIGN
<Multi_key> <equal> <p>          	: "₽"   U20bd # ROUBLE SIGN
<Multi_key> <Cyrillic_ZE> <equal>	: "₽"   U20bd # ROUBLE SIGN
<Multi_key> <Cyrillic_ze> <equal>	: "₽"   U20bd # ROUBLE SIGN
<Multi_key> <equal> <Cyrillic_ZE>	: "₽"   U20bd # ROUBLE SIGN
<Multi_key> <equal> <Cyrillic_ze>	: "₽"   U20bd # ROUBLE SIGN
# "₭" U20ad KIP SIGN
# "₮" U20ae TUGRIK SIGN
# "₯" U20af DRACHMA SIGN
# "₰" U20b0 GERMAN PENNY SIGN
# "₱" U20b1 PESO SIGN
# "₲" U20b2 GUARANI SIGN
# "₳" U20b3 AUSTRAL SIGN
# "₴" U20b4 HRYVNIA SIGN
# "₵" U20b5 CEDI SIGN
<Multi_key> <R> <equal>          	: "₹" U20b9 # INDIAN RUPEE SIGN
<Multi_key> <equal> <R>          	: "₹" U20b9 # INDIAN RUPEE SIGN
<Multi_key> <r> <equal>          	: "₹" U20b9 # INDIAN RUPEE SIGN
<Multi_key> <equal> <r>          	: "₹" U20b9 # INDIAN RUPEE SIGN

<Multi_key> <C> <bar>            	: "¢"   cent # CENT SIGN
<Multi_key> <bar> <C>			: "¢"   cent # CENT SIGN
<Multi_key> <c> <bar>            	: "¢"   cent # CENT SIGN
<Multi_key> <bar> <c>			: "¢"   cent # CENT SIGN
<Multi_key> <c> <slash>          	: "¢"   cent # CENT SIGN
<Multi_key> <slash> <c>          	: "¢"   cent # CENT SIGN
<Multi_key> <L> <minus>          	: "£"   sterling # POUND SIGN
<Multi_key> <minus> <L>          	: "£"   sterling # POUND SIGN
<Multi_key> <l> <minus> 		: "£"   sterling # POUND SIGN
<Multi_key> <minus> <l>          	: "£"   sterling # POUND SIGN
<Multi_key> <Y> <equal>          	: "¥"   yen # YEN SIGN
<Multi_key> <equal> <Y>          	: "¥"   yen # YEN SIGN
<Multi_key> <y> <equal> 		: "¥"   yen # YEN SIGN
<Multi_key> <equal> <y>          	: "¥"   yen # YEN SIGN
<Multi_key> <Y> <minus> 		: "¥"   yen # YEN SIGN
<Multi_key> <minus> <Y> 		: "¥"   yen # YEN SIGN
<Multi_key> <y> <minus> 		: "¥"   yen # YEN SIGN
<Multi_key> <minus> <y> 		: "¥"   yen # YEN SIGN

# Long S
<Multi_key> <f> <s>              	: "ſ"   U017f # LATIN SMALL LETTER LONG S
<Multi_key> <f> <S>              	: "ſ"   U017f # LATIN SMALL LETTER LONG S
<dead_abovedot> <Multi_key> <f> <s>	: "ẛ"   U1e9b # LATIN SMALL LETTER LONG S WITH DOT ABOVE
<Multi_key> <dead_abovedot> <f> <s>	: "ẛ"   U1e9b # LATIN SMALL LETTER LONG S WITH DOT ABOVE

# Dashes
<Multi_key> <minus> <minus> <period> 	: "–"   U2013 # EN DASH
<Multi_key> <minus> <minus> <minus> 	: "—"   U2014 # EM DASH

# Musical alterations
<Multi_key> <numbersign> <q>    	: "♩"   U2669 # QUARTER NOTE
<Multi_key> <numbersign> <e>    	: "♪"   U266a # EIGHTH NOTE
<Multi_key> <numbersign> <E>    	: "♫"   U266b # BEAMED EIGHTH NOTES
<Multi_key> <numbersign> <S>    	: "♬"   U266c # BEAMED SIXTEENTH NOTES
<Multi_key> <numbersign> <b>     	: "♭"   U266d # MUSIC FLAT SIGN
<Multi_key> <numbersign> <f>     	: "♮"   U266e # MUSIC NATURAL SIGN
<Multi_key> <numbersign> <numbersign> 	: "♯"   U266f # MUSIC SHARP SIGN

# Other symbols
<Multi_key> <s> <o>              	: "§"   section # SECTION SIGN
<Multi_key> <o> <s>              	: "§"   section # SECTION SIGN
<Multi_key> <S> <O> 			: "§"   section # SECTION SIGN
<Multi_key> <O> <S> 			: "§"   section # SECTION SIGN
<Multi_key> <s> <exclam> 		: "§"   section # SECTION SIGN
<Multi_key> <S> <exclam> 		: "§"   section # SECTION SIGN
<Multi_key> <Cyrillic_pe> <Cyrillic_a>	: "§"   section # SECTION SIGN

<Multi_key> <o> <x>              	: "¤"   currency # CURRENCY SIGN
<Multi_key> <x> <o>              	: "¤"   currency # CURRENCY SIGN
<Multi_key> <o> <X> 			: "¤"   currency # CURRENCY SIGN
<Multi_key> <X> <o> 			: "¤"   currency # CURRENCY SIGN
<Multi_key> <O> <X> 			: "¤"   currency # CURRENCY SIGN
<Multi_key> <X> <O> 			: "¤"   currency # CURRENCY SIGN
<Multi_key> <O> <x> 			: "¤"   currency # CURRENCY SIGN
<Multi_key> <x> <O> 			: "¤"   currency # CURRENCY SIGN

<Multi_key> <P> <P>              	: "¶"   paragraph # PILCROW SIGN

<Multi_key> <N> <o>			: "№" numerosign # NUMERO SIGN
<Multi_key> <N> <O>			: "№" numerosign # NUMERO SIGN
<Multi_key> <Cyrillic_EN> <Cyrillic_o>	: "№" numerosign # NUMERO SIGN
<Multi_key> <Cyrillic_EN> <Cyrillic_O>	: "№" numerosign # NUMERO SIGN

<Multi_key> <question> <exclam>         : "⸘"   U2E18 # INVERTED INTERROBANG
<Multi_key> <exclam> <question>         : "‽"   U203D # INTERROBANG

<Multi_key> <C> <C> <C> <P>             : "☭"   U262D # HAMMER AND SICKLE
<Multi_key> <O> <A>                     : "Ⓐ"   U24B6 # CIRCLED LATIN CAPITAL LETTER A


<Multi_key> <colon> <parenright>        : "☺"   U263A # WHITE SMILING FACE
<Multi_key> <colon> <parenleft>         : "☹"   U2639 # WHITE FROWNING FACE
<Multi_key> <backslash> <o> <slash>		: "🙌"		# PERSON RAISING BOTH HANDS IN CELEBRATION

<Multi_key> <p> <o> <o>                 : "💩"  U1F4A9 # PILE OF POO

<Multi_key> <F> <U>                     : "🖕"  U1F595 # REVERSED HAND WITH MIDDLE FINGER EXTENDED
<Multi_key> <L> <L> <A> <P>             : "🖖"  U1F596 # RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS

<Multi_key> <s> <s>              	: "ß"   ssharp # LATIN SMALL LETTER SHARP S
<Multi_key> <S> <S>              	: "ẞ"   U1e9e # LATIN CAPITAL LETTER SHARP S
<Multi_key> <o> <e>              	: "œ"   oe # LATIN SMALL LIGATURE OE
<Multi_key> <O> <E>              	: "Œ"   OE # LATIN CAPITAL LIGATURE OE
<Multi_key> <a> <e>              	: "æ"   ae # LATIN SMALL LETTER AE
<Multi_key> <A> <E>              	: "Æ"   AE # LATIN CAPITAL LETTER AE
<Multi_key> <f> <f>              	: "ﬀ"   Ufb00 # LATIN SMALL LIGATURE FF
<Multi_key> <f> <i>              	: "ﬁ"   Ufb01 # LATIN SMALL LIGATURE FI
<Multi_key> <f> <l>              	: "ﬂ"   Ufb02 # LATIN SMALL LIGATURE FL
<Multi_key> <F> <i>              	: "ﬃ"   Ufb03 # LATIN SMALL LIGATURE FFI
<Multi_key> <F> <l>              	: "ﬄ"   Ufb04 # LATIN SMALL LIGATURE FFL
<Multi_key> <I> <J>              	: "Ĳ"   U0132 # LATIN CAPITAL LIGATURE IJ
<Multi_key> <I> <j>              	: "Ĳ"   U0132 # LATIN CAPITAL LIGATURE IJ
<Multi_key> <i> <j>              	: "ĳ"   U0133 # LATIN SMALL LIGATURE IJ

<Multi_key> <1> <4>              	: "¼"   onequarter # VULGAR FRACTION ONE QUARTER
<Multi_key> <1> <2>              	: "½"   onehalf # VULGAR FRACTION ONE HALF
<Multi_key> <3> <4>              	: "¾"   threequarters # VULGAR FRACTION THREE QUARTERS
<Multi_key> <1> <7>			: "⅐"	U2150 # VULGAR FRACTION ONE SEVENTH
<Multi_key> <1> <9>			: "⅑"	U2151 # VULGAR FRACTION ONE NINTH
<Multi_key> <1> <1> <0>			: "⅒"	U2152 # VULGAR FRACTION ONE TENTH
<Multi_key> <1> <3>			: "⅓"	U2153 # VULGAR FRACTION ONE THIRD
<Multi_key> <2> <3>			: "⅔"	U2154 # VULGAR FRACTION TWO THIRDS
<Multi_key> <1> <5>			: "⅕"	U2155 # VULGAR FRACTION ONE FIFTH
<Multi_key> <2> <5>			: "⅖"	U2156 # VULGAR FRACTION TWO FIFTHS
<Multi_key> <3> <5>			: "⅗"	U2157 # VULGAR FRACTION THREE FIFTHS
<Multi_key> <4> <5>			: "⅘"	U2158 # VULGAR FRACTION FOUR FIFTHS
<Multi_key> <1> <6>			: "⅙"	U2159 # VULGAR FRACTION ONE SIXTH
<Multi_key> <5> <6>			: "⅚"	U215A # VULGAR FRACTION FIVE SIXTHS
<Multi_key> <1> <8>			: "⅛"	U215B # VULGAR FRACTION ONE EIGHTH
<Multi_key> <3> <8>			: "⅜"	U215C # VULGAR FRACTION THREE EIGHTHS
<Multi_key> <5> <8>			: "⅝"	U215D # VULGAR FRACTION FIVE EIGHTHS
<Multi_key> <7> <8>			: "⅞"	U215E # VULGAR FRACTION SEVEN EIGHTHS
<Multi_key> <0> <3>			: "↉"	U2189 # VULGAR FRACTION ZERO THIRDS
<Multi_Key> <colon> <minus>      	: "÷"   division # DIVISION SIGN
<Multi_Key> <minus> <colon>      	: "÷"   division # DIVISION SIGN
<dead_circumflex> <0>            	: "⁰"   U2070 # SUPERSCRIPT ZERO
<Multi_key> <asciicircum> <0>    	: "⁰"   U2070 # SUPERSCRIPT ZERO
<dead_circumflex> <KP_0>         	: "⁰"   U2070 # SUPERSCRIPT ZERO
<Multi_key> <asciicircum> <KP_0> 	: "⁰"   U2070 # SUPERSCRIPT ZERO
<dead_circumflex> <Multi_key> <underscore> <i> 	: "ⁱ"   U2071 # SUPERSCRIPT LATIN SMALL LETTER I
<Multi_key> <asciicircum> <underscore> <i> 	: "ⁱ"   U2071 # SUPERSCRIPT LATIN SMALL LETTER I
<dead_circumflex> <2>            	: "²"   twosuperior # SUPERSCRIPT TWO
<Multi_key> <asciicircum> <2>    	: "²"   twosuperior # SUPERSCRIPT TWO
<Multi_key> <2> <asciicircum> 		: "²"   twosuperior # SUPERSCRIPT TWO
<dead_circumflex> <KP_2>         	: "²"   twosuperior # SUPERSCRIPT TWO
<Multi_key> <asciicircum> <KP_2> 	: "²"   twosuperior # SUPERSCRIPT TWO
<dead_circumflex> <3>            	: "³"   threesuperior # SUPERSCRIPT THREE
<Multi_key> <asciicircum> <3>    	: "³"   threesuperior # SUPERSCRIPT THREE
<Multi_key> <3> <asciicircum> 		: "³"   threesuperior # SUPERSCRIPT THREE
<dead_circumflex> <KP_3>         	: "³"   threesuperior # SUPERSCRIPT THREE
<Multi_key> <asciicircum> <KP_3> 	: "³"   threesuperior # SUPERSCRIPT THREE
<Multi_key> <m> <u>              	: "µ"   mu # MICRO SIGN
<dead_circumflex> <1>            	: "¹"   onesuperior # SUPERSCRIPT ONE
<Multi_key> <asciicircum> <1>    	: "¹"   onesuperior # SUPERSCRIPT ONE
<Multi_key> <1> <asciicircum> 		: "¹"   onesuperior # SUPERSCRIPT ONE
<dead_circumflex> <KP_1>         	: "¹"   onesuperior # SUPERSCRIPT ONE
<Multi_key> <asciicircum> <KP_1> 	: "¹"   onesuperior # SUPERSCRIPT ONE
<dead_circumflex> <4>            	: "⁴"   U2074 # SUPERSCRIPT FOUR
<Multi_key> <asciicircum> <4>    	: "⁴"   U2074 # SUPERSCRIPT FOUR
<dead_circumflex> <KP_4>         	: "⁴"   U2074 # SUPERSCRIPT FOUR
<Multi_key> <asciicircum> <KP_4> 	: "⁴"   U2074 # SUPERSCRIPT FOUR
<dead_circumflex> <5>            	: "⁵"   U2075 # SUPERSCRIPT FIVE
<Multi_key> <asciicircum> <5>    	: "⁵"   U2075 # SUPERSCRIPT FIVE
<dead_circumflex> <KP_5>         	: "⁵"   U2075 # SUPERSCRIPT FIVE
<Multi_key> <asciicircum> <KP_5> 	: "⁵"   U2075 # SUPERSCRIPT FIVE
<dead_circumflex> <6>            	: "⁶"   U2076 # SUPERSCRIPT SIX
<Multi_key> <asciicircum> <6>    	: "⁶"   U2076 # SUPERSCRIPT SIX
<dead_circumflex> <KP_6>         	: "⁶"   U2076 # SUPERSCRIPT SIX
<Multi_key> <asciicircum> <KP_6> 	: "⁶"   U2076 # SUPERSCRIPT SIX
<dead_circumflex> <7>            	: "⁷"   U2077 # SUPERSCRIPT SEVEN
<Multi_key> <asciicircum> <7>    	: "⁷"   U2077 # SUPERSCRIPT SEVEN
<dead_circumflex> <KP_7>         	: "⁷"   U2077 # SUPERSCRIPT SEVEN
<Multi_key> <asciicircum> <KP_7> 	: "⁷"   U2077 # SUPERSCRIPT SEVEN
<dead_circumflex> <8>            	: "⁸"   U2078 # SUPERSCRIPT EIGHT
<Multi_key> <asciicircum> <8>    	: "⁸"   U2078 # SUPERSCRIPT EIGHT
<dead_circumflex> <KP_8>         	: "⁸"   U2078 # SUPERSCRIPT EIGHT
<Multi_key> <asciicircum> <KP_8> 	: "⁸"   U2078 # SUPERSCRIPT EIGHT
<dead_circumflex> <9>            	: "⁹"   U2079 # SUPERSCRIPT NINE
<Multi_key> <asciicircum> <9>    	: "⁹"   U2079 # SUPERSCRIPT NINE
<dead_circumflex> <KP_9>         	: "⁹"   U2079 # SUPERSCRIPT NINE
<Multi_key> <asciicircum> <KP_9> 	: "⁹"   U2079 # SUPERSCRIPT NINE
<dead_circumflex> <plus>         	: "⁺"   U207A # SUPERSCRIPT PLUS SIGN
<Multi_key> <asciicircum> <plus> 	: "⁺"   U207A # SUPERSCRIPT PLUS SIGN
<dead_circumflex> <KP_Add>       	: "⁺"   U207A # SUPERSCRIPT PLUS SIGN
<Multi_key> <asciicircum> <KP_Add> 	: "⁺"   U207A # SUPERSCRIPT PLUS SIGN
<dead_circumflex> <minus> 		: "⁻"   U207B # SUPERSCRIPT MINUS
<dead_circumflex> <equal>        	: "⁼"   U207C # SUPERSCRIPT EQUALS SIGN
<Multi_key> <asciicircum> <equal> 	: "⁼"   U207C # SUPERSCRIPT EQUALS SIGN
<dead_circumflex> <parenleft>    	: "⁽"   U207D # SUPERSCRIPT LEFT PARENTHESIS
<Multi_key> <asciicircum> <parenleft> 	: "⁽"   U207D # SUPERSCRIPT LEFT PARENTHESIS
<dead_circumflex> <parenright>   	: "⁾"   U207E # SUPERSCRIPT RIGHT PARENTHESIS
<Multi_key> <asciicircum> <parenright> 	: "⁾"   U207E # SUPERSCRIPT RIGHT PARENTHESIS
<dead_circumflex> <Multi_key> <underscore> <n> 	: "ⁿ"   U207F # SUPERSCRIPT LATIN SMALL LETTER N
<Multi_key> <asciicircum> <underscore> <n> 	: "ⁿ"   U207F # SUPERSCRIPT LATIN SMALL LETTER N
<Multi_key> <underscore> <0>     	: "₀"   U2080 # SUBSCRIPT ZERO
<Multi_key> <underscore> <KP_0>  	: "₀"   U2080 # SUBSCRIPT ZERO
<Multi_key> <underscore> <1>     	: "₁"   U2081 # SUBSCRIPT ONE
<Multi_key> <underscore> <KP_1>  	: "₁"   U2081 # SUBSCRIPT ONE
<Multi_key> <underscore> <2>     	: "₂"   U2082 # SUBSCRIPT TWO
<Multi_key> <underscore> <KP_2>  	: "₂"   U2082 # SUBSCRIPT TWO
<Multi_key> <underscore> <3>     	: "₃"   U2083 # SUBSCRIPT THREE
<Multi_key> <underscore> <KP_3>  	: "₃"   U2083 # SUBSCRIPT THREE
<Multi_key> <underscore> <4>     	: "₄"   U2084 # SUBSCRIPT FOUR
<Multi_key> <underscore> <KP_4>  	: "₄"   U2084 # SUBSCRIPT FOUR
<Multi_key> <underscore> <5>     	: "₅"   U2085 # SUBSCRIPT FIVE
<Multi_key> <underscore> <KP_5>  	: "₅"   U2085 # SUBSCRIPT FIVE
<Multi_key> <underscore> <6>     	: "₆"   U2086 # SUBSCRIPT SIX
<Multi_key> <underscore> <KP_6>  	: "₆"   U2086 # SUBSCRIPT SIX
<Multi_key> <underscore> <7>     	: "₇"   U2087 # SUBSCRIPT SEVEN
<Multi_key> <underscore> <KP_7>  	: "₇"   U2087 # SUBSCRIPT SEVEN
<Multi_key> <underscore> <8>     	: "₈"   U2088 # SUBSCRIPT EIGHT
<Multi_key> <underscore> <KP_8>  	: "₈"   U2088 # SUBSCRIPT EIGHT
<Multi_key> <underscore> <9>     	: "₉"   U2089 # SUBSCRIPT NINE
<Multi_key> <underscore> <KP_9>  	: "₉"   U2089 # SUBSCRIPT NINE
<Multi_key> <underscore> <plus>  	: "₊"   U208A # SUBSCRIPT PLUS SIGN
<Multi_key> <underscore> <KP_Add> 	: "₊"   U208A # SUBSCRIPT PLUS SIGN
<Multi_key> <underscore> <equal> 	: "₌"   U208C # SUBSCRIPT EQUALS SIGN
<Multi_key> <underscore> <parenleft> 	: "₍"   U208D # SUBSCRIPT LEFT PARENTHESIS
<Multi_key> <underscore> <parenright> 	: "₎"   U208E # SUBSCRIPT RIGHT PARENTHESIS


<dead_circumflex> <Multi_key> <S> <M> 	: "℠"   U2120 # SERVICE MARK
<Multi_key> <S> <M>		 	: "℠"   U2120 # SERVICE MARK
<dead_circumflex> <Multi_key> <s> <M> 	: "℠"   U2120 # SERVICE MARK
<Multi_key> <s> <M>		 	: "℠"   U2120 # SERVICE MARK
<dead_circumflex> <Multi_key> <S> <m> 	: "℠"   U2120 # SERVICE MARK
<Multi_key> <S> <m>		 	: "℠"   U2120 # SERVICE MARK
<dead_circumflex> <Multi_key> <s> <m> 	: "℠"   U2120 # SERVICE MARK
<Multi_key> <s> <m>		 	: "℠"   U2120 # SERVICE MARK
<dead_circumflex> <Multi_key> <T> <M> 	: "™"   U2122 # TRADE MARK SIGN
<Multi_key> <T> <M>		 	: "™"   U2122 # TRADE MARK SIGN
<dead_circumflex> <Multi_key> <t> <M> 	: "™"   U2122 # TRADE MARK SIGN
<Multi_key> <t> <M>		 	: "™"   U2122 # TRADE MARK SIGN
<dead_circumflex> <Multi_key> <T> <m> 	: "™"   U2122 # TRADE MARK SIGN
<Multi_key> <T> <m>		 	: "™"   U2122 # TRADE MARK SIGN
<dead_circumflex> <Multi_key> <t> <m> 	: "™"   U2122 # TRADE MARK SIGN