/***********************************************************************/
/******************* This file is generated by *************************/
/******************* the Compose Generator *****************************/
/***********************************************************************/

#include "Compose.gen.h"

//generated compose tree
const Node Compose::root[] PROGMEM = {
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) OBJ_3084155333744}},
	{{0, 0, L2, KEY_TILDE}, {(uint16_t) OBJ_3084155333664}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155333584}},
	{{0, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155333984}},
	{{0, 0, L1, KEY_EQUAL}, {(uint16_t) OBJ_3084155334304}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) OBJ_3084155334544}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) OBJ_3084155396320}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) OBJ_3084155396240}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) OBJ_3084155396560}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155396720}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) OBJ_3084155396880}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) OBJ_3084155397280}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155397440}},
	{{0, 0, L4, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155397760}},
	{{0, 0, L5, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155397680}},
	{{0, 0, L5, KEY_EQUAL}, {(uint16_t) OBJ_3084155397600}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) OBJ_3084155398160}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) OBJ_3084155398400}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) OBJ_3084155398720}},
};

const Node Compose::OBJ_3084155333744[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2c6}},
	{{1, 1, L1, KEY_TILDE}, {0x302}},
};

const Node Compose::OBJ_3084155333664[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2c7}},
	{{0, 1, L2, KEY_TILDE}, {0x30c}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) OBJ_3084155431888}},
	{{0, 1, L1, KEY_0}, {0x2080}},
	{{0, 1, L1, KEYPAD_0}, {0x2080}},
	{{0, 1, L1, KEY_1}, {0x2081}},
	{{0, 1, L1, KEYPAD_1}, {0x2081}},
	{{0, 1, L1, KEY_2}, {0x2082}},
	{{0, 1, L1, KEYPAD_2}, {0x2082}},
	{{0, 1, L1, KEY_3}, {0x2083}},
	{{0, 1, L1, KEYPAD_3}, {0x2083}},
	{{0, 1, L1, KEY_4}, {0x2084}},
	{{0, 1, L1, KEYPAD_4}, {0x2084}},
	{{0, 1, L1, KEY_5}, {0x2085}},
	{{0, 1, L1, KEYPAD_5}, {0x2085}},
	{{0, 1, L1, KEY_6}, {0x2086}},
	{{0, 1, L1, KEYPAD_6}, {0x2086}},
	{{0, 1, L1, KEY_7}, {0x2087}},
	{{0, 1, L1, KEYPAD_7}, {0x2087}},
	{{0, 1, L1, KEY_8}, {0x2088}},
	{{0, 1, L1, KEYPAD_8}, {0x2088}},
	{{0, 1, L1, KEY_9}, {0x2089}},
	{{1, 1, L1, KEYPAD_9}, {0x2089}},
};

const Node Compose::OBJ_3084155431888[] PROGMEM = {
	{{0, 0, L2, KEY_SEMICOLON}, {(uint16_t) OBJ_3084155432128}},
	{{1, 0, L1, KEY_SEMICOLON}, {(uint16_t) OBJ_3084155432288}},
};

const Node Compose::OBJ_3084155432128[] PROGMEM = {
	{{0, 1, L2, KEY_B}, {0x1c4}},
	{{1, 1, L1, KEY_B}, {0x1c5}},
};

const Node Compose::OBJ_3084155432288[] PROGMEM = {
	{{1, 1, L1, KEY_B}, {0x1c6}},
};

const Node Compose::OBJ_3084155333584[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2d8}},
	{{0, 1, L6, KEY_RIGHT_BRACE}, {0x306}},
	{{0, 1, L2, KEY_U}, {0x1e2a}},
	{{0, 1, L1, KEY_U}, {0x1e2b}},
	{{1, 1, L5, KEY_5}, {0x263f}},
};

const Node Compose::OBJ_3084155333984[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xb4}},
	{{0, 1, L1, KEY_RIGHT_BRACE}, {0x301}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155159632}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) OBJ_3084155429888}},
};

const Node Compose::OBJ_3084155159632[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1fe}},
	{{1, 1, L1, KEY_G}, {0x1ff}},
};

const Node Compose::OBJ_3084155429888[] PROGMEM = {
	{{0, 0, L2, KEY_D}, {(uint16_t) OBJ_3084155430048}},
	{{1, 0, L1, KEY_D}, {(uint16_t) OBJ_3084155430128}},
};

const Node Compose::OBJ_3084155430048[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x1fc}},
};

const Node Compose::OBJ_3084155430128[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1fd}},
};

const Node Compose::OBJ_3084155334304[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x60}},
	{{1, 1, L1, KEY_EQUAL}, {0x300}},
};

const Node Compose::OBJ_3084155334544[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xb8}},
	{{0, 1, L2, KEY_EQUAL}, {0x327}},
	{{0, 1, L2, KEY_D}, {0x104}},
	{{0, 1, L1, KEY_D}, {0x105}},
	{{0, 1, L2, KEY_F}, {0x118}},
	{{0, 1, L1, KEY_F}, {0x119}},
	{{0, 1, L2, KEY_S}, {0x12e}},
	{{0, 1, L1, KEY_S}, {0x12f}},
	{{0, 1, L2, KEY_A}, {0x172}},
	{{0, 1, L1, KEY_A}, {0x173}},
	{{0, 1, L2, KEY_G}, {0x1ea}},
	{{1, 1, L1, KEY_G}, {0x1eb}},
};

const Node Compose::OBJ_3084155396320[] PROGMEM = {
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) OBJ_3084155396400}},
	{{0, 0, L4, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155398000}},
	{{0, 1, L5, KEY_SPACE}, {0x21bb}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) OBJ_3084155399360}},
	{{0, 1, L1, KEY_SPACE}, {0x21bb}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2025}},
	{{0, 1, L3, KEY_Q}, {0x22ee}},
	{{0, 1, L5, KEY_5}, {0x2641}},
	{{0, 1, L3, KEY_R}, {0x2423}},
	{{1, 1, L3, KEYPAD_3}, {0x21cb}},
};

const Node Compose::OBJ_3084155396400[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2db}},
	{{0, 1, L2, KEY_EQUAL}, {0x328}},
	{{0, 1, L1, KEY_SPACE}, {0x2db}},
	{{0, 1, L2, KEY_F}, {0x228}},
	{{1, 1, L1, KEY_F}, {0x229}},
};

const Node Compose::OBJ_3084155398000[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2f5}},
	{{0, 1, L4, KEY_RIGHT_BRACE}, {0x30f}},
	{{0, 1, L2, KEY_D}, {0x200}},
	{{0, 1, L1, KEY_D}, {0x201}},
	{{0, 1, L2, KEY_F}, {0x204}},
	{{0, 1, L1, KEY_F}, {0x205}},
	{{0, 1, L2, KEY_S}, {0x208}},
	{{0, 1, L1, KEY_S}, {0x209}},
	{{0, 1, L2, KEY_G}, {0x20c}},
	{{0, 1, L1, KEY_G}, {0x20d}},
	{{0, 1, L2, KEY_K}, {0x210}},
	{{0, 1, L1, KEY_K}, {0x211}},
	{{0, 1, L2, KEY_A}, {0x214}},
	{{1, 1, L1, KEY_A}, {0x215}},
};

const Node Compose::OBJ_3084155399360[] PROGMEM = {
	{{0, 1, L6, KEY_RIGHT_BRACE}, {0x311}},
	{{0, 1, L2, KEY_D}, {0x202}},
	{{0, 1, L1, KEY_D}, {0x203}},
	{{0, 1, L2, KEY_F}, {0x206}},
	{{0, 1, L1, KEY_F}, {0x207}},
	{{0, 1, L2, KEY_S}, {0x20a}},
	{{0, 1, L1, KEY_S}, {0x20b}},
	{{0, 1, L2, KEY_G}, {0x20e}},
	{{0, 1, L1, KEY_G}, {0x20f}},
	{{0, 1, L2, KEY_K}, {0x212}},
	{{0, 1, L1, KEY_K}, {0x213}},
	{{0, 1, L2, KEY_A}, {0x216}},
	{{1, 1, L1, KEY_A}, {0x217}},
};

const Node Compose::OBJ_3084155396240[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2d9}},
	{{0, 1, L4, KEY_TILDE}, {0x307}},
	{{0, 1, L2, KEY_E}, {0x13f}},
	{{0, 1, L1, KEY_E}, {0x140}},
	{{1, 1, L1, KEY_SLASH}, {0x237}},
};

const Node Compose::OBJ_3084155396560[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2da}},
	{{1, 1, L3, KEY_EQUAL}, {0x30a}},
};

const Node Compose::OBJ_3084155396720[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2dc}},
	{{0, 1, L2, KEY_RIGHT_BRACE}, {0x303}},
	{{0, 1, L2, KEY_E}, {0x2c62}},
	{{1, 1, L1, KEY_E}, {0x26b}},
};

const Node Compose::OBJ_3084155396880[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xaf}},
	{{0, 1, L6, KEY_EQUAL}, {0x304}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) OBJ_3084155410768}},
	{{0, 1, L2, KEY_N}, {0x1e06}},
	{{0, 1, L1, KEY_N}, {0x1e07}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e0e}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e0f}},
	{{0, 1, L2, KEY_Y}, {0x1e34}},
	{{0, 1, L1, KEY_Y}, {0x1e35}},
	{{0, 1, L2, KEY_E}, {0x1e3a}},
	{{0, 1, L1, KEY_E}, {0x1e3b}},
	{{0, 1, L2, KEY_J}, {0x1e48}},
	{{0, 1, L1, KEY_J}, {0x1e49}},
	{{0, 1, L2, KEY_K}, {0x1e5e}},
	{{0, 1, L1, KEY_K}, {0x1e5f}},
	{{0, 1, L2, KEY_L}, {0x1e6e}},
	{{0, 1, L1, KEY_L}, {0x1e6f}},
	{{0, 1, L2, KEY_B}, {0x1e94}},
	{{0, 1, L1, KEY_B}, {0x1e95}},
	{{0, 1, L1, KEY_U}, {0x1e96}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) OBJ_3084155429568}},
};

const Node Compose::OBJ_3084155410768[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ec}},
	{{1, 1, L1, KEY_G}, {0x1ed}},
};

const Node Compose::OBJ_3084155429568[] PROGMEM = {
	{{0, 0, L2, KEY_D}, {(uint16_t) OBJ_3084155429808}},
	{{1, 0, L1, KEY_D}, {(uint16_t) OBJ_3084155429648}},
};

const Node Compose::OBJ_3084155429808[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x1e2}},
};

const Node Compose::OBJ_3084155429648[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1e3}},
};

const Node Compose::OBJ_3084155397280[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xa8}},
	{{1, 1, L4, KEY_EQUAL}, {0x308}},
};

const Node Compose::OBJ_3084155397440[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2f}},
	{{0, 1, L3, KEY_RIGHT_BRACE}, {0x337}},
	{{0, 1, L1, KEY_SPACE}, {0x2010}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x110}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x111}},
	{{0, 1, L2, KEY_U}, {0x126}},
	{{0, 1, L1, KEY_U}, {0x127}},
	{{0, 1, L2, KEY_E}, {0x141}},
	{{0, 1, L1, KEY_E}, {0x142}},
	{{0, 1, L2, KEY_G}, {0xd8}},
	{{0, 1, L1, KEY_G}, {0xf8}},
	{{0, 1, L5, KEY_4}, {0x26a6}},
	{{0, 1, L5, KEY_6}, {0x26a7}},
	{{0, 1, L3, KEY_S}, {0x2718}},
	{{0, 1, L1, KEYPAD_DIVIDE}, {0x2718}},
	{{0, 1, L3, KEY_A}, {0x2718}},
	{{1, 1, L4, KEY_6}, {0x20a4}},
};

const Node Compose::OBJ_3084155397760[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2dd}},
	{{0, 1, L4, KEY_RIGHT_BRACE}, {0x30b}},
	{{1, 1, L1, KEY_SPACE}, {0x2dd}},
};

const Node Compose::OBJ_3084155397680[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x1fbf}},
	{{0, 1, L5, KEY_RIGHT_BRACE}, {0x313}},
	{{1, 1, L1, KEY_SPACE}, {0x1fbf}},
};

const Node Compose::OBJ_3084155397600[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x1ffe}},
	{{0, 1, L5, KEY_EQUAL}, {0x314}},
	{{1, 1, L1, KEY_SPACE}, {0x1ffe}},
};

const Node Compose::OBJ_3084155398160[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2de}},
	{{0, 1, L5, KEY_TILDE}, {0x2de}},
	{{0, 1, L1, KEY_SPACE}, {0x2de}},
	{{0, 1, L3, KEY_S}, {0x2714}},
	{{0, 1, L1, KEYPAD_DIVIDE}, {0x2714}},
	{{1, 1, L3, KEY_A}, {0x2714}},
};

const Node Compose::OBJ_3084155398400[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2e}},
	{{0, 1, L6, KEY_TILDE}, {0x323}},
	{{1, 1, L1, KEY_SPACE}, {0x2e}},
};

const Node Compose::OBJ_3084155398720[] PROGMEM = {
	{{0, 0, L1, KEY_G}, {(uint16_t) OBJ_3084155398800}},
	{{0, 0, L3, KEY_Q}, {(uint16_t) OBJ_3084155398560}},
	{{0, 0, L3, KEY_W}, {(uint16_t) OBJ_3084155408928}},
	{{0, 0, L3, KEY_0}, {(uint16_t) OBJ_3084155408608}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) OBJ_3084155160512}},
	{{0, 0, L2, KEY_H}, {(uint16_t) OBJ_3084155285232}},
	{{0, 0, L1, KEY_H}, {(uint16_t) OBJ_3084155285072}},
	{{0, 0, L2, KEY_L}, {(uint16_t) OBJ_3084155284992}},
	{{0, 0, L1, KEY_L}, {(uint16_t) OBJ_3084155284592}},
	{{0, 0, L2, KEY_F}, {(uint16_t) OBJ_3084155411728}},
	{{0, 0, L2, KEY_E}, {(uint16_t) OBJ_3084155411888}},
	{{0, 0, L1, KEY_E}, {(uint16_t) OBJ_3084155411968}},
	{{0, 0, L1, KEY_S}, {(uint16_t) OBJ_3084155429248}},
	{{0, 0, L2, KEY_S}, {(uint16_t) OBJ_3084155429168}},
	{{0, 0, L1, KEY_B}, {(uint16_t) OBJ_3084155430288}},
	{{0, 0, L1, KEY_O}, {(uint16_t) OBJ_3084155430608}},
	{{0, 0, L2, KEY_O}, {(uint16_t) OBJ_3084155430928}},
	{{0, 0, L3, KEY_LEFT_BRACE}, {(uint16_t) OBJ_3084155431168}},
	{{0, 0, L2, KEY_SEMICOLON}, {(uint16_t) OBJ_3084155431568}},
	{{0, 0, L1, KEY_SEMICOLON}, {(uint16_t) OBJ_3084155431808}},
	{{0, 0, L2, KEY_J}, {(uint16_t) OBJ_3084155432688}},
	{{0, 0, L1, KEY_J}, {(uint16_t) OBJ_3084155453504}},
	{{0, 0, L1, KEY_2}, {(uint16_t) OBJ_3084155455344}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) OBJ_3084155455424}},
	{{0, 0, L1, KEYPAD_2}, {(uint16_t) OBJ_3084155455504}},
	{{0, 0, L3, KEY_H}, {(uint16_t) OBJ_3084155455904}},
	{{0, 0, L1, KEY_1}, {(uint16_t) OBJ_3084155456384}},
	{{0, 0, L1, KEYPAD_1}, {(uint16_t) OBJ_3084155456704}},
	{{0, 0, L2, KEYPAD_9}, {(uint16_t) OBJ_3084155466032}},
	{{0, 0, L5, KEY_SPACE}, {(uint16_t) OBJ_3084155466512}},
	{{0, 0, L1, KEY_7}, {(uint16_t) OBJ_3084155466752}},
	{{0, 0, L1, KEYPAD_7}, {(uint16_t) OBJ_3084155466672}},
	{{0, 0, L2, KEY_K}, {(uint16_t) OBJ_3084155467152}},
	{{0, 0, L1, KEY_K}, {(uint16_t) OBJ_3084155469152}},
	{{0, 0, L1, KEY_3}, {(uint16_t) OBJ_3084155484016}},
	{{0, 0, L1, KEY_4}, {(uint16_t) OBJ_3084155484096}},
	{{0, 0, L1, KEY_5}, {(uint16_t) OBJ_3084155484416}},
	{{0, 0, L1, KEYPAD_3}, {(uint16_t) OBJ_3084155485376}},
	{{0, 0, L1, KEYPAD_4}, {(uint16_t) OBJ_3084155485456}},
	{{0, 0, L1, KEYPAD_5}, {(uint16_t) OBJ_3084155485776}},
	{{0, 0, L3, KEY_SEMICOLON}, {(uint16_t) OBJ_3084155511648}},
	{{0, 0, L1, KEY_R}, {(uint16_t) OBJ_3084155511888}},
	{{0, 0, L5, KEY_5}, {(uint16_t) OBJ_3084155511968}},
	{{0, 0, L5, KEY_4}, {(uint16_t) OBJ_3084155512208}},
	{{0, 1, L1, KEY_TAB}, {0x266b}},
	{{0, 1, L3, KEY_TAB}, {0x266b}},
	{{0, 0, L3, KEY_U}, {(uint16_t) OBJ_3084155513568}},
	{{0, 0, L2, KEY_R}, {(uint16_t) OBJ_3084155513808}},
	{{0, 0, L3, KEY_E}, {(uint16_t) OBJ_3084155513888}},
	{{0, 0, L6, KEYPAD_0}, {(uint16_t) OBJ_3084155514128}},
	{{0, 0, L2, KEYPAD_7}, {(uint16_t) OBJ_3084155514288}},
	{{0, 0, L2, KEYPAD_8}, {(uint16_t) OBJ_3084155514608}},
	{{0, 0, L6, KEY_SEMICOLON}, {(uint16_t) OBJ_3084155514688}},
	{{0, 0, L2, KEYPAD_0}, {(uint16_t) OBJ_3084155527472}},
	{{0, 0, L1, KEY_V}, {(uint16_t) OBJ_3084155527552}},
	{{0, 0, L1, KEY_PERIOD}, {(uint16_t) OBJ_3084155528592}},
	{{1, 0, L2, KEY_PERIOD}, {(uint16_t) OBJ_3084155528832}},
};

const Node Compose::OBJ_3084155398800[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x25cc}},
	{{1, 0, L1, KEY_V}, {(uint16_t) OBJ_3084155528032}},
};

const Node Compose::OBJ_3084155528032[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0x2325}},
};

const Node Compose::OBJ_3084155398560[] PROGMEM = {
	{{0, 1, L1, KEY_G}, {0x25cc}},
	{{1, 1, L3, KEY_C}, {0x22ee}},
};

const Node Compose::OBJ_3084155408928[] PROGMEM = {
	{{1, 1, L3, KEY_W}, {0x332}},
};

const Node Compose::OBJ_3084155408608[] PROGMEM = {
	{{1, 1, L3, KEY_0}, {0x2bc}},
};

const Node Compose::OBJ_3084155160512[] PROGMEM = {
	{{0, 1, L2, KEY_U}, {0x126}},
	{{0, 1, L1, KEY_U}, {0x127}},
	{{1, 1, L4, KEY_6}, {0x20a4}},
};

const Node Compose::OBJ_3084155285232[] PROGMEM = {
	{{1, 1, L1, KEY_COMMA}, {0x218}},
};

const Node Compose::OBJ_3084155285072[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x219}},
	{{1, 1, L1, KEY_L}, {0xfb06}},
};

const Node Compose::OBJ_3084155284992[] PROGMEM = {
	{{1, 1, L1, KEY_COMMA}, {0x21a}},
};

const Node Compose::OBJ_3084155284592[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x21b}},
	{{1, 1, L1, KEY_M}, {0x2122}},
};

const Node Compose::OBJ_3084155411728[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x18f}},
};

const Node Compose::OBJ_3084155411888[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x13f}},
	{{0, 1, L2, KEY_SLASH}, {0x1c7}},
	{{1, 1, L1, KEY_SLASH}, {0x1c8}},
};

const Node Compose::OBJ_3084155411968[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x140}},
	{{1, 1, L1, KEY_SLASH}, {0x1c9}},
};

const Node Compose::OBJ_3084155429248[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0x131}},
	{{1, 1, L1, KEY_SLASH}, {0x133}},
};

const Node Compose::OBJ_3084155429168[] PROGMEM = {
	{{0, 1, L2, KEY_S}, {0x130}},
	{{1, 1, L2, KEY_SLASH}, {0x132}},
};

const Node Compose::OBJ_3084155430288[] PROGMEM = {
	{{0, 1, L1, KEY_U}, {0x292}},
	{{1, 1, L1, KEY_B}, {0x292}},
};

const Node Compose::OBJ_3084155430608[] PROGMEM = {
	{{0, 1, L1, KEY_O}, {0xfb00}},
	{{0, 1, L1, KEY_S}, {0xfb01}},
	{{1, 1, L1, KEY_E}, {0xfb02}},
};

const Node Compose::OBJ_3084155430928[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0xfb03}},
	{{1, 1, L1, KEY_E}, {0xfb04}},
};

const Node Compose::OBJ_3084155431168[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0xfb05}},
};

const Node Compose::OBJ_3084155431568[] PROGMEM = {
	{{0, 1, L2, KEY_B}, {0x1f1}},
	{{1, 1, L1, KEY_B}, {0x1f2}},
};

const Node Compose::OBJ_3084155431808[] PROGMEM = {
	{{0, 1, L1, KEY_B}, {0x1f3}},
	{{1, 0, L1, KEY_D}, {(uint16_t) OBJ_3084155528192}},
};

const Node Compose::OBJ_3084155528192[] PROGMEM = {
	{{1, 1, L1, KEY_I}, {0x2020}},
};

const Node Compose::OBJ_3084155432688[] PROGMEM = {
	{{0, 1, L2, KEY_SLASH}, {0x1ca}},
	{{1, 1, L1, KEY_SLASH}, {0x1cb}},
};

const Node Compose::OBJ_3084155453504[] PROGMEM = {
	{{1, 1, L1, KEY_SLASH}, {0x1cc}},
};

const Node Compose::OBJ_3084155455344[] PROGMEM = {
	{{0, 1, L3, KEY_Y}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2047}},
	{{0, 1, L1, KEY_3}, {0x2154}},
	{{1, 1, L1, KEY_5}, {0x2156}},
};

const Node Compose::OBJ_3084155455424[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x203c}},
	{{0, 1, L1, KEYPAD_2}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2049}},
	{{1, 1, L6, KEY_SEMICOLON}, {0x26a0}},
};

const Node Compose::OBJ_3084155455504[] PROGMEM = {
	{{0, 1, L3, KEY_Y}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2047}},
	{{0, 1, L1, KEYPAD_3}, {0x2154}},
	{{1, 1, L1, KEYPAD_5}, {0x2156}},
};

const Node Compose::OBJ_3084155455904[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x2047}},
	{{0, 1, L1, KEYPAD_2}, {0x2047}},
	{{1, 1, L3, KEY_Y}, {0x2048}},
};

const Node Compose::OBJ_3084155456384[] PROGMEM = {
	{{0, 0, L3, KEY_H}, {(uint16_t) OBJ_3084155456544}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) OBJ_3084155456464}},
	{{0, 0, L4, KEY_H}, {(uint16_t) OBJ_3084155457104}},
	{{0, 0, L4, KEY_Y}, {(uint16_t) OBJ_3084155457264}},
	{{0, 1, L1, KEY_3}, {0x2153}},
	{{0, 1, L1, KEY_5}, {0x2155}},
	{{0, 1, L1, KEY_6}, {0x2159}},
	{{0, 1, L1, KEY_8}, {0x215b}},
	{{0, 1, L3, KEY_S}, {0x215f}},
	{{1, 1, L1, KEYPAD_DIVIDE}, {0x215f}},
};

const Node Compose::OBJ_3084155456544[] PROGMEM = {
	{{1, 1, L3, KEY_Y}, {0x203d}},
};

const Node Compose::OBJ_3084155456464[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x203d}},
};

const Node Compose::OBJ_3084155457104[] PROGMEM = {
	{{1, 1, L4, KEY_Y}, {0x2e18}},
};

const Node Compose::OBJ_3084155457264[] PROGMEM = {
	{{1, 1, L4, KEY_H}, {0x2e18}},
};

const Node Compose::OBJ_3084155456704[] PROGMEM = {
	{{0, 0, L3, KEY_H}, {(uint16_t) OBJ_3084155456944}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) OBJ_3084155456864}},
	{{0, 0, L4, KEY_H}, {(uint16_t) OBJ_3084155457424}},
	{{0, 0, L4, KEY_Y}, {(uint16_t) OBJ_3084155465872}},
	{{0, 1, L1, KEYPAD_3}, {0x2153}},
	{{0, 1, L1, KEYPAD_5}, {0x2155}},
	{{0, 1, L1, KEYPAD_6}, {0x2159}},
	{{0, 1, L1, KEYPAD_8}, {0x215b}},
	{{0, 1, L3, KEY_S}, {0x215f}},
	{{0, 1, L1, KEYPAD_DIVIDE}, {0x215f}},
	{{0, 1, L1, KEYPAD_4}, {0xbc}},
	{{1, 1, L1, KEYPAD_2}, {0xbd}},
};

const Node Compose::OBJ_3084155456944[] PROGMEM = {
	{{1, 1, L3, KEY_Y}, {0x203d}},
};

const Node Compose::OBJ_3084155456864[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x203d}},
};

const Node Compose::OBJ_3084155457424[] PROGMEM = {
	{{1, 1, L4, KEY_Y}, {0x2e18}},
};

const Node Compose::OBJ_3084155465872[] PROGMEM = {
	{{1, 1, L4, KEY_H}, {0x2e18}},
};

const Node Compose::OBJ_3084155466032[] PROGMEM = {
	{{1, 1, L2, KEYPAD_9}, {0x2021}},
};

const Node Compose::OBJ_3084155466512[] PROGMEM = {
	{{1, 1, L5, KEY_SPACE}, {0x2d}},
};

const Node Compose::OBJ_3084155466752[] PROGMEM = {
	{{0, 1, L1, KEY_7}, {0x204a}},
	{{1, 1, L1, KEY_8}, {0x215e}},
};

const Node Compose::OBJ_3084155466672[] PROGMEM = {
	{{0, 1, L1, KEYPAD_7}, {0x204a}},
	{{1, 1, L1, KEYPAD_8}, {0x215e}},
};

const Node Compose::OBJ_3084155467152[] PROGMEM = {
	{{0, 0, L1, KEY_1}, {(uint16_t) OBJ_3084155467072}},
	{{0, 1, L1, KEY_2}, {0x2161}},
	{{0, 1, L1, KEY_3}, {0x2162}},
	{{0, 1, L1, KEY_4}, {0x2163}},
	{{0, 1, L1, KEY_5}, {0x2164}},
	{{0, 1, L1, KEY_6}, {0x2165}},
	{{0, 1, L1, KEY_7}, {0x2166}},
	{{0, 1, L1, KEY_8}, {0x2167}},
	{{0, 1, L1, KEY_9}, {0x2168}},
	{{0, 0, L1, KEYPAD_1}, {(uint16_t) OBJ_3084155468112}},
	{{0, 1, L1, KEYPAD_2}, {0x2161}},
	{{0, 1, L1, KEYPAD_3}, {0x2162}},
	{{0, 1, L1, KEYPAD_4}, {0x2163}},
	{{0, 1, L1, KEYPAD_5}, {0x2164}},
	{{0, 1, L1, KEYPAD_6}, {0x2165}},
	{{0, 1, L1, KEYPAD_7}, {0x2166}},
	{{0, 1, L1, KEYPAD_8}, {0x2167}},
	{{1, 1, L1, KEYPAD_9}, {0x2168}},
};

const Node Compose::OBJ_3084155467072[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2160}},
	{{0, 1, L1, KEY_0}, {0x2169}},
	{{0, 1, L1, KEY_1}, {0x216a}},
	{{1, 1, L1, KEY_2}, {0x216b}},
};

const Node Compose::OBJ_3084155468112[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2160}},
	{{0, 1, L1, KEYPAD_0}, {0x2169}},
	{{0, 1, L1, KEYPAD_1}, {0x216a}},
	{{1, 1, L1, KEYPAD_2}, {0x216b}},
};

const Node Compose::OBJ_3084155469152[] PROGMEM = {
	{{0, 0, L1, KEY_1}, {(uint16_t) OBJ_3084155469312}},
	{{0, 1, L1, KEY_2}, {0x2171}},
	{{0, 1, L1, KEY_3}, {0x2172}},
	{{0, 1, L1, KEY_4}, {0x2173}},
	{{0, 1, L1, KEY_5}, {0x2174}},
	{{0, 1, L1, KEY_6}, {0x2175}},
	{{0, 1, L1, KEY_7}, {0x2176}},
	{{0, 1, L1, KEY_8}, {0x2177}},
	{{0, 1, L1, KEY_9}, {0x2178}},
	{{0, 0, L1, KEYPAD_1}, {(uint16_t) OBJ_3084155482656}},
	{{0, 1, L1, KEYPAD_2}, {0x2171}},
	{{0, 1, L1, KEYPAD_3}, {0x2172}},
	{{0, 1, L1, KEYPAD_4}, {0x2173}},
	{{0, 1, L1, KEYPAD_5}, {0x2174}},
	{{0, 1, L1, KEYPAD_6}, {0x2175}},
	{{0, 1, L1, KEYPAD_7}, {0x2176}},
	{{0, 1, L1, KEYPAD_8}, {0x2177}},
	{{1, 1, L1, KEYPAD_9}, {0x2178}},
};

const Node Compose::OBJ_3084155469312[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2170}},
	{{0, 1, L1, KEY_0}, {0x2179}},
	{{0, 1, L1, KEY_1}, {0x217a}},
	{{1, 1, L1, KEY_2}, {0x217b}},
};

const Node Compose::OBJ_3084155482656[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2170}},
	{{0, 1, L1, KEYPAD_0}, {0x2179}},
	{{0, 1, L1, KEYPAD_1}, {0x217a}},
	{{1, 1, L1, KEYPAD_2}, {0x217b}},
};

const Node Compose::OBJ_3084155484016[] PROGMEM = {
	{{0, 1, L1, KEY_5}, {0x2157}},
	{{1, 1, L1, KEY_8}, {0x215c}},
};

const Node Compose::OBJ_3084155484096[] PROGMEM = {
	{{1, 1, L1, KEY_5}, {0x2158}},
};

const Node Compose::OBJ_3084155484416[] PROGMEM = {
	{{0, 1, L1, KEY_6}, {0x215a}},
	{{1, 1, L1, KEY_8}, {0x215d}},
};

const Node Compose::OBJ_3084155485376[] PROGMEM = {
	{{0, 1, L1, KEYPAD_5}, {0x2157}},
	{{0, 1, L1, KEYPAD_8}, {0x215c}},
	{{1, 1, L1, KEYPAD_4}, {0xbe}},
};

const Node Compose::OBJ_3084155485456[] PROGMEM = {
	{{1, 1, L1, KEYPAD_5}, {0x2158}},
};

const Node Compose::OBJ_3084155485776[] PROGMEM = {
	{{0, 1, L1, KEYPAD_6}, {0x215a}},
	{{1, 1, L1, KEYPAD_8}, {0x215d}},
};

const Node Compose::OBJ_3084155511648[] PROGMEM = {
	{{0, 1, L3, KEY_K}, {0x263a}},
	{{1, 1, L3, KEY_J}, {0x2639}},
};

const Node Compose::OBJ_3084155511888[] PROGMEM = {
	{{1, 0, L1, KEYPAD_DIVIDE}, {(uint16_t) OBJ_3084155512048}},
};

const Node Compose::OBJ_3084155512048[] PROGMEM = {
	{{1, 1, L1, KEY_G}, {0x2105}},
};

const Node Compose::OBJ_3084155511968[] PROGMEM = {
	{{0, 1, L5, KEY_5}, {0x26a2}},
	{{1, 1, L5, KEY_4}, {0x26a4}},
};

const Node Compose::OBJ_3084155512208[] PROGMEM = {
	{{0, 1, L5, KEY_4}, {0x26a3}},
	{{1, 1, L5, KEY_5}, {0x26a4}},
};

const Node Compose::OBJ_3084155513568[] PROGMEM = {
	{{0, 1, L1, KEY_3}, {0x2665}},
	{{1, 1, L1, KEYPAD_3}, {0x2665}},
};

const Node Compose::OBJ_3084155513808[] PROGMEM = {
	{{1, 0, L2, KEY_J}, {(uint16_t) OBJ_3084155513968}},
};

const Node Compose::OBJ_3084155513968[] PROGMEM = {
	{{1, 1, L2, KEY_SEMICOLON}, {0x262e}},
};

const Node Compose::OBJ_3084155513888[] PROGMEM = {
	{{1, 1, L3, KEY_R}, {0x25a1}},
};

const Node Compose::OBJ_3084155514128[] PROGMEM = {
	{{0, 1, L2, KEYPAD_7}, {0x2611}},
	{{1, 1, L2, KEYPAD_8}, {0x2612}},
};

const Node Compose::OBJ_3084155514288[] PROGMEM = {
	{{1, 1, L6, KEYPAD_0}, {0x2611}},
};

const Node Compose::OBJ_3084155514608[] PROGMEM = {
	{{1, 1, L6, KEYPAD_0}, {0x2612}},
};

const Node Compose::OBJ_3084155514688[] PROGMEM = {
	{{1, 1, L3, KEY_Y}, {0x26a0}},
};

const Node Compose::OBJ_3084155527472[] PROGMEM = {
	{{1, 1, L2, KEYPAD_0}, {0x237d}},
};

const Node Compose::OBJ_3084155527552[] PROGMEM = {
	{{0, 1, L1, KEY_O}, {0x20b0}},
	{{1, 0, L1, KEY_G}, {(uint16_t) OBJ_3084155527952}},
};

const Node Compose::OBJ_3084155527952[] PROGMEM = {
	{{1, 1, L1, KEY_S}, {0x2318}},
};

const Node Compose::OBJ_3084155528592[] PROGMEM = {
	{{0, 0, L3, KEY_S}, {(uint16_t) OBJ_3084155528672}},
	{{1, 0, L1, KEYPAD_DIVIDE}, {(uint16_t) OBJ_3084155528512}},
};

const Node Compose::OBJ_3084155528672[] PROGMEM = {
	{{1, 1, L1, KEY_PERIOD}, {0x2052}},
};

const Node Compose::OBJ_3084155528512[] PROGMEM = {
	{{1, 1, L1, KEY_PERIOD}, {0x2052}},
};

const Node Compose::OBJ_3084155528832[] PROGMEM = {
	{{1, 1, L2, KEY_PERIOD}, {0x2023}},
};


uint16_t Compose::transition(uint8_t layer, uint8_t key) {
	Node* cur = currentNode;
	Node val_cur;

	do {
		memcpy_P(&val_cur, cur, sizeof(val_cur));
		if (val_cur.layeredKey.layer == layer && val_cur.layeredKey.keycode == key) { //found
			if (val_cur.layeredKey.isLeaf) {
				currentNode = const_cast<Node*>(root);
				return val_cur.payload.unicode;
				
			} else { //found, waiting for next key
				currentNode = const_cast<Node*>(val_cur.payload.nodes);
				return 1; 
			}
		}
		cur++;
	} while (val_cur.layeredKey.isLastElement == 0);
	
	//not found
	currentNode = const_cast<Node*>(root);
	return 0;
}

void Compose::reset(){
	currentNode = const_cast<Node*>(root);
}