/***********************************************************************/
/******************* This file is generated by *************************/
/******************* the Compose Generator *****************************/
/***********************************************************************/

#ifndef __COMPOSE_H__
#define __COMPOSE_H__

#include "NeoIncludes.h"
#include <assert.h>

/*
 * The tree is static, therefore no methods for removing/adding elements,
 * to not make life too complicated, this file is generated by a script.
 * 
 * The implementation with bit fields and unions is not the most pretty one
 * but the most memory efficient.
 * 
 * Payload is either pointing to next node or contains unicode symbol.
 * indication what is inside is given by the isLeaf flag cast to uint16_t
 * in Initialization only to trick the compiler, as only first element of the
 * union can be initialized. 
*/

struct LayeredKey {
	uint8_t layer;
	uint8_t key;
};

struct Node {
	struct {
		uint8_t isLastElement : 1;
		uint8_t isLeaf : 1;
		uint8_t layer : 6;
		uint8_t keycode : 8;
	} layeredKey;
	union {
		uint16_t unicode;
		Node* nodes;
	} payload;
};


class Compose
{
	private:
	Node* currentNode;

	const static Node root[] PROGMEM;
	const static Node NODE_2253753848192[] PROGMEM;
	const static Node NODE_2253754144624[] PROGMEM;
	const static Node NODE_2253754287104[] PROGMEM;
	const static Node NODE_2253754287264[] PROGMEM;
	const static Node NODE_2253754386128[] PROGMEM;
	const static Node NODE_2253754386288[] PROGMEM;
	const static Node NODE_2253754409984[] PROGMEM;
	const static Node NODE_2253754410304[] PROGMEM;
	const static Node NODE_2253754410784[] PROGMEM;
	const static Node NODE_2253754411104[] PROGMEM;
	const static Node NODE_2253754411344[] PROGMEM;
	const static Node NODE_2253754411504[] PROGMEM;
	const static Node NODE_2253754411584[] PROGMEM;
	const static Node NODE_2253754412864[] PROGMEM;
	const static Node NODE_2253754421312[] PROGMEM;
	const static Node NODE_2253754421872[] PROGMEM;
	const static Node NODE_2253754422592[] PROGMEM;
	const static Node NODE_2253754422912[] PROGMEM;
	const static Node NODE_2253754423072[] PROGMEM;
	const static Node NODE_2253754386208[] PROGMEM;
	const static Node NODE_2253754412624[] PROGMEM;
	const static Node NODE_2253754421392[] PROGMEM;
	const static Node NODE_2253754410144[] PROGMEM;
	const static Node NODE_2253754412784[] PROGMEM;
	const static Node NODE_2253754410944[] PROGMEM;
	const static Node NODE_2253754423712[] PROGMEM;
	const static Node NODE_2253754424032[] PROGMEM;
	const static Node NODE_2253754421712[] PROGMEM;
	const static Node NODE_2253753848112[] PROGMEM;
	const static Node NODE_2253753909472[] PROGMEM;
	const static Node NODE_2253753909712[] PROGMEM;
	const static Node NODE_2253753909872[] PROGMEM;
	const static Node NODE_2253754351104[] PROGMEM;
	const static Node NODE_2253754351184[] PROGMEM;
	const static Node NODE_2253754067840[] PROGMEM;
	const static Node NODE_2253753848032[] PROGMEM;
	const static Node NODE_2253754106400[] PROGMEM;
	const static Node NODE_2253754145984[] PROGMEM;
	const static Node NODE_2253753848432[] PROGMEM;
	const static Node NODE_2253751327056[] PROGMEM;
	const static Node NODE_2253753890992[] PROGMEM;
	const static Node NODE_2253753891152[] PROGMEM;
	const static Node NODE_2253753891232[] PROGMEM;
	const static Node NODE_2253754067600[] PROGMEM;
	const static Node NODE_2253754082464[] PROGMEM;
	const static Node NODE_2253754084544[] PROGMEM;
	const static Node NODE_2253754106160[] PROGMEM;
	const static Node NODE_2253754109200[] PROGMEM;
	const static Node NODE_2253754143824[] PROGMEM;
	const static Node NODE_2253754144864[] PROGMEM;
	const static Node NODE_2253754165344[] PROGMEM;
	const static Node NODE_2253754185184[] PROGMEM;
	const static Node NODE_2253754185344[] PROGMEM;
	const static Node NODE_2253753848752[] PROGMEM;
	const static Node NODE_2253754068400[] PROGMEM;
	const static Node NODE_2253754085264[] PROGMEM;
	const static Node NODE_2253754143744[] PROGMEM;
	const static Node NODE_2253754145264[] PROGMEM;
	const static Node NODE_2253754165664[] PROGMEM;
	const static Node NODE_2253754184944[] PROGMEM;
	const static Node NODE_2253754185024[] PROGMEM;
	const static Node NODE_2253753848992[] PROGMEM;
	const static Node NODE_2253753849232[] PROGMEM;
	const static Node NODE_2253753849312[] PROGMEM;
	const static Node NODE_2253753850912[] PROGMEM;
	const static Node NODE_2253753868752[] PROGMEM;
	const static Node NODE_2253753981504[] PROGMEM;
	const static Node NODE_2253753981824[] PROGMEM;
	const static Node NODE_2253753982544[] PROGMEM;
	const static Node NODE_2253753982464[] PROGMEM;
	const static Node NODE_2253753982864[] PROGMEM;
	const static Node NODE_2253754351024[] PROGMEM;
	const static Node NODE_2253754351344[] PROGMEM;
	const static Node NODE_2253754370784[] PROGMEM;
	const static Node NODE_2253754385488[] PROGMEM;
	const static Node NODE_2253754423952[] PROGMEM;
	const static Node NODE_2253754674768[] PROGMEM;
	const static Node NODE_2253754386768[] PROGMEM;
	const static Node NODE_2253754387008[] PROGMEM;
	const static Node NODE_2253754387248[] PROGMEM;
	const static Node NODE_2253754580160[] PROGMEM;
	const static Node NODE_2253753849152[] PROGMEM;
	const static Node NODE_2253754127680[] PROGMEM;
	const static Node NODE_2253754127920[] PROGMEM;
	const static Node NODE_2253754248784[] PROGMEM;
	const static Node NODE_2253754248864[] PROGMEM;
	const static Node NODE_2253754481936[] PROGMEM;
	const static Node NODE_2253753849472[] PROGMEM;
	const static Node NODE_2253754479776[] PROGMEM;
	const static Node NODE_2253754480176[] PROGMEM;
	const static Node NODE_2253754600880[] PROGMEM;
	const static Node NODE_2253753849632[] PROGMEM;
	const static Node NODE_2253754144384[] PROGMEM;
	const static Node NODE_2253754145744[] PROGMEM;
	const static Node NODE_2253754166144[] PROGMEM;
	const static Node NODE_2253754185504[] PROGMEM;
	const static Node NODE_2253754185664[] PROGMEM;
	const static Node NODE_2253754207744[] PROGMEM;
	const static Node NODE_2253754600480[] PROGMEM;
	const static Node NODE_2253753849792[] PROGMEM;
	const static Node NODE_2253753871872[] PROGMEM;
	const static Node NODE_2253753890672[] PROGMEM;
	const static Node NODE_2253753890912[] PROGMEM;
	const static Node NODE_2253753890752[] PROGMEM;
	const static Node NODE_2253754067040[] PROGMEM;
	const static Node NODE_2253754081344[] PROGMEM;
	const static Node NODE_2253754083424[] PROGMEM;
	const static Node NODE_2253754108240[] PROGMEM;
	const static Node NODE_2253754673648[] PROGMEM;
	const static Node NODE_2253753850192[] PROGMEM;
	const static Node NODE_2253754109520[] PROGMEM;
	const static Node NODE_2253754128640[] PROGMEM;
	const static Node NODE_2253753850352[] PROGMEM;
	const static Node NODE_2253754082864[] PROGMEM;
	const static Node NODE_2253754331024[] PROGMEM;
	const static Node NODE_2253754347664[] PROGMEM;
	const static Node NODE_2253754350544[] PROGMEM;
	const static Node NODE_2253754370704[] PROGMEM;
	const static Node NODE_2253754560736[] PROGMEM;
	const static Node NODE_2253754562256[] PROGMEM;
	const static Node NODE_2253754562576[] PROGMEM;
	const static Node NODE_2253754562736[] PROGMEM;
	const static Node NODE_2253754562976[] PROGMEM;
	const static Node NODE_2253754563136[] PROGMEM;
	const static Node NODE_2253754348144[] PROGMEM;
	const static Node NODE_2253754348784[] PROGMEM;
	const static Node NODE_2253754370464[] PROGMEM;
	const static Node NODE_2253754371024[] PROGMEM;
	const static Node NODE_2253754371264[] PROGMEM;
	const static Node NODE_2253753850672[] PROGMEM;
	const static Node NODE_2253753850592[] PROGMEM;
	const static Node NODE_2253754144144[] PROGMEM;
	const static Node NODE_2253754145504[] PROGMEM;
	const static Node NODE_2253754165904[] PROGMEM;
	const static Node NODE_2253754424192[] PROGMEM;
	const static Node NODE_2253753850512[] PROGMEM;
	const static Node NODE_2253754424352[] PROGMEM;
	const static Node NODE_2253754424672[] PROGMEM;
	const static Node NODE_2253753851072[] PROGMEM;
	const static Node NODE_2253754308624[] PROGMEM;
	const static Node NODE_2253754308944[] PROGMEM;
	const static Node NODE_2253754327984[] PROGMEM;
	const static Node NODE_2253754579680[] PROGMEM;
	const static Node NODE_2253754579920[] PROGMEM;
	const static Node NODE_2253754580240[] PROGMEM;
	const static Node NODE_2253754580400[] PROGMEM;
	const static Node NODE_2253754328864[] PROGMEM;
	const static Node NODE_2253754348224[] PROGMEM;
	const static Node NODE_2253753851312[] PROGMEM;
	const static Node NODE_2253754166384[] PROGMEM;
	const static Node NODE_2253753851632[] PROGMEM;
	const static Node NODE_2253753851712[] PROGMEM;
	const static Node NODE_2253753979104[] PROGMEM;
	const static Node NODE_2253754480016[] PROGMEM;
	const static Node NODE_2253754480336[] PROGMEM;
	const static Node NODE_2253753851472[] PROGMEM;
	const static Node NODE_2253753913232[] PROGMEM;
	const static Node NODE_2253754597520[] PROGMEM;
	const static Node NODE_2253754597760[] PROGMEM;
	const static Node NODE_2253754598000[] PROGMEM;
	const static Node NODE_2253754598080[] PROGMEM;
	const static Node NODE_2253753870032[] PROGMEM;
	const static Node NODE_2253754387568[] PROGMEM;
	const static Node NODE_2253754388368[] PROGMEM;
	const static Node NODE_2253753869712[] PROGMEM;
	const static Node NODE_2253751326176[] PROGMEM;
	const static Node NODE_2253754249104[] PROGMEM;
	const static Node NODE_2253754349024[] PROGMEM;
	const static Node NODE_2253753766912[] PROGMEM;
	const static Node NODE_2253753766752[] PROGMEM;
	const static Node NODE_2253754500176[] PROGMEM;
	const static Node NODE_2253754641120[] PROGMEM;
	const static Node NODE_2253753766672[] PROGMEM;
	const static Node NODE_2253753766352[] PROGMEM;
	const static Node NODE_2253753889312[] PROGMEM;
	const static Node NODE_2253753889472[] PROGMEM;
	const static Node NODE_2253753889552[] PROGMEM;
	const static Node NODE_2253753890352[] PROGMEM;
	const static Node NODE_2253754384528[] PROGMEM;
	const static Node NODE_2253754500336[] PROGMEM;
	const static Node NODE_2253753890272[] PROGMEM;
	const static Node NODE_2253753891392[] PROGMEM;
	const static Node NODE_2253753891712[] PROGMEM;
	const static Node NODE_2253753892032[] PROGMEM;
	const static Node NODE_2253753892272[] PROGMEM;
	const static Node NODE_2253753892672[] PROGMEM;
	const static Node NODE_2253753909392[] PROGMEM;
	const static Node NODE_2253753979264[] PROGMEM;
	const static Node NODE_2253753910272[] PROGMEM;
	const static Node NODE_2253753910512[] PROGMEM;
	const static Node NODE_2253753911632[] PROGMEM;
	const static Node NODE_2253753910752[] PROGMEM;
	const static Node NODE_2253753911872[] PROGMEM;
	const static Node NODE_2253753912192[] PROGMEM;
	const static Node NODE_2253753912352[] PROGMEM;
	const static Node NODE_2253753912272[] PROGMEM;
	const static Node NODE_2253753912512[] PROGMEM;
	const static Node NODE_2253753912672[] PROGMEM;
	const static Node NODE_2253754286224[] PROGMEM;
	const static Node NODE_2253753912832[] PROGMEM;
	const static Node NODE_2253753929792[] PROGMEM;
	const static Node NODE_2253753930032[] PROGMEM;
	const static Node NODE_2253753929952[] PROGMEM;
	const static Node NODE_2253753930352[] PROGMEM;
	const static Node NODE_2253753931232[] PROGMEM;
	const static Node NODE_2253753931392[] PROGMEM;
	const static Node NODE_2253753932672[] PROGMEM;
	const static Node NODE_2253753932752[] PROGMEM;
	const static Node NODE_2253753933072[] PROGMEM;
	const static Node NODE_2253753954768[] PROGMEM;
	const static Node NODE_2253753955008[] PROGMEM;
	const static Node NODE_2253753955168[] PROGMEM;
	const static Node NODE_2253753955088[] PROGMEM;
	const static Node NODE_2253753955328[] PROGMEM;
	const static Node NODE_2253753956448[] PROGMEM;
	const static Node NODE_2253754561696[] PROGMEM;
	const static Node NODE_2253753956768[] PROGMEM;
	const static Node NODE_2253753956848[] PROGMEM;
	const static Node NODE_2253754268384[] PROGMEM;
	const static Node NODE_2253754268464[] PROGMEM;
	const static Node NODE_2253753956608[] PROGMEM;
	const static Node NODE_2253753957008[] PROGMEM;
	const static Node NODE_2253753957168[] PROGMEM;
	const static Node NODE_2253753957488[] PROGMEM;
	const static Node NODE_2253753957568[] PROGMEM;
	const static Node NODE_2253753957968[] PROGMEM;
	const static Node NODE_2253753958048[] PROGMEM;
	const static Node NODE_2253753979024[] PROGMEM;
	const static Node NODE_2253754500496[] PROGMEM;
	const static Node NODE_2253754500736[] PROGMEM;
	const static Node NODE_2253754673248[] PROGMEM;
	const static Node NODE_2253753979664[] PROGMEM;
	const static Node NODE_2253753979744[] PROGMEM;
	const static Node NODE_2253753979904[] PROGMEM;
	const static Node NODE_2253754233536[] PROGMEM;
	const static Node NODE_2253754369184[] PROGMEM;
	const static Node NODE_2253754234576[] PROGMEM;
	const static Node NODE_2253754234976[] PROGMEM;
	const static Node NODE_2253754235616[] PROGMEM;
	const static Node NODE_2253754236016[] PROGMEM;
	const static Node NODE_2253754371824[] PROGMEM;
	const static Node NODE_2253754543136[] PROGMEM;
	const static Node NODE_2253754236096[] PROGMEM;
	const static Node NODE_2253754673888[] PROGMEM;
	const static Node NODE_2253754674048[] PROGMEM;
	const static Node NODE_2253754673968[] PROGMEM;
	const static Node NODE_2253754236736[] PROGMEM;
	const static Node NODE_2253754245984[] PROGMEM;
	const static Node NODE_2253754641360[] PROGMEM;
	const static Node NODE_2253754247024[] PROGMEM;
	const static Node NODE_2253754542496[] PROGMEM;
	const static Node NODE_2253754561136[] PROGMEM;
	const static Node NODE_2253754577920[] PROGMEM;
	const static Node NODE_2253754579120[] PROGMEM;
	const static Node NODE_2253754579200[] PROGMEM;
	const static Node NODE_2253754247904[] PROGMEM;
	const static Node NODE_2253754248144[] PROGMEM;
	const static Node NODE_2253754248944[] PROGMEM;
	const static Node NODE_2253754265664[] PROGMEM;
	const static Node NODE_2253754265984[] PROGMEM;
	const static Node NODE_2253754267264[] PROGMEM;
	const static Node NODE_2253754267584[] PROGMEM;
	const static Node NODE_2253754269024[] PROGMEM;
	const static Node NODE_2253754269424[] PROGMEM;
	const static Node NODE_2253754286464[] PROGMEM;
	const static Node NODE_2253754517840[] PROGMEM;
	const static Node NODE_2253754286864[] PROGMEM;
	const static Node NODE_2253754287184[] PROGMEM;
	const static Node NODE_2253754563936[] PROGMEM;
	const static Node NODE_2253754564496[] PROGMEM;
	const static Node NODE_2253754618160[] PROGMEM;
	const static Node NODE_2253754327504[] PROGMEM;
	const static Node NODE_2253754328224[] PROGMEM;
	const static Node NODE_2253754328064[] PROGMEM;
	const static Node NODE_2253754576960[] PROGMEM;
	const static Node NODE_2253754329024[] PROGMEM;
	const static Node NODE_2253754329184[] PROGMEM;
	const static Node NODE_2253754329744[] PROGMEM;
	const static Node NODE_2253754329824[] PROGMEM;
	const static Node NODE_2253754350784[] PROGMEM;
	const static Node NODE_2253754368304[] PROGMEM;
	const static Node NODE_2253754368464[] PROGMEM;
	const static Node NODE_2253754368544[] PROGMEM;
	const static Node NODE_2253754369264[] PROGMEM;
	const static Node NODE_2253754369104[] PROGMEM;
	const static Node NODE_2253754369584[] PROGMEM;
	const static Node NODE_2253754369744[] PROGMEM;
	const static Node NODE_2253754371184[] PROGMEM;
	const static Node NODE_2253754371664[] PROGMEM;
	const static Node NODE_2253754371904[] PROGMEM;
	const static Node NODE_2253754384848[] PROGMEM;
	const static Node NODE_2253754409184[] PROGMEM;
	const static Node NODE_2253754409424[] PROGMEM;
	const static Node NODE_2253754409824[] PROGMEM;
	const static Node NODE_2253754409504[] PROGMEM;
	const static Node NODE_2253754409904[] PROGMEM;
	const static Node NODE_2253754455680[] PROGMEM;
	const static Node NODE_2253754457280[] PROGMEM;
	const static Node NODE_2253754457600[] PROGMEM;
	const static Node NODE_2253754578800[] PROGMEM;
	const static Node NODE_2253753847952[] PROGMEM;
	const static Node NODE_2253754479056[] PROGMEM;
	const static Node NODE_2253754480736[] PROGMEM;
	const static Node NODE_2253754562096[] PROGMEM;
	const static Node NODE_2253754481296[] PROGMEM;
	const static Node NODE_2253754561456[] PROGMEM;
	const static Node NODE_2253754499296[] PROGMEM;
	const static Node NODE_2253754501456[] PROGMEM;
	const static Node NODE_2253754543936[] PROGMEM;
	const static Node NODE_2253754502336[] PROGMEM;
	const static Node NODE_2253754502576[] PROGMEM;
	const static Node NODE_2253754502816[] PROGMEM;
	const static Node NODE_2253754502976[] PROGMEM;
	const static Node NODE_2253754502896[] PROGMEM;
	const static Node NODE_2253754515600[] PROGMEM;
	const static Node NODE_2253754515920[] PROGMEM;
	const static Node NODE_2253754562416[] PROGMEM;
	const static Node NODE_2253754517360[] PROGMEM;
	const static Node NODE_2253754518000[] PROGMEM;
	const static Node NODE_2253754563856[] PROGMEM;
	const static Node NODE_2253754577280[] PROGMEM;
	const static Node NODE_2253754577520[] PROGMEM;
	const static Node NODE_2253754577600[] PROGMEM;
	const static Node NODE_2253754598480[] PROGMEM;
	const static Node NODE_2253754598640[] PROGMEM;
	const static Node NODE_2253754672048[] PROGMEM;
	const static Node NODE_2253754672448[] PROGMEM;
	const static Node NODE_2253754672688[] PROGMEM;
	const static Node NODE_2253754673008[] PROGMEM;

	const static LayeredKey aliases[][2];
	
	LayeredKey getAlias(uint8_t layer, uint8_t key);

	public:
	Compose() : currentNode(const_cast<Node*>(root)){
		//if this assertion fails, the struct in Node has to be reworked for the target architecture
		assert(sizeof(uint16_t) >= sizeof(Node*));
	}
	
	uint16_t transition(uint8_t layer, uint8_t key);
	void reset();
	
	


}; //Compose

#endif //__COMPOSE_H__