/***********************************************************************/
/******************* This file is generated by *************************/
/******************* the Compose Generator *****************************/
/***********************************************************************/

#ifndef __COMPOSE_H__
#define __COMPOSE_H__

#include "NeoIncludes.h"
#include <assert.h>

/*
 * The tree is static, therefore no methods for removing/adding elements,
 * to not make life too complicated, this file is generated by a script.
 * 
 * The implementation with bit fields and unions is not the most pretty one
 * but the most memory efficient.
 * 
 * Payload is either pointing to next node or contains unicode symbol.
 * indication what is inside is given by the isLeaf flag cast to uint16_t
 * in Initialization only to trick the compiler, as only first element of the
 * union can be initialized. 
*/

struct LayeredKey {
	uint8_t layer;
	uint8_t key;
};

struct Node {
	struct {
		uint8_t isLastElement : 1;
		uint8_t isLeaf : 1;
		uint8_t layer : 6;
		uint8_t keycode : 8;
	} layeredKey;
	union {
		uint16_t unicode;
		Node* nodes;
	} payload;
};


class Compose
{
	private:
	Node* currentNode;

	const static Node root[] PROGMEM;
	const static Node NODE_1925925212048[] PROGMEM;
	const static Node NODE_1925925574112[] PROGMEM;
	const static Node NODE_1925925617312[] PROGMEM;
	const static Node NODE_1925925617472[] PROGMEM;
	const static Node NODE_1925925737952[] PROGMEM;
	const static Node NODE_1925925738112[] PROGMEM;
	const static Node NODE_1925925753616[] PROGMEM;
	const static Node NODE_1925925753936[] PROGMEM;
	const static Node NODE_1925925754416[] PROGMEM;
	const static Node NODE_1925925754736[] PROGMEM;
	const static Node NODE_1925925754976[] PROGMEM;
	const static Node NODE_1925925755136[] PROGMEM;
	const static Node NODE_1925925755216[] PROGMEM;
	const static Node NODE_1925925756496[] PROGMEM;
	const static Node NODE_1925925756656[] PROGMEM;
	const static Node NODE_1925925777792[] PROGMEM;
	const static Node NODE_1925925778512[] PROGMEM;
	const static Node NODE_1925925778832[] PROGMEM;
	const static Node NODE_1925925778992[] PROGMEM;
	const static Node NODE_1925925738032[] PROGMEM;
	const static Node NODE_1925925756256[] PROGMEM;
	const static Node NODE_1925925756736[] PROGMEM;
	const static Node NODE_1925925753776[] PROGMEM;
	const static Node NODE_1925925756416[] PROGMEM;
	const static Node NODE_1925925754576[] PROGMEM;
	const static Node NODE_1925925779632[] PROGMEM;
	const static Node NODE_1925925779952[] PROGMEM;
	const static Node NODE_1925925777632[] PROGMEM;
	const static Node NODE_1925925211968[] PROGMEM;
	const static Node NODE_1925925322480[] PROGMEM;
	const static Node NODE_1925925343296[] PROGMEM;
	const static Node NODE_1925925343456[] PROGMEM;
	const static Node NODE_1925925698592[] PROGMEM;
	const static Node NODE_1925925698672[] PROGMEM;
	const static Node NODE_1925925493232[] PROGMEM;
	const static Node NODE_1925925211888[] PROGMEM;
	const static Node NODE_1925925531792[] PROGMEM;
	const static Node NODE_1925925575472[] PROGMEM;
	const static Node NODE_1925925277920[] PROGMEM;
	const static Node NODE_1925922760640[] PROGMEM;
	const static Node NODE_1925925320480[] PROGMEM;
	const static Node NODE_1925925320640[] PROGMEM;
	const static Node NODE_1925925320720[] PROGMEM;
	const static Node NODE_1925925492992[] PROGMEM;
	const static Node NODE_1925925511952[] PROGMEM;
	const static Node NODE_1925925514032[] PROGMEM;
	const static Node NODE_1925925515072[] PROGMEM;
	const static Node NODE_1925925534592[] PROGMEM;
	const static Node NODE_1925925573312[] PROGMEM;
	const static Node NODE_1925925574352[] PROGMEM;
	const static Node NODE_1925925598928[] PROGMEM;
	const static Node NODE_1925925278240[] PROGMEM;
	const static Node NODE_1925925493792[] PROGMEM;
	const static Node NODE_1925925514752[] PROGMEM;
	const static Node NODE_1925925573232[] PROGMEM;
	const static Node NODE_1925925574752[] PROGMEM;
	const static Node NODE_1925925599248[] PROGMEM;
	const static Node NODE_1925925278480[] PROGMEM;
	const static Node NODE_1925925278720[] PROGMEM;
	const static Node NODE_1925925278800[] PROGMEM;
	const static Node NODE_1925925280400[] PROGMEM;
	const static Node NODE_1925925281600[] PROGMEM;
	const static Node NODE_1925925406896[] PROGMEM;
	const static Node NODE_1925925407216[] PROGMEM;
	const static Node NODE_1925925407936[] PROGMEM;
	const static Node NODE_1925925407856[] PROGMEM;
	const static Node NODE_1925925408256[] PROGMEM;
	const static Node NODE_1925925698512[] PROGMEM;
	const static Node NODE_1925925698832[] PROGMEM;
	const static Node NODE_1925925718432[] PROGMEM;
	const static Node NODE_1925925737312[] PROGMEM;
	const static Node NODE_1925925779872[] PROGMEM;
	const static Node NODE_1925925964832[] PROGMEM;
	const static Node NODE_1925925738592[] PROGMEM;
	const static Node NODE_1925925738832[] PROGMEM;
	const static Node NODE_1925925739072[] PROGMEM;
	const static Node NODE_1925925278640[] PROGMEM;
	const static Node NODE_1925925553072[] PROGMEM;
	const static Node NODE_1925925553312[] PROGMEM;
	const static Node NODE_1925925821712[] PROGMEM;
	const static Node NODE_1925925821872[] PROGMEM;
	const static Node NODE_1925925278960[] PROGMEM;
	const static Node NODE_1925925819552[] PROGMEM;
	const static Node NODE_1925925819952[] PROGMEM;
	const static Node NODE_1925925279120[] PROGMEM;
	const static Node NODE_1925925573872[] PROGMEM;
	const static Node NODE_1925925575232[] PROGMEM;
	const static Node NODE_1925925599728[] PROGMEM;
	const static Node NODE_1925925279280[] PROGMEM;
	const static Node NODE_1925925297264[] PROGMEM;
	const static Node NODE_1925925320160[] PROGMEM;
	const static Node NODE_1925925320400[] PROGMEM;
	const static Node NODE_1925925320240[] PROGMEM;
	const static Node NODE_1925925492432[] PROGMEM;
	const static Node NODE_1925925494352[] PROGMEM;
	const static Node NODE_1925925512912[] PROGMEM;
	const static Node NODE_1925925533632[] PROGMEM;
	const static Node NODE_1925925963712[] PROGMEM;
	const static Node NODE_1925925279680[] PROGMEM;
	const static Node NODE_1925925534912[] PROGMEM;
	const static Node NODE_1925925554032[] PROGMEM;
	const static Node NODE_1925925279840[] PROGMEM;
	const static Node NODE_1925925512352[] PROGMEM;
	const static Node NODE_1925925678032[] PROGMEM;
	const static Node NODE_1925925678192[] PROGMEM;
	const static Node NODE_1925925698032[] PROGMEM;
	const static Node NODE_1925925718352[] PROGMEM;
	const static Node NODE_1925925882912[] PROGMEM;
	const static Node NODE_1925925883152[] PROGMEM;
	const static Node NODE_1925925883312[] PROGMEM;
	const static Node NODE_1925925883552[] PROGMEM;
	const static Node NODE_1925925883472[] PROGMEM;
	const static Node NODE_1925925678672[] PROGMEM;
	const static Node NODE_1925925696112[] PROGMEM;
	const static Node NODE_1925925718112[] PROGMEM;
	const static Node NODE_1925925718672[] PROGMEM;
	const static Node NODE_1925925718912[] PROGMEM;
	const static Node NODE_1925925280160[] PROGMEM;
	const static Node NODE_1925925280080[] PROGMEM;
	const static Node NODE_1925925573632[] PROGMEM;
	const static Node NODE_1925925574992[] PROGMEM;
	const static Node NODE_1925925599488[] PROGMEM;
	const static Node NODE_1925925780112[] PROGMEM;
	const static Node NODE_1925925280000[] PROGMEM;
	const static Node NODE_1925925780272[] PROGMEM;
	const static Node NODE_1925925780592[] PROGMEM;
	const static Node NODE_1925925280560[] PROGMEM;
	const static Node NODE_1925925655392[] PROGMEM;
	const static Node NODE_1925925655712[] PROGMEM;
	const static Node NODE_1925925658272[] PROGMEM;
	const static Node NODE_1925925902192[] PROGMEM;
	const static Node NODE_1925925902272[] PROGMEM;
	const static Node NODE_1925925902352[] PROGMEM;
	const static Node NODE_1925925902592[] PROGMEM;
	const static Node NODE_1925925675632[] PROGMEM;
	const static Node NODE_1925925678752[] PROGMEM;
	const static Node NODE_1925925280800[] PROGMEM;
	const static Node NODE_1925925599968[] PROGMEM;
	const static Node NODE_1925925281120[] PROGMEM;
	const static Node NODE_1925925281200[] PROGMEM;
	const static Node NODE_1925925383920[] PROGMEM;
	const static Node NODE_1925925819792[] PROGMEM;
	const static Node NODE_1925925820112[] PROGMEM;
	const static Node NODE_1925925280960[] PROGMEM;
	const static Node NODE_1925925346816[] PROGMEM;
	const static Node NODE_1925925903072[] PROGMEM;
	const static Node NODE_1925925903152[] PROGMEM;
	const static Node NODE_1925925903312[] PROGMEM;
	const static Node NODE_1925925295424[] PROGMEM;
	const static Node NODE_1925925739392[] PROGMEM;
	const static Node NODE_1925925740192[] PROGMEM;
	const static Node NODE_1925925295104[] PROGMEM;
	const static Node NODE_1925922759760[] PROGMEM;
	const static Node NODE_1925925696352[] PROGMEM;
	const static Node NODE_1925925192304[] PROGMEM;
	const static Node NODE_1925925192144[] PROGMEM;
	const static Node NODE_1925925844448[] PROGMEM;
	const static Node NODE_1925925942752[] PROGMEM;
	const static Node NODE_1925925192064[] PROGMEM;
	const static Node NODE_1925925191744[] PROGMEM;
	const static Node NODE_1925925318800[] PROGMEM;
	const static Node NODE_1925925318960[] PROGMEM;
	const static Node NODE_1925925319040[] PROGMEM;
	const static Node NODE_1925925319840[] PROGMEM;
	const static Node NODE_1925925719952[] PROGMEM;
	const static Node NODE_1925925844208[] PROGMEM;
	const static Node NODE_1925925319760[] PROGMEM;
	const static Node NODE_1925925320880[] PROGMEM;
	const static Node NODE_1925925321200[] PROGMEM;
	const static Node NODE_1925925321520[] PROGMEM;
	const static Node NODE_1925925321760[] PROGMEM;
	const static Node NODE_1925925322160[] PROGMEM;
	const static Node NODE_1925925322400[] PROGMEM;
	const static Node NODE_1925925384080[] PROGMEM;
	const static Node NODE_1925925343856[] PROGMEM;
	const static Node NODE_1925925344096[] PROGMEM;
	const static Node NODE_1925925345216[] PROGMEM;
	const static Node NODE_1925925344336[] PROGMEM;
	const static Node NODE_1925925345456[] PROGMEM;
	const static Node NODE_1925925345776[] PROGMEM;
	const static Node NODE_1925925345936[] PROGMEM;
	const static Node NODE_1925925345856[] PROGMEM;
	const static Node NODE_1925925346096[] PROGMEM;
	const static Node NODE_1925925346256[] PROGMEM;
	const static Node NODE_1925925616432[] PROGMEM;
	const static Node NODE_1925925346416[] PROGMEM;
	const static Node NODE_1925925346896[] PROGMEM;
	const static Node NODE_1925925347136[] PROGMEM;
	const static Node NODE_1925925347056[] PROGMEM;
	const static Node NODE_1925925355664[] PROGMEM;
	const static Node NODE_1925925356624[] PROGMEM;
	const static Node NODE_1925925356784[] PROGMEM;
	const static Node NODE_1925925358064[] PROGMEM;
	const static Node NODE_1925925358144[] PROGMEM;
	const static Node NODE_1925925358464[] PROGMEM;
	const static Node NODE_1925925380160[] PROGMEM;
	const static Node NODE_1925925380400[] PROGMEM;
	const static Node NODE_1925925380560[] PROGMEM;
	const static Node NODE_1925925380480[] PROGMEM;
	const static Node NODE_1925925380720[] PROGMEM;
	const static Node NODE_1925925381840[] PROGMEM;
	const static Node NODE_1925925882592[] PROGMEM;
	const static Node NODE_1925925382160[] PROGMEM;
	const static Node NODE_1925925382240[] PROGMEM;
	const static Node NODE_1925925382000[] PROGMEM;
	const static Node NODE_1925925382400[] PROGMEM;
	const static Node NODE_1925925382560[] PROGMEM;
	const static Node NODE_1925925382880[] PROGMEM;
	const static Node NODE_1925925382960[] PROGMEM;
	const static Node NODE_1925925383360[] PROGMEM;
	const static Node NODE_1925925383440[] PROGMEM;
	const static Node NODE_1925925383840[] PROGMEM;
	const static Node NODE_1925925844608[] PROGMEM;
	const static Node NODE_1925925844848[] PROGMEM;
	const static Node NODE_1925925963152[] PROGMEM;
	const static Node NODE_1925925405056[] PROGMEM;
	const static Node NODE_1925925405136[] PROGMEM;
	const static Node NODE_1925925405296[] PROGMEM;
	const static Node NODE_1925925614432[] PROGMEM;
	const static Node NODE_1925925614752[] PROGMEM;
	const static Node NODE_1925925615552[] PROGMEM;
	const static Node NODE_1925925716672[] PROGMEM;
	const static Node NODE_1925925615632[] PROGMEM;
	const static Node NODE_1925925616112[] PROGMEM;
	const static Node NODE_1925925616672[] PROGMEM;
	const static Node NODE_1925925860592[] PROGMEM;
	const static Node NODE_1925925617072[] PROGMEM;
	const static Node NODE_1925925617392[] PROGMEM;
	const static Node NODE_1925925900752[] PROGMEM;
	const static Node NODE_1925925901232[] PROGMEM;
	const static Node NODE_1925925634912[] PROGMEM;
	const static Node NODE_1925925963952[] PROGMEM;
	const static Node NODE_1925925964112[] PROGMEM;
	const static Node NODE_1925925964032[] PROGMEM;
	const static Node NODE_1925925657792[] PROGMEM;
	const static Node NODE_1925925658512[] PROGMEM;
	const static Node NODE_1925925658352[] PROGMEM;
	const static Node NODE_1925925901312[] PROGMEM;
	const static Node NODE_1925925675792[] PROGMEM;
	const static Node NODE_1925925675952[] PROGMEM;
	const static Node NODE_1925925676512[] PROGMEM;
	const static Node NODE_1925925676592[] PROGMEM;
	const static Node NODE_1925925676912[] PROGMEM;
	const static Node NODE_1925925695712[] PROGMEM;
	const static Node NODE_1925925719472[] PROGMEM;
	const static Node NODE_1925925881472[] PROGMEM;
	const static Node NODE_1925925698272[] PROGMEM;
	const static Node NODE_1925925699312[] PROGMEM;
	const static Node NODE_1925925699472[] PROGMEM;
	const static Node NODE_1925925716032[] PROGMEM;
	const static Node NODE_1925925716512[] PROGMEM;
	const static Node NODE_1925925716592[] PROGMEM;
	const static Node NODE_1925925717072[] PROGMEM;
	const static Node NODE_1925925717232[] PROGMEM;
	const static Node NODE_1925925717392[] PROGMEM;
	const static Node NODE_1925925718832[] PROGMEM;
	const static Node NODE_1925925719312[] PROGMEM;
	const static Node NODE_1925925719552[] PROGMEM;
	const static Node NODE_1925925719712[] PROGMEM;
	const static Node NODE_1925925736672[] PROGMEM;
	const static Node NODE_1925925752896[] PROGMEM;
	const static Node NODE_1925925753056[] PROGMEM;
	const static Node NODE_1925925753456[] PROGMEM;
	const static Node NODE_1925925753136[] PROGMEM;
	const static Node NODE_1925925753536[] PROGMEM;
	const static Node NODE_1925925795216[] PROGMEM;
	const static Node NODE_1925925795536[] PROGMEM;
	const static Node NODE_1925925796896[] PROGMEM;
	const static Node NODE_1925925796976[] PROGMEM;
	const static Node NODE_1925925797296[] PROGMEM;
	const static Node NODE_1925925901392[] PROGMEM;
	const static Node NODE_1925925797616[] PROGMEM;
	const static Node NODE_1925925211808[] PROGMEM;
	const static Node NODE_1925925818832[] PROGMEM;
	const static Node NODE_1925925820512[] PROGMEM;
	const static Node NODE_1925925882992[] PROGMEM;
	const static Node NODE_1925925821072[] PROGMEM;
	const static Node NODE_1925925882352[] PROGMEM;
	const static Node NODE_1925925843248[] PROGMEM;
	const static Node NODE_1925925844288[] PROGMEM;
	const static Node NODE_1925925963472[] PROGMEM;
	const static Node NODE_1925925846128[] PROGMEM;
	const static Node NODE_1925925846208[] PROGMEM;
	const static Node NODE_1925925846608[] PROGMEM;
	const static Node NODE_1925925859712[] PROGMEM;
	const static Node NODE_1925925880912[] PROGMEM;
	const static Node NODE_1925925881952[] PROGMEM;
	const static Node NODE_1925925901632[] PROGMEM;
	const static Node NODE_1925925901792[] PROGMEM;
	const static Node NODE_1925925860192[] PROGMEM;
	const static Node NODE_1925925862832[] PROGMEM;
	const static Node NODE_1925925943392[] PROGMEM;
	const static Node NODE_1925925943552[] PROGMEM;
	const static Node NODE_1925925961872[] PROGMEM;
	const static Node NODE_1925925962272[] PROGMEM;
	const static Node NODE_1925925962512[] PROGMEM;
	const static Node NODE_1925925962832[] PROGMEM;

	const static LayeredKey aliases[][2];
	
	LayeredKey getAlias(uint8_t layer, uint8_t key);

	public:
	Compose() : currentNode(const_cast<Node*>(root)){
		//if this assertion fails, the struct in Node has to be reworked for the target architecture
		assert(sizeof(uint16_t) >= sizeof(Node*));
	}
	
	uint16_t transition(uint8_t layer, uint8_t key);
	void reset();
	
	


}; //Compose

#endif //__COMPOSE_H__