/***********************************************************************/
/******************* This file is generated by *************************/
/******************* the Compose Generator *****************************/
/***********************************************************************/

#include "Compose.gen.h"

//generated compose tree
const Node Compose::root[] PROGMEM = {
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1925925212048}},
	{{0, 0, L2, KEY_TILDE}, {(uint16_t) NODE_1925925211968}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925211888}},
	{{0, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925277920}},
	{{0, 0, L1, KEY_EQUAL}, {(uint16_t) NODE_1925925278240}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1925925278480}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1925925278720}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_1925925278640}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_1925925278960}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925279120}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1925925279280}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1925925279680}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925279840}},
	{{0, 0, L4, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925280160}},
	{{0, 0, L5, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925280080}},
	{{0, 0, L5, KEY_EQUAL}, {(uint16_t) NODE_1925925280000}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1925925280560}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) NODE_1925925280800}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925281120}},
};

const Node Compose::NODE_1925925212048[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2c6}},
	{{0, 1, L1, KEY_TILDE}, {0x302}},
	{{0, 1, L1, KEY_SPACE}, {0x5e}},
	{{0, 1, L2, KEY_D}, {0xc2}},
	{{0, 1, L2, KEY_F}, {0xca}},
	{{0, 1, L2, KEY_S}, {0xce}},
	{{0, 1, L2, KEY_G}, {0xd4}},
	{{0, 1, L2, KEY_A}, {0xdb}},
	{{0, 1, L1, KEY_D}, {0xe2}},
	{{0, 1, L1, KEY_F}, {0xea}},
	{{0, 1, L1, KEY_S}, {0xee}},
	{{0, 1, L1, KEY_G}, {0xf4}},
	{{0, 1, L1, KEY_A}, {0xfb}},
	{{0, 1, L2, KEY_R}, {0x108}},
	{{0, 1, L1, KEY_R}, {0x109}},
	{{0, 1, L2, KEY_I}, {0x11c}},
	{{0, 1, L1, KEY_I}, {0x11d}},
	{{0, 1, L2, KEY_U}, {0x124}},
	{{0, 1, L1, KEY_U}, {0x125}},
	{{0, 1, L2, KEY_SLASH}, {0x134}},
	{{0, 1, L1, KEY_SLASH}, {0x135}},
	{{0, 1, L2, KEY_H}, {0x15c}},
	{{0, 1, L1, KEY_H}, {0x15d}},
	{{0, 1, L2, KEY_T}, {0x174}},
	{{0, 1, L1, KEY_T}, {0x175}},
	{{0, 1, L2, KEY_QUOTE}, {0x176}},
	{{0, 1, L1, KEY_QUOTE}, {0x177}},
	{{0, 1, L2, KEY_B}, {0x1e90}},
	{{0, 1, L1, KEY_B}, {0x1e91}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) NODE_1925925574112}},
	{{0, 1, L1, KEY_0}, {0x2070}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925617312}},
	{{0, 1, L1, KEY_2}, {0xb2}},
	{{0, 1, L1, KEY_3}, {0xb3}},
	{{0, 1, L1, KEY_1}, {0xb9}},
	{{0, 1, L1, KEY_4}, {0x2074}},
	{{0, 1, L1, KEY_5}, {0x2075}},
	{{0, 1, L1, KEY_6}, {0x2076}},
	{{0, 1, L1, KEY_7}, {0x2077}},
	{{0, 1, L1, KEY_8}, {0x2078}},
	{{0, 1, L1, KEY_9}, {0x2079}},
	{{0, 1, L3, KEY_N}, {0x207a}},
	{{0, 1, L1, KEY_MINUS}, {0x207b}},
	{{0, 1, L3, KEY_O}, {0x207c}},
	{{0, 1, L3, KEY_J}, {0x207d}},
	{{0, 1, L3, KEY_K}, {0x207e}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1925925738032}},
	{{0, 1, L3, KEY_G}, {0x33d}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1925925753776}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925754576}},
	{{0, 1, L3, KEY_H}, {0x2c0}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_1925925777632}},
	{{0, 1, L5, KEY_QUOTE}, {0x1db7}},
	{{0, 1, L5, KEY_F}, {0x1d4b}},
	{{0, 1, L5, KEY_D}, {0x1d45}},
	{{0, 1, L3, KEY_I}, {0x20d7}},
	{{0, 1, L3, KEY_U}, {0x20d6}},
	{{0, 1, L3, KEY_MINUS}, {0x207b}},
	{{1, 1, L3, KEY_Q}, {0x22ef}},
};

const Node Compose::NODE_1925925574112[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eac}},
	{{0, 1, L1, KEY_D}, {0x1ead}},
	{{0, 1, L2, KEY_F}, {0x1ec6}},
	{{0, 1, L1, KEY_F}, {0x1ec7}},
	{{0, 1, L2, KEY_G}, {0x1ed8}},
	{{1, 1, L1, KEY_G}, {0x1ed9}},
};

const Node Compose::NODE_1925925617312[] PROGMEM = {
	{{0, 0, L3, KEY_W}, {(uint16_t) NODE_1925925617472}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1925925737952}},
	{{0, 0, L1, KEY_W}, {(uint16_t) NODE_1925925738112}},
	{{0, 0, L1, KEY_J}, {(uint16_t) NODE_1925925753616}},
	{{0, 0, L1, KEY_SLASH}, {(uint16_t) NODE_1925925753936}},
	{{0, 0, L2, KEY_J}, {(uint16_t) NODE_1925925754416}},
	{{0, 0, L1, KEY_I}, {(uint16_t) NODE_1925925754736}},
	{{0, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_1925925754976}},
	{{0, 0, L1, KEY_H}, {(uint16_t) NODE_1925925755136}},
	{{0, 0, L1, KEY_B}, {(uint16_t) NODE_1925925755216}},
	{{0, 0, L1, KEY_E}, {(uint16_t) NODE_1925925756496}},
	{{0, 0, L2, KEY_E}, {(uint16_t) NODE_1925925756656}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1925925777792}},
	{{0, 0, L2, KEY_S}, {(uint16_t) NODE_1925925778512}},
	{{0, 0, L1, KEY_F}, {(uint16_t) NODE_1925925778832}},
	{{1, 0, L1, KEY_3}, {(uint16_t) NODE_1925925778992}},
};

const Node Compose::NODE_1925925617472[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0x2071}},
	{{1, 1, L1, KEY_J}, {0x207f}},
};

const Node Compose::NODE_1925925737952[] PROGMEM = {
	{{1, 1, L3, KEY_T}, {0xa71b}},
};

const Node Compose::NODE_1925925738112[] PROGMEM = {
	{{0, 1, L3, KEY_C}, {0xa71c}},
	{{1, 1, L3, KEY_K}, {0x1db9}},
};

const Node Compose::NODE_1925925753616[] PROGMEM = {
	{{0, 1, L1, KEY_E}, {0x1daf}},
	{{1, 1, L1, KEY_I}, {0x1d51}},
};

const Node Compose::NODE_1925925753936[] PROGMEM = {
	{{1, 1, L1, KEY_J}, {0x1dae}},
};

const Node Compose::NODE_1925925754416[] PROGMEM = {
	{{1, 1, L2, KEY_J}, {0x1db0}},
};

const Node Compose::NODE_1925925754736[] PROGMEM = {
	{{1, 1, L1, KEY_I}, {0x1da2}},
};

const Node Compose::NODE_1925925754976[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x1d9e}},
};

const Node Compose::NODE_1925925755136[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x1db4}},
};

const Node Compose::NODE_1925925755216[] PROGMEM = {
	{{0, 1, L1, KEY_U}, {0x1dbe}},
	{{1, 1, L1, KEY_B}, {0x1dbe}},
};

const Node Compose::NODE_1925925756496[] PROGMEM = {
	{{1, 1, L1, KEY_E}, {0x1da9}},
};

const Node Compose::NODE_1925925756656[] PROGMEM = {
	{{1, 1, L2, KEY_E}, {0x1dab}},
};

const Node Compose::NODE_1925925777792[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0x1da4}},
	{{0, 1, L1, KEY_A}, {0x1db6}},
	{{0, 1, L1, KEY_G}, {0x1db1}},
	{{1, 1, L2, KEY_S}, {0x1da7}},
};

const Node Compose::NODE_1925925778512[] PROGMEM = {
	{{1, 1, L2, KEY_S}, {0x1da6}},
};

const Node Compose::NODE_1925925778832[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1d4a}},
};

const Node Compose::NODE_1925925778992[] PROGMEM = {
	{{1, 1, L1, KEY_3}, {0x1d9f}},
};

const Node Compose::NODE_1925925738032[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x31a}},
	{{0, 1, L2, KEY_K}, {0x2b6}},
	{{0, 1, L3, KEY_H}, {0x2c1}},
	{{0, 1, L1, KEY_K}, {0x2b4}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925756256}},
	{{0, 1, L1, KEY_U}, {0x1da3}},
	{{0, 1, L1, KEY_M}, {0x1d5a}},
	{{0, 1, L1, KEY_W}, {0x1dba}},
	{{0, 1, L1, KEY_R}, {0x1d53}},
	{{0, 1, L1, KEY_D}, {0x1d44}},
	{{1, 1, L5, KEY_D}, {0x1d9b}},
};

const Node Compose::NODE_1925925756256[] PROGMEM = {
	{{1, 0, L1, KEY_U}, {(uint16_t) NODE_1925925756736}},
};

const Node Compose::NODE_1925925756736[] PROGMEM = {
	{{1, 1, L1, KEY_J}, {0x1dad}},
};

const Node Compose::NODE_1925925753776[] PROGMEM = {
	{{0, 1, L1, KEY_M}, {0x1dac}},
	{{0, 1, L1, KEY_J}, {0x1d51}},
	{{0, 1, L1, KEY_H}, {0x1db3}},
	{{0, 1, L1, KEY_B}, {0x1dbc}},
	{{0, 1, L1, KEY_SLASH}, {0x1da8}},
	{{0, 1, L1, KEY_Q}, {0x2e0}},
	{{0, 1, L1, KEY_U}, {0x2b1}},
	{{1, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1925925756416}},
};

const Node Compose::NODE_1925925756416[] PROGMEM = {
	{{1, 1, L1, KEY_K}, {0x2b5}},
};

const Node Compose::NODE_1925925754576[] PROGMEM = {
	{{0, 1, L1, KEY_SLASH}, {0x1da1}},
	{{0, 1, L2, KEY_SLASH}, {0x1da1}},
	{{0, 1, L1, KEY_S}, {0x1da4}},
	{{0, 1, L1, KEY_A}, {0x1db6}},
	{{0, 1, L2, KEY_S}, {0x1da7}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925779632}},
};

const Node Compose::NODE_1925925779632[] PROGMEM = {
	{{1, 0, L2, KEY_S}, {(uint16_t) NODE_1925925779952}},
};

const Node Compose::NODE_1925925779952[] PROGMEM = {
	{{1, 1, L2, KEY_S}, {0x1da7}},
};

const Node Compose::NODE_1925925777632[] PROGMEM = {
	{{0, 1, L1, KEY_R}, {0x1d9d}},
	{{1, 1, L1, KEY_B}, {0x1dbd}},
};

const Node Compose::NODE_1925925211968[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2c7}},
	{{0, 1, L2, KEY_TILDE}, {0x30c}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925322480}},
	{{0, 1, L1, KEY_0}, {0x2080}},
	{{0, 1, L1, KEY_1}, {0x2081}},
	{{0, 1, L1, KEY_2}, {0x2082}},
	{{0, 1, L1, KEY_3}, {0x2083}},
	{{0, 1, L1, KEY_4}, {0x2084}},
	{{0, 1, L1, KEY_5}, {0x2085}},
	{{0, 1, L1, KEY_6}, {0x2086}},
	{{0, 1, L1, KEY_7}, {0x2087}},
	{{0, 1, L1, KEY_8}, {0x2088}},
	{{0, 1, L1, KEY_9}, {0x2089}},
	{{0, 1, L1, KEY_SPACE}, {0x2c7}},
	{{0, 1, L2, KEY_R}, {0x10c}},
	{{0, 1, L1, KEY_R}, {0x10d}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x10e}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x10f}},
	{{0, 1, L2, KEY_F}, {0x11a}},
	{{0, 1, L1, KEY_F}, {0x11b}},
	{{0, 1, L2, KEY_E}, {0x13d}},
	{{0, 1, L1, KEY_E}, {0x13e}},
	{{0, 1, L2, KEY_J}, {0x147}},
	{{0, 1, L1, KEY_J}, {0x148}},
	{{0, 1, L2, KEY_K}, {0x158}},
	{{0, 1, L1, KEY_K}, {0x159}},
	{{0, 1, L2, KEY_H}, {0x160}},
	{{0, 1, L1, KEY_H}, {0x161}},
	{{0, 1, L2, KEY_L}, {0x164}},
	{{0, 1, L1, KEY_L}, {0x165}},
	{{0, 1, L2, KEY_B}, {0x17d}},
	{{0, 1, L1, KEY_B}, {0x17e}},
	{{0, 1, L2, KEY_D}, {0x1cd}},
	{{0, 1, L1, KEY_D}, {0x1ce}},
	{{0, 1, L2, KEY_S}, {0x1cf}},
	{{0, 1, L1, KEY_S}, {0x1d0}},
	{{0, 1, L2, KEY_G}, {0x1d1}},
	{{0, 1, L1, KEY_G}, {0x1d2}},
	{{0, 1, L2, KEY_A}, {0x1d3}},
	{{0, 1, L1, KEY_A}, {0x1d4}},
	{{0, 1, L2, KEY_Z}, {0x1d9}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1925925493232}},
	{{0, 1, L1, KEY_Z}, {0x1da}},
	{{0, 1, L2, KEY_I}, {0x1e6}},
	{{0, 1, L1, KEY_I}, {0x1e7}},
	{{0, 1, L2, KEY_Y}, {0x1e8}},
	{{0, 1, L1, KEY_Y}, {0x1e9}},
	{{0, 1, L1, KEY_SLASH}, {0x1f0}},
	{{0, 1, L2, KEY_U}, {0x21e}},
	{{0, 1, L1, KEY_U}, {0x21f}},
	{{1, 1, L3, KEY_O}, {0x225a}},
};

const Node Compose::NODE_1925925322480[] PROGMEM = {
	{{0, 0, L2, KEY_SEMICOLON}, {(uint16_t) NODE_1925925343296}},
	{{0, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_1925925343456}},
	{{0, 0, L2, KEY_B}, {(uint16_t) NODE_1925925698592}},
	{{1, 0, L1, KEY_B}, {(uint16_t) NODE_1925925698672}},
};

const Node Compose::NODE_1925925343296[] PROGMEM = {
	{{0, 1, L2, KEY_B}, {0x1c4}},
	{{1, 1, L1, KEY_B}, {0x1c5}},
};

const Node Compose::NODE_1925925343456[] PROGMEM = {
	{{1, 1, L1, KEY_B}, {0x1c6}},
};

const Node Compose::NODE_1925925698592[] PROGMEM = {
	{{1, 1, L2, KEY_U}, {0x1ee}},
};

const Node Compose::NODE_1925925698672[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x1ef}},
};

const Node Compose::NODE_1925925493232[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1d9}},
	{{1, 1, L1, KEY_A}, {0x1da}},
};

const Node Compose::NODE_1925925211888[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2d8}},
	{{0, 1, L6, KEY_RIGHT_BRACE}, {0x306}},
	{{0, 1, L2, KEY_U}, {0x1e2a}},
	{{0, 1, L1, KEY_U}, {0x1e2b}},
	{{0, 1, L5, KEY_5}, {0x263f}},
	{{0, 1, L1, KEY_SPACE}, {0x2d8}},
	{{0, 1, L2, KEY_D}, {0x102}},
	{{0, 1, L1, KEY_D}, {0x103}},
	{{0, 1, L2, KEY_F}, {0x114}},
	{{0, 1, L1, KEY_F}, {0x115}},
	{{0, 1, L2, KEY_I}, {0x11e}},
	{{0, 1, L1, KEY_I}, {0x11f}},
	{{0, 1, L2, KEY_S}, {0x12c}},
	{{0, 1, L1, KEY_S}, {0x12d}},
	{{0, 1, L2, KEY_G}, {0x14e}},
	{{0, 1, L1, KEY_G}, {0x14f}},
	{{0, 1, L2, KEY_A}, {0x16c}},
	{{0, 1, L1, KEY_A}, {0x16d}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1925925531792}},
	{{1, 0, L6, KEY_TILDE}, {(uint16_t) NODE_1925925575472}},
};

const Node Compose::NODE_1925925531792[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e1c}},
	{{1, 1, L1, KEY_F}, {0x1e1d}},
};

const Node Compose::NODE_1925925575472[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eb6}},
	{{1, 1, L1, KEY_D}, {0x1eb7}},
};

const Node Compose::NODE_1925925277920[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xb4}},
	{{0, 1, L1, KEY_RIGHT_BRACE}, {0x301}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925922760640}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925320480}},
	{{0, 1, L1, KEY_SPACE}, {0xb4}},
	{{0, 1, L2, KEY_D}, {0xc1}},
	{{0, 1, L2, KEY_F}, {0xc9}},
	{{0, 1, L2, KEY_S}, {0xcd}},
	{{0, 1, L2, KEY_G}, {0xd3}},
	{{0, 1, L2, KEY_A}, {0xda}},
	{{0, 1, L2, KEY_QUOTE}, {0xdd}},
	{{0, 1, L1, KEY_D}, {0xe1}},
	{{0, 1, L1, KEY_F}, {0xe9}},
	{{0, 1, L1, KEY_S}, {0xed}},
	{{0, 1, L1, KEY_G}, {0xf3}},
	{{0, 1, L1, KEY_A}, {0xfa}},
	{{0, 1, L1, KEY_QUOTE}, {0xfd}},
	{{0, 1, L2, KEY_R}, {0x106}},
	{{0, 1, L1, KEY_R}, {0x107}},
	{{0, 1, L2, KEY_E}, {0x139}},
	{{0, 1, L1, KEY_E}, {0x13a}},
	{{0, 1, L2, KEY_J}, {0x143}},
	{{0, 1, L1, KEY_J}, {0x144}},
	{{0, 1, L2, KEY_K}, {0x154}},
	{{0, 1, L1, KEY_K}, {0x155}},
	{{0, 1, L2, KEY_H}, {0x15a}},
	{{0, 1, L1, KEY_H}, {0x15b}},
	{{0, 1, L2, KEY_B}, {0x179}},
	{{0, 1, L1, KEY_B}, {0x17a}},
	{{0, 1, L2, KEY_Z}, {0x1d7}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1925925492992}},
	{{0, 1, L1, KEY_Z}, {0x1d8}},
	{{0, 1, L2, KEY_I}, {0x1f4}},
	{{0, 1, L1, KEY_I}, {0x1f5}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_1925925511952}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1925925514032}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1925925515072}},
	{{0, 1, L2, KEY_Y}, {0x1e30}},
	{{0, 1, L1, KEY_Y}, {0x1e31}},
	{{0, 1, L2, KEY_M}, {0x1e3e}},
	{{0, 1, L1, KEY_M}, {0x1e3f}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925534592}},
	{{0, 1, L2, KEY_V}, {0x1e54}},
	{{0, 1, L1, KEY_V}, {0x1e55}},
	{{0, 1, L2, KEY_T}, {0x1e82}},
	{{0, 1, L1, KEY_T}, {0x1e83}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1925925573312}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925574352}},
	{{1, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1925925598928}},
};

const Node Compose::NODE_1925922760640[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1fe}},
	{{1, 1, L1, KEY_G}, {0x1ff}},
};

const Node Compose::NODE_1925925320480[] PROGMEM = {
	{{0, 0, L2, KEY_D}, {(uint16_t) NODE_1925925320640}},
	{{1, 0, L1, KEY_D}, {(uint16_t) NODE_1925925320720}},
};

const Node Compose::NODE_1925925320640[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x1fc}},
};

const Node Compose::NODE_1925925320720[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1fd}},
};

const Node Compose::NODE_1925925492992[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1d7}},
	{{0, 1, L1, KEY_A}, {0x1d8}},
	{{0, 1, L2, KEY_S}, {0x1e2e}},
	{{1, 1, L1, KEY_S}, {0x1e2f}},
};

const Node Compose::NODE_1925925511952[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1fa}},
	{{1, 1, L1, KEY_D}, {0x1fb}},
};

const Node Compose::NODE_1925925514032[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1e08}},
	{{1, 1, L1, KEY_R}, {0x1e09}},
};

const Node Compose::NODE_1925925515072[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e16}},
	{{0, 1, L1, KEY_F}, {0x1e17}},
	{{0, 1, L2, KEY_G}, {0x1e52}},
	{{1, 1, L1, KEY_G}, {0x1e53}},
};

const Node Compose::NODE_1925925534592[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1e4c}},
	{{0, 1, L1, KEY_G}, {0x1e4d}},
	{{0, 1, L2, KEY_A}, {0x1e78}},
	{{1, 1, L1, KEY_A}, {0x1e79}},
};

const Node Compose::NODE_1925925573312[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1ea4}},
	{{0, 1, L1, KEY_D}, {0x1ea5}},
	{{0, 1, L2, KEY_F}, {0x1ebe}},
	{{0, 1, L1, KEY_F}, {0x1ebf}},
	{{0, 1, L2, KEY_G}, {0x1ed0}},
	{{1, 1, L1, KEY_G}, {0x1ed1}},
};

const Node Compose::NODE_1925925574352[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eae}},
	{{1, 1, L1, KEY_D}, {0x1eaf}},
};

const Node Compose::NODE_1925925598928[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1eda}},
	{{0, 1, L1, KEY_G}, {0x1edb}},
	{{0, 1, L2, KEY_A}, {0x1ee8}},
	{{1, 1, L1, KEY_A}, {0x1ee9}},
};

const Node Compose::NODE_1925925278240[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x60}},
	{{0, 1, L1, KEY_EQUAL}, {0x300}},
	{{0, 1, L1, KEY_SPACE}, {0x60}},
	{{0, 1, L2, KEY_D}, {0xc0}},
	{{0, 1, L2, KEY_F}, {0xc8}},
	{{0, 1, L2, KEY_S}, {0xcc}},
	{{0, 1, L2, KEY_G}, {0xd2}},
	{{0, 1, L2, KEY_A}, {0xd9}},
	{{0, 1, L1, KEY_D}, {0xe0}},
	{{0, 1, L1, KEY_F}, {0xe8}},
	{{0, 1, L1, KEY_S}, {0xec}},
	{{0, 1, L1, KEY_G}, {0xf2}},
	{{0, 1, L1, KEY_A}, {0xf9}},
	{{0, 1, L2, KEY_Z}, {0x1db}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1925925493792}},
	{{0, 1, L1, KEY_Z}, {0x1dc}},
	{{0, 1, L2, KEY_J}, {0x1f8}},
	{{0, 1, L1, KEY_J}, {0x1f9}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1925925514752}},
	{{0, 1, L2, KEY_T}, {0x1e80}},
	{{0, 1, L1, KEY_T}, {0x1e81}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1925925573232}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925574752}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1925925599248}},
	{{0, 1, L2, KEY_QUOTE}, {0x1ef2}},
	{{1, 1, L1, KEY_QUOTE}, {0x1ef3}},
};

const Node Compose::NODE_1925925493792[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1db}},
	{{1, 1, L1, KEY_A}, {0x1dc}},
};

const Node Compose::NODE_1925925514752[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e14}},
	{{0, 1, L1, KEY_F}, {0x1e15}},
	{{0, 1, L2, KEY_G}, {0x1e50}},
	{{1, 1, L1, KEY_G}, {0x1e51}},
};

const Node Compose::NODE_1925925573232[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1ea6}},
	{{0, 1, L1, KEY_D}, {0x1ea7}},
	{{0, 1, L2, KEY_F}, {0x1ec0}},
	{{0, 1, L1, KEY_F}, {0x1ec1}},
	{{0, 1, L2, KEY_G}, {0x1ed2}},
	{{1, 1, L1, KEY_G}, {0x1ed3}},
};

const Node Compose::NODE_1925925574752[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eb0}},
	{{1, 1, L1, KEY_D}, {0x1eb1}},
};

const Node Compose::NODE_1925925599248[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1edc}},
	{{0, 1, L1, KEY_G}, {0x1edd}},
	{{0, 1, L2, KEY_A}, {0x1eea}},
	{{1, 1, L1, KEY_A}, {0x1eeb}},
};

const Node Compose::NODE_1925925278480[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xb8}},
	{{0, 1, L2, KEY_EQUAL}, {0x327}},
	{{0, 1, L2, KEY_D}, {0x104}},
	{{0, 1, L1, KEY_D}, {0x105}},
	{{0, 1, L2, KEY_F}, {0x118}},
	{{0, 1, L1, KEY_F}, {0x119}},
	{{0, 1, L2, KEY_S}, {0x12e}},
	{{0, 1, L1, KEY_S}, {0x12f}},
	{{0, 1, L2, KEY_A}, {0x172}},
	{{0, 1, L1, KEY_A}, {0x173}},
	{{0, 1, L2, KEY_G}, {0x1ea}},
	{{0, 1, L1, KEY_G}, {0x1eb}},
	{{0, 1, L1, KEY_SPACE}, {0xb8}},
	{{0, 1, L2, KEY_R}, {0xc7}},
	{{0, 1, L1, KEY_R}, {0xe7}},
	{{0, 1, L2, KEY_I}, {0x122}},
	{{0, 1, L1, KEY_I}, {0x123}},
	{{0, 1, L2, KEY_Y}, {0x136}},
	{{0, 1, L1, KEY_Y}, {0x137}},
	{{0, 1, L2, KEY_E}, {0x13b}},
	{{0, 1, L1, KEY_E}, {0x13c}},
	{{0, 1, L2, KEY_J}, {0x145}},
	{{0, 1, L1, KEY_J}, {0x146}},
	{{0, 1, L2, KEY_K}, {0x156}},
	{{0, 1, L1, KEY_K}, {0x157}},
	{{0, 1, L2, KEY_H}, {0x15e}},
	{{0, 1, L1, KEY_H}, {0x15f}},
	{{0, 1, L2, KEY_L}, {0x162}},
	{{0, 1, L1, KEY_L}, {0x163}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e10}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e11}},
	{{0, 1, L2, KEY_U}, {0x1e28}},
	{{1, 1, L1, KEY_U}, {0x1e29}},
};

const Node Compose::NODE_1925925278720[] PROGMEM = {
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1925925278800}},
	{{0, 0, L4, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925280400}},
	{{0, 1, L5, KEY_SPACE}, {0x21bb}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925281600}},
	{{0, 1, L1, KEY_SPACE}, {0x21bb}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2025}},
	{{0, 1, L3, KEY_Q}, {0x22ee}},
	{{0, 1, L5, KEY_5}, {0x2641}},
	{{0, 1, L3, KEY_R}, {0x2423}},
	{{0, 1, L3, KEYPAD_3}, {0x21cb}},
	{{0, 1, L1, KEY_D}, {0x250}},
	{{0, 1, L2, KEY_R}, {0x186}},
	{{0, 1, L1, KEY_R}, {0x254}},
	{{0, 1, L1, KEY_F}, {0x258}},
	{{0, 1, L1, KEY_U}, {0x265}},
	{{0, 1, L1, KEY_M}, {0x26f}},
	{{0, 1, L2, KEY_K}, {0x281}},
	{{0, 1, L1, KEY_K}, {0x279}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925406896}},
	{{0, 1, L2, KEY_H}, {0x1a7}},
	{{0, 1, L2, KEY_W}, {0x245}},
	{{0, 1, L1, KEY_W}, {0x28c}},
	{{0, 1, L1, KEY_T}, {0x28d}},
	{{0, 1, L1, KEY_QUOTE}, {0x28e}},
	{{0, 1, L5, KEY_E}, {0x28e}},
	{{0, 1, L1, KEY_3}, {0x190}},
	{{0, 1, L5, KEY_D}, {0x252}},
	{{0, 1, L6, KEY_T}, {0x1b1}},
	{{0, 1, L5, KEY_L}, {0x27e}},
	{{0, 1, L3, KEY_K}, {0x203f}},
	{{0, 1, L3, KEY_J}, {0x361}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_1925925738592}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1925925738832}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925739072}},
	{{0, 1, L6, KEY_V}, {0x2210}},
	{{1, 1, L3, KEY_V}, {0x2240}},
};

const Node Compose::NODE_1925925278800[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2db}},
	{{0, 1, L2, KEY_EQUAL}, {0x328}},
	{{0, 1, L1, KEY_SPACE}, {0x2db}},
	{{0, 1, L2, KEY_F}, {0x228}},
	{{1, 1, L1, KEY_F}, {0x229}},
};

const Node Compose::NODE_1925925280400[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2f5}},
	{{0, 1, L4, KEY_RIGHT_BRACE}, {0x30f}},
	{{0, 1, L2, KEY_D}, {0x200}},
	{{0, 1, L1, KEY_D}, {0x201}},
	{{0, 1, L2, KEY_F}, {0x204}},
	{{0, 1, L1, KEY_F}, {0x205}},
	{{0, 1, L2, KEY_S}, {0x208}},
	{{0, 1, L1, KEY_S}, {0x209}},
	{{0, 1, L2, KEY_G}, {0x20c}},
	{{0, 1, L1, KEY_G}, {0x20d}},
	{{0, 1, L2, KEY_K}, {0x210}},
	{{0, 1, L1, KEY_K}, {0x211}},
	{{0, 1, L2, KEY_A}, {0x214}},
	{{1, 1, L1, KEY_A}, {0x215}},
};

const Node Compose::NODE_1925925281600[] PROGMEM = {
	{{0, 1, L6, KEY_RIGHT_BRACE}, {0x311}},
	{{0, 1, L2, KEY_D}, {0x202}},
	{{0, 1, L1, KEY_D}, {0x203}},
	{{0, 1, L2, KEY_F}, {0x206}},
	{{0, 1, L1, KEY_F}, {0x207}},
	{{0, 1, L2, KEY_S}, {0x20a}},
	{{0, 1, L1, KEY_S}, {0x20b}},
	{{0, 1, L2, KEY_G}, {0x20e}},
	{{0, 1, L1, KEY_G}, {0x20f}},
	{{0, 1, L2, KEY_K}, {0x212}},
	{{0, 1, L1, KEY_K}, {0x213}},
	{{0, 1, L2, KEY_A}, {0x216}},
	{{1, 1, L1, KEY_A}, {0x217}},
};

const Node Compose::NODE_1925925406896[] PROGMEM = {
	{{0, 0, L1, KEY_K}, {(uint16_t) NODE_1925925407216}},
	{{0, 0, L1, KEY_D}, {(uint16_t) NODE_1925925407936}},
	{{0, 0, L5, KEY_D}, {(uint16_t) NODE_1925925407856}},
	{{0, 0, L1, KEY_U}, {(uint16_t) NODE_1925925408256}},
	{{0, 0, L2, KEY_B}, {(uint16_t) NODE_1925925698512}},
	{{0, 0, L1, KEY_B}, {(uint16_t) NODE_1925925698832}},
	{{0, 0, L1, KEY_S}, {(uint16_t) NODE_1925925718432}},
	{{0, 0, L3, KEY_PERIOD}, {(uint16_t) NODE_1925925737312}},
	{{0, 0, L1, KEY_H}, {(uint16_t) NODE_1925925779872}},
	{{1, 0, L1, KEY_T}, {(uint16_t) NODE_1925925964832}},
};

const Node Compose::NODE_1925925407216[] PROGMEM = {
	{{0, 1, L1, KEY_K}, {0x27a}},
	{{1, 1, L3, KEY_W}, {0x27f}},
};

const Node Compose::NODE_1925925407936[] PROGMEM = {
	{{1, 1, L1, KEY_D}, {0x252}},
};

const Node Compose::NODE_1925925407856[] PROGMEM = {
	{{1, 1, L5, KEY_D}, {0x252}},
};

const Node Compose::NODE_1925925408256[] PROGMEM = {
	{{1, 1, L1, KEY_J}, {0x270}},
};

const Node Compose::NODE_1925925698512[] PROGMEM = {
	{{1, 1, L2, KEY_B}, {0x1b8}},
};

const Node Compose::NODE_1925925698832[] PROGMEM = {
	{{1, 1, L1, KEY_B}, {0x1b9}},
};

const Node Compose::NODE_1925925718432[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x295}},
};

const Node Compose::NODE_1925925737312[] PROGMEM = {
	{{1, 1, L3, KEY_PERIOD}, {0x2cc}},
};

const Node Compose::NODE_1925925779872[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x285}},
};

const Node Compose::NODE_1925925964832[] PROGMEM = {
	{{0, 1, L3, KEY_PERIOD}, {0x2035}},
	{{1, 1, L1, KEY_3}, {0x2037}},
};

const Node Compose::NODE_1925925738592[] PROGMEM = {
	{{0, 1, L3, KEY_EQUAL}, {0x325}},
	{{0, 1, L2, KEY_D}, {0x1e00}},
	{{1, 1, L1, KEY_D}, {0x1e01}},
};

const Node Compose::NODE_1925925738832[] PROGMEM = {
	{{0, 1, L4, KEY_EQUAL}, {0x324}},
	{{0, 1, L2, KEY_A}, {0x1e72}},
	{{1, 1, L1, KEY_A}, {0x1e73}},
};

const Node Compose::NODE_1925925739072[] PROGMEM = {
	{{0, 1, L2, KEY_RIGHT_BRACE}, {0x330}},
	{{0, 1, L2, KEY_F}, {0x1e1a}},
	{{0, 1, L1, KEY_F}, {0x1e1b}},
	{{0, 1, L2, KEY_S}, {0x1e2c}},
	{{0, 1, L1, KEY_S}, {0x1e2d}},
	{{0, 1, L2, KEY_A}, {0x1e74}},
	{{1, 1, L1, KEY_A}, {0x1e75}},
};

const Node Compose::NODE_1925925278640[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2d9}},
	{{0, 1, L4, KEY_TILDE}, {0x307}},
	{{0, 1, L2, KEY_E}, {0x13f}},
	{{0, 1, L1, KEY_E}, {0x140}},
	{{0, 1, L1, KEY_SLASH}, {0x237}},
	{{0, 1, L1, KEY_SPACE}, {0x2d9}},
	{{0, 1, L2, KEY_R}, {0x10a}},
	{{0, 1, L1, KEY_R}, {0x10b}},
	{{0, 1, L2, KEY_F}, {0x116}},
	{{0, 1, L1, KEY_F}, {0x117}},
	{{0, 1, L2, KEY_I}, {0x120}},
	{{0, 1, L1, KEY_I}, {0x121}},
	{{0, 1, L2, KEY_S}, {0x130}},
	{{0, 1, L1, KEY_S}, {0x131}},
	{{0, 1, L2, KEY_B}, {0x17b}},
	{{0, 1, L1, KEY_B}, {0x17c}},
	{{0, 1, L2, KEY_D}, {0x226}},
	{{0, 1, L1, KEY_D}, {0x227}},
	{{0, 1, L2, KEY_G}, {0x22e}},
	{{0, 1, L1, KEY_G}, {0x22f}},
	{{0, 1, L2, KEY_N}, {0x1e02}},
	{{0, 1, L1, KEY_N}, {0x1e03}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e0a}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e0b}},
	{{0, 1, L2, KEY_O}, {0x1e1e}},
	{{0, 1, L1, KEY_O}, {0x1e1f}},
	{{0, 1, L2, KEY_U}, {0x1e22}},
	{{0, 1, L1, KEY_U}, {0x1e23}},
	{{0, 1, L2, KEY_M}, {0x1e40}},
	{{0, 1, L1, KEY_M}, {0x1e41}},
	{{0, 1, L2, KEY_J}, {0x1e44}},
	{{0, 1, L1, KEY_J}, {0x1e45}},
	{{0, 1, L2, KEY_V}, {0x1e56}},
	{{0, 1, L1, KEY_V}, {0x1e57}},
	{{0, 1, L2, KEY_K}, {0x1e58}},
	{{0, 1, L1, KEY_K}, {0x1e59}},
	{{0, 1, L2, KEY_H}, {0x1e60}},
	{{0, 1, L1, KEY_H}, {0x1e61}},
	{{0, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925553072}},
	{{0, 0, L2, KEY_TILDE}, {(uint16_t) NODE_1925925553312}},
	{{0, 1, L2, KEY_L}, {0x1e6a}},
	{{0, 1, L1, KEY_L}, {0x1e6b}},
	{{0, 1, L2, KEY_T}, {0x1e86}},
	{{0, 1, L1, KEY_T}, {0x1e87}},
	{{0, 1, L2, KEY_Q}, {0x1e8a}},
	{{0, 1, L1, KEY_Q}, {0x1e8b}},
	{{0, 1, L2, KEY_QUOTE}, {0x1e8e}},
	{{0, 1, L1, KEY_QUOTE}, {0x1e8f}},
	{{0, 1, L3, KEY_LEFT_BRACE}, {0x1e9b}},
	{{0, 1, L1, KEY_0}, {0x298}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925821712}},
	{{0, 1, L3, KEY_O}, {0x2250}},
	{{0, 1, L6, KEY_3}, {0x2a51}},
	{{0, 1, L6, KEY_2}, {0x2a52}},
	{{0, 1, L3, KEY_V}, {0x2a6a}},
	{{0, 1, L1, KEY_MINUS}, {0x2238}},
	{{0, 1, L3, KEY_N}, {0x2214}},
	{{0, 1, L3, KEY_G}, {0x2a30}},
	{{1, 1, L6, KEY_SEMICOLON}, {0x29ca}},
};

const Node Compose::NODE_1925925553072[] PROGMEM = {
	{{0, 1, L2, KEY_H}, {0x1e64}},
	{{1, 1, L1, KEY_H}, {0x1e65}},
};

const Node Compose::NODE_1925925553312[] PROGMEM = {
	{{0, 1, L2, KEY_H}, {0x1e66}},
	{{1, 1, L1, KEY_H}, {0x1e67}},
};

const Node Compose::NODE_1925925821712[] PROGMEM = {
	{{1, 0, L3, KEY_O}, {(uint16_t) NODE_1925925821872}},
};

const Node Compose::NODE_1925925821872[] PROGMEM = {
	{{1, 1, L3, KEY_O}, {0x2a67}},
};

const Node Compose::NODE_1925925278960[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2da}},
	{{0, 1, L3, KEY_EQUAL}, {0x30a}},
	{{0, 1, L1, KEY_SPACE}, {0xb0}},
	{{0, 1, L2, KEY_D}, {0xc5}},
	{{0, 1, L1, KEY_D}, {0xe5}},
	{{0, 1, L2, KEY_A}, {0x16e}},
	{{0, 1, L1, KEY_A}, {0x16f}},
	{{0, 1, L1, KEY_T}, {0x1e98}},
	{{0, 1, L1, KEY_QUOTE}, {0x1e99}},
	{{0, 1, L1, KEY_R}, {0x255}},
	{{0, 1, L1, KEY_B}, {0x291}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x221}},
	{{0, 1, L1, KEY_E}, {0x234}},
	{{0, 1, L1, KEY_J}, {0x235}},
	{{0, 1, L1, KEY_L}, {0x236}},
	{{0, 1, L6, KEY_S}, {0x222e}},
	{{0, 0, L1, KEY_2}, {(uint16_t) NODE_1925925819552}},
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_1925925819952}},
	{{0, 1, L3, KEY_O}, {0x2257}},
	{{1, 1, L3, KEY_N}, {0x2a22}},
};

const Node Compose::NODE_1925925819552[] PROGMEM = {
	{{1, 1, L6, KEY_S}, {0x222f}},
};

const Node Compose::NODE_1925925819952[] PROGMEM = {
	{{1, 1, L6, KEY_S}, {0x2230}},
};

const Node Compose::NODE_1925925279120[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2dc}},
	{{0, 1, L2, KEY_RIGHT_BRACE}, {0x303}},
	{{0, 1, L2, KEY_E}, {0x2c62}},
	{{0, 1, L1, KEY_E}, {0x26b}},
	{{0, 1, L1, KEY_SPACE}, {0x7e}},
	{{0, 1, L2, KEY_D}, {0xc3}},
	{{0, 1, L2, KEY_J}, {0xd1}},
	{{0, 1, L2, KEY_G}, {0xd5}},
	{{0, 1, L1, KEY_D}, {0xe3}},
	{{0, 1, L1, KEY_J}, {0xf1}},
	{{0, 1, L1, KEY_G}, {0xf5}},
	{{0, 1, L2, KEY_S}, {0x128}},
	{{0, 1, L1, KEY_S}, {0x129}},
	{{0, 1, L2, KEY_A}, {0x168}},
	{{0, 1, L1, KEY_A}, {0x169}},
	{{0, 1, L2, KEY_W}, {0x1e7c}},
	{{0, 1, L1, KEY_W}, {0x1e7d}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1925925573872}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925575232}},
	{{0, 1, L2, KEY_F}, {0x1ebc}},
	{{0, 1, L1, KEY_F}, {0x1ebd}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1925925599728}},
	{{0, 1, L2, KEY_QUOTE}, {0x1ef8}},
	{{0, 1, L1, KEY_QUOTE}, {0x1ef9}},
	{{0, 1, L3, KEY_O}, {0x2245}},
	{{0, 1, L3, KEY_V}, {0x2248}},
	{{0, 1, L1, KEY_MINUS}, {0x2243}},
	{{1, 1, L3, KEY_N}, {0x2a24}},
};

const Node Compose::NODE_1925925573872[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eaa}},
	{{0, 1, L1, KEY_D}, {0x1eab}},
	{{0, 1, L2, KEY_F}, {0x1ec4}},
	{{0, 1, L1, KEY_F}, {0x1ec5}},
	{{0, 1, L2, KEY_G}, {0x1ed6}},
	{{1, 1, L1, KEY_G}, {0x1ed7}},
};

const Node Compose::NODE_1925925575232[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eb4}},
	{{1, 1, L1, KEY_D}, {0x1eb5}},
};

const Node Compose::NODE_1925925599728[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ee0}},
	{{0, 1, L1, KEY_G}, {0x1ee1}},
	{{0, 1, L2, KEY_A}, {0x1eee}},
	{{1, 1, L1, KEY_A}, {0x1eef}},
};

const Node Compose::NODE_1925925279280[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xaf}},
	{{0, 1, L6, KEY_EQUAL}, {0x304}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1925925297264}},
	{{0, 1, L2, KEY_N}, {0x1e06}},
	{{0, 1, L1, KEY_N}, {0x1e07}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e0e}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e0f}},
	{{0, 1, L2, KEY_Y}, {0x1e34}},
	{{0, 1, L1, KEY_Y}, {0x1e35}},
	{{0, 1, L2, KEY_E}, {0x1e3a}},
	{{0, 1, L1, KEY_E}, {0x1e3b}},
	{{0, 1, L2, KEY_J}, {0x1e48}},
	{{0, 1, L1, KEY_J}, {0x1e49}},
	{{0, 1, L2, KEY_K}, {0x1e5e}},
	{{0, 1, L1, KEY_K}, {0x1e5f}},
	{{0, 1, L2, KEY_L}, {0x1e6e}},
	{{0, 1, L1, KEY_L}, {0x1e6f}},
	{{0, 1, L2, KEY_B}, {0x1e94}},
	{{0, 1, L1, KEY_B}, {0x1e95}},
	{{0, 1, L1, KEY_U}, {0x1e96}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925320160}},
	{{0, 1, L1, KEY_SPACE}, {0xaf}},
	{{0, 1, L2, KEY_D}, {0x100}},
	{{0, 1, L1, KEY_D}, {0x101}},
	{{0, 1, L2, KEY_F}, {0x112}},
	{{0, 1, L1, KEY_F}, {0x113}},
	{{0, 1, L2, KEY_S}, {0x12a}},
	{{0, 1, L1, KEY_S}, {0x12b}},
	{{0, 1, L2, KEY_G}, {0x14c}},
	{{0, 1, L1, KEY_G}, {0x14d}},
	{{0, 1, L2, KEY_A}, {0x16a}},
	{{0, 1, L1, KEY_A}, {0x16b}},
	{{0, 1, L2, KEY_Z}, {0x1d5}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1925925492432}},
	{{0, 1, L1, KEY_Z}, {0x1d6}},
	{{0, 1, L2, KEY_C}, {0x1de}},
	{{0, 1, L1, KEY_C}, {0x1df}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_1925925494352}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925512912}},
	{{0, 1, L2, KEY_QUOTE}, {0x232}},
	{{0, 1, L1, KEY_QUOTE}, {0x233}},
	{{0, 1, L2, KEY_I}, {0x1e20}},
	{{0, 1, L1, KEY_I}, {0x1e21}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) NODE_1925925533632}},
	{{0, 1, L3, KEY_V}, {0x2243}},
	{{0, 1, L3, KEY_U}, {0x2264}},
	{{0, 1, L3, KEY_I}, {0x2265}},
	{{0, 1, L6, KEY_3}, {0x22bc}},
	{{0, 1, L6, KEY_2}, {0x22bd}},
	{{0, 1, L6, KEY_S}, {0x2a1b}},
	{{1, 0, L1, KEY_V}, {(uint16_t) NODE_1925925963712}},
};

const Node Compose::NODE_1925925297264[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ec}},
	{{1, 1, L1, KEY_G}, {0x1ed}},
};

const Node Compose::NODE_1925925320160[] PROGMEM = {
	{{0, 0, L2, KEY_D}, {(uint16_t) NODE_1925925320400}},
	{{1, 0, L1, KEY_D}, {(uint16_t) NODE_1925925320240}},
};

const Node Compose::NODE_1925925320400[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x1e2}},
};

const Node Compose::NODE_1925925320240[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1e3}},
};

const Node Compose::NODE_1925925492432[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1d5}},
	{{0, 1, L1, KEY_A}, {0x1d6}},
	{{0, 1, L2, KEY_D}, {0x1de}},
	{{0, 1, L1, KEY_D}, {0x1df}},
	{{0, 1, L2, KEY_G}, {0x22a}},
	{{1, 1, L1, KEY_G}, {0x22b}},
};

const Node Compose::NODE_1925925494352[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1e0}},
	{{0, 1, L1, KEY_D}, {0x1e1}},
	{{0, 1, L2, KEY_G}, {0x230}},
	{{1, 1, L1, KEY_G}, {0x231}},
};

const Node Compose::NODE_1925925512912[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x22c}},
	{{1, 1, L1, KEY_G}, {0x22d}},
};

const Node Compose::NODE_1925925533632[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x1e38}},
	{{0, 1, L1, KEY_E}, {0x1e39}},
	{{0, 1, L2, KEY_K}, {0x1e5c}},
	{{1, 1, L1, KEY_K}, {0x1e5d}},
};

const Node Compose::NODE_1925925963712[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x210f}},
};

const Node Compose::NODE_1925925279680[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xa8}},
	{{0, 1, L4, KEY_EQUAL}, {0x308}},
	{{0, 1, L1, KEY_SPACE}, {0xa8}},
	{{0, 1, L2, KEY_D}, {0xc4}},
	{{0, 1, L2, KEY_F}, {0xcb}},
	{{0, 1, L2, KEY_S}, {0xcf}},
	{{0, 1, L2, KEY_G}, {0xd6}},
	{{0, 1, L2, KEY_A}, {0xdc}},
	{{0, 1, L1, KEY_D}, {0xe4}},
	{{0, 1, L1, KEY_F}, {0xeb}},
	{{0, 1, L1, KEY_S}, {0xef}},
	{{0, 1, L1, KEY_G}, {0xf6}},
	{{0, 1, L1, KEY_A}, {0xfc}},
	{{0, 1, L1, KEY_QUOTE}, {0xff}},
	{{0, 1, L2, KEY_QUOTE}, {0x178}},
	{{0, 1, L2, KEY_U}, {0x1e26}},
	{{0, 1, L1, KEY_U}, {0x1e27}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925534912}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1925925554032}},
	{{0, 1, L2, KEY_T}, {0x1e84}},
	{{0, 1, L1, KEY_T}, {0x1e85}},
	{{0, 1, L2, KEY_Q}, {0x1e8c}},
	{{0, 1, L1, KEY_Q}, {0x1e8d}},
	{{1, 1, L1, KEY_L}, {0x1e97}},
};

const Node Compose::NODE_1925925534912[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1e4e}},
	{{1, 1, L1, KEY_G}, {0x1e4f}},
};

const Node Compose::NODE_1925925554032[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1e7a}},
	{{1, 1, L1, KEY_A}, {0x1e7b}},
};

const Node Compose::NODE_1925925279840[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2f}},
	{{0, 1, L3, KEY_RIGHT_BRACE}, {0x337}},
	{{0, 1, L1, KEY_SPACE}, {0x2010}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x110}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x111}},
	{{0, 1, L2, KEY_U}, {0x126}},
	{{0, 1, L1, KEY_U}, {0x127}},
	{{0, 1, L2, KEY_E}, {0x141}},
	{{0, 1, L1, KEY_E}, {0x142}},
	{{0, 1, L2, KEY_G}, {0xd8}},
	{{0, 1, L1, KEY_G}, {0xf8}},
	{{0, 1, L5, KEY_4}, {0x26a6}},
	{{0, 1, L5, KEY_6}, {0x26a7}},
	{{0, 1, L3, KEY_S}, {0x2718}},
	{{0, 1, L3, KEY_A}, {0x2718}},
	{{0, 1, L4, KEY_6}, {0x20a4}},
	{{0, 1, L2, KEY_L}, {0x166}},
	{{0, 1, L1, KEY_L}, {0x167}},
	{{0, 1, L1, KEY_N}, {0x180}},
	{{0, 1, L2, KEY_S}, {0x197}},
	{{0, 1, L2, KEY_B}, {0x1b5}},
	{{0, 1, L1, KEY_B}, {0x1b6}},
	{{0, 1, L2, KEY_I}, {0x1e4}},
	{{0, 1, L1, KEY_I}, {0x1e5}},
	{{0, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925512352}},
	{{0, 1, L1, KEY_S}, {0x268}},
	{{0, 1, L2, KEY_D}, {0x23a}},
	{{0, 1, L1, KEY_D}, {0x2c65}},
	{{0, 1, L2, KEY_N}, {0x243}},
	{{0, 1, L2, KEY_R}, {0x23b}},
	{{0, 1, L1, KEY_R}, {0x23c}},
	{{0, 1, L2, KEY_F}, {0x246}},
	{{0, 1, L1, KEY_F}, {0x247}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925678032}},
	{{0, 1, L2, KEY_SLASH}, {0x25f}},
	{{0, 1, L1, KEY_SLASH}, {0x25f}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_1925925678672}},
	{{0, 1, L2, KEY_V}, {0x2c63}},
	{{0, 0, L1, KEY_V}, {(uint16_t) NODE_1925925696112}},
	{{0, 1, L2, KEY_K}, {0x24c}},
	{{0, 1, L1, KEY_K}, {0x24d}},
	{{0, 1, L1, KEY_A}, {0x289}},
	{{0, 1, L2, KEY_A}, {0x244}},
	{{0, 1, L2, KEY_QUOTE}, {0x24e}},
	{{0, 1, L1, KEY_QUOTE}, {0x24f}},
	{{0, 1, L5, KEY_E}, {0x19b}},
	{{0, 1, L5, KEY_S}, {0x1d7c}},
	{{0, 1, L5, KEY_QUOTE}, {0x1d7f}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1925925718112}},
	{{0, 1, L3, KEY_LEFT_BRACE}, {0x1e9c}},
	{{0, 1, L1, KEY_0}, {0x2205}},
	{{0, 1, L6, KEY_S}, {0x2a0f}},
	{{0, 1, L3, KEY_O}, {0x2260}},
	{{0, 1, L3, KEY_C}, {0x2224}},
	{{0, 1, L3, KEY_V}, {0x2241}},
	{{0, 1, L3, KEY_U}, {0x226e}},
	{{1, 1, L3, KEY_I}, {0x226f}},
};

const Node Compose::NODE_1925925512352[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1fe}},
	{{1, 1, L1, KEY_G}, {0x1ff}},
};

const Node Compose::NODE_1925925678032[] PROGMEM = {
	{{0, 0, L2, KEY_S}, {(uint16_t) NODE_1925925678192}},
	{{0, 0, L2, KEY_A}, {(uint16_t) NODE_1925925698032}},
	{{0, 0, L1, KEY_S}, {(uint16_t) NODE_1925925718352}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1925925882912}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1925925883152}},
	{{1, 0, L3, KEY_O}, {(uint16_t) NODE_1925925883312}},
};

const Node Compose::NODE_1925925678192[] PROGMEM = {
	{{1, 1, L2, KEY_S}, {0x1d7b}},
};

const Node Compose::NODE_1925925698032[] PROGMEM = {
	{{1, 1, L2, KEY_A}, {0x1d7e}},
};

const Node Compose::NODE_1925925718352[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x2a1}},
};

const Node Compose::NODE_1925925882912[] PROGMEM = {
	{{1, 1, L3, KEY_C}, {0x22ea}},
};

const Node Compose::NODE_1925925883152[] PROGMEM = {
	{{0, 1, L3, KEY_I}, {0x22eb}},
	{{0, 1, L1, KEY_MINUS}, {0x22ac}},
	{{1, 1, L3, KEY_O}, {0x22ad}},
};

const Node Compose::NODE_1925925883312[] PROGMEM = {
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1925925883552}},
	{{1, 0, L3, KEY_C}, {(uint16_t) NODE_1925925883472}},
};

const Node Compose::NODE_1925925883552[] PROGMEM = {
	{{1, 1, L3, KEY_C}, {0x22ec}},
};

const Node Compose::NODE_1925925883472[] PROGMEM = {
	{{1, 1, L3, KEY_I}, {0x22ed}},
};

const Node Compose::NODE_1925925678672[] PROGMEM = {
	{{1, 1, L1, KEY_SLASH}, {0x25f}},
};

const Node Compose::NODE_1925925696112[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x210f}},
};

const Node Compose::NODE_1925925718112[] PROGMEM = {
	{{0, 1, L3, KEY_H}, {0x2a2}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925718672}},
};

const Node Compose::NODE_1925925718672[] PROGMEM = {
	{{1, 0, L1, KEY_S}, {(uint16_t) NODE_1925925718912}},
};

const Node Compose::NODE_1925925718912[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x2a2}},
};

const Node Compose::NODE_1925925280160[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2dd}},
	{{0, 1, L4, KEY_RIGHT_BRACE}, {0x30b}},
	{{0, 1, L1, KEY_SPACE}, {0x2dd}},
	{{0, 1, L2, KEY_G}, {0x150}},
	{{0, 1, L1, KEY_G}, {0x151}},
	{{0, 1, L2, KEY_A}, {0x170}},
	{{1, 1, L1, KEY_A}, {0x171}},
};

const Node Compose::NODE_1925925280080[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x1fbf}},
	{{0, 1, L5, KEY_RIGHT_BRACE}, {0x313}},
	{{0, 1, L1, KEY_SPACE}, {0x1fbf}},
	{{0, 1, L2, KEY_D}, {0x1ea2}},
	{{0, 1, L1, KEY_D}, {0x1ea3}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1925925573632}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925574992}},
	{{0, 1, L2, KEY_F}, {0x1eba}},
	{{0, 1, L1, KEY_F}, {0x1ebb}},
	{{0, 1, L2, KEY_S}, {0x1ec8}},
	{{0, 1, L1, KEY_S}, {0x1ec9}},
	{{0, 1, L2, KEY_G}, {0x1ece}},
	{{0, 1, L1, KEY_G}, {0x1ecf}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1925925599488}},
	{{0, 1, L2, KEY_A}, {0x1ee6}},
	{{0, 1, L1, KEY_A}, {0x1ee7}},
	{{0, 1, L2, KEY_QUOTE}, {0x1ef6}},
	{{0, 1, L1, KEY_QUOTE}, {0x1ef7}},
	{{1, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1925925780112}},
};

const Node Compose::NODE_1925925573632[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1ea8}},
	{{0, 1, L1, KEY_D}, {0x1ea9}},
	{{0, 1, L2, KEY_F}, {0x1ec2}},
	{{0, 1, L1, KEY_F}, {0x1ec3}},
	{{0, 1, L2, KEY_G}, {0x1ed4}},
	{{1, 1, L1, KEY_G}, {0x1ed5}},
};

const Node Compose::NODE_1925925574992[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eb2}},
	{{1, 1, L1, KEY_D}, {0x1eb3}},
};

const Node Compose::NODE_1925925599488[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ede}},
	{{0, 1, L1, KEY_G}, {0x1edf}},
	{{0, 1, L2, KEY_A}, {0x1eec}},
	{{1, 1, L1, KEY_A}, {0x1eed}},
};

const Node Compose::NODE_1925925780112[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x2ae}},
};

const Node Compose::NODE_1925925280000[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x1ffe}},
	{{0, 1, L5, KEY_EQUAL}, {0x314}},
	{{0, 1, L1, KEY_SPACE}, {0x1ffe}},
	{{1, 0, L5, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925780272}},
};

const Node Compose::NODE_1925925780272[] PROGMEM = {
	{{1, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1925925780592}},
};

const Node Compose::NODE_1925925780592[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x2af}},
};

const Node Compose::NODE_1925925280560[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2de}},
	{{0, 1, L5, KEY_TILDE}, {0x2de}},
	{{0, 1, L1, KEY_SPACE}, {0x2de}},
	{{0, 1, L3, KEY_S}, {0x2714}},
	{{0, 1, L3, KEY_A}, {0x2714}},
	{{0, 1, L2, KEY_G}, {0x1a0}},
	{{0, 1, L1, KEY_G}, {0x1a1}},
	{{0, 1, L2, KEY_A}, {0x1af}},
	{{0, 1, L1, KEY_A}, {0x1b0}},
	{{0, 1, L2, KEY_N}, {0x181}},
	{{0, 1, L1, KEY_N}, {0x253}},
	{{0, 1, L2, KEY_R}, {0x187}},
	{{0, 1, L1, KEY_R}, {0x188}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x18a}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x257}},
	{{0, 1, L2, KEY_O}, {0x191}},
	{{0, 1, L1, KEY_O}, {0x192}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1925925655392}},
	{{0, 1, L2, KEY_I}, {0x193}},
	{{0, 1, L1, KEY_I}, {0x260}},
	{{0, 1, L1, KEY_U}, {0x266}},
	{{0, 1, L2, KEY_S}, {0x196}},
	{{0, 1, L1, KEY_S}, {0x269}},
	{{0, 1, L1, KEY_SLASH}, {0x29d}},
	{{0, 1, L2, KEY_Y}, {0x198}},
	{{0, 1, L1, KEY_Y}, {0x199}},
	{{0, 1, L1, KEY_E}, {0x26c}},
	{{0, 1, L2, KEY_M}, {0x2c6e}},
	{{0, 1, L1, KEY_M}, {0x271}},
	{{0, 1, L2, KEY_J}, {0x14a}},
	{{0, 1, L1, KEY_J}, {0x14b}},
	{{0, 1, L2, KEY_V}, {0x1a4}},
	{{0, 1, L1, KEY_V}, {0x1a5}},
	{{0, 1, L2, KEY_K}, {0x2c64}},
	{{0, 1, L1, KEY_K}, {0x27d}},
	{{0, 1, L1, KEY_H}, {0x282}},
	{{0, 1, L2, KEY_L}, {0x1ac}},
	{{0, 1, L1, KEY_L}, {0x1ad}},
	{{0, 1, L1, KEY_W}, {0x2c71}},
	{{0, 1, L2, KEY_T}, {0x2c72}},
	{{0, 1, L1, KEY_T}, {0x2c73}},
	{{0, 1, L2, KEY_Q}, {0x194}},
	{{0, 1, L1, KEY_Q}, {0x263}},
	{{0, 1, L2, KEY_QUOTE}, {0x1b3}},
	{{0, 1, L1, KEY_QUOTE}, {0x1b4}},
	{{0, 1, L1, KEY_B}, {0x290}},
	{{0, 1, L1, KEY_3}, {0x25d}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1925925675632}},
	{{1, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925678752}},
};

const Node Compose::NODE_1925925655392[] PROGMEM = {
	{{0, 0, L2, KEY_I}, {(uint16_t) NODE_1925925655712}},
	{{0, 0, L1, KEY_F}, {(uint16_t) NODE_1925925658272}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1925925902192}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1925925902272}},
	{{0, 0, L3, KEY_A}, {(uint16_t) NODE_1925925902352}},
	{{1, 0, L3, KEY_S}, {(uint16_t) NODE_1925925902592}},
};

const Node Compose::NODE_1925925655712[] PROGMEM = {
	{{1, 1, L2, KEY_I}, {0x29b}},
};

const Node Compose::NODE_1925925658272[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x25a}},
};

const Node Compose::NODE_1925925902192[] PROGMEM = {
	{{1, 1, L3, KEY_I}, {0x21aa}},
};

const Node Compose::NODE_1925925902272[] PROGMEM = {
	{{1, 1, L1, KEY_MINUS}, {0x21a9}},
};

const Node Compose::NODE_1925925902352[] PROGMEM = {
	{{0, 1, L3, KEY_T}, {0x2923}},
	{{1, 1, L1, KEY_W}, {0x2925}},
};

const Node Compose::NODE_1925925902592[] PROGMEM = {
	{{0, 1, L3, KEY_T}, {0x2924}},
	{{1, 1, L1, KEY_W}, {0x2926}},
};

const Node Compose::NODE_1925925675632[] PROGMEM = {
	{{1, 1, L1, KEY_K}, {0x27b}},
};

const Node Compose::NODE_1925925678752[] PROGMEM = {
	{{1, 1, L2, KEY_SLASH}, {0x284}},
};

const Node Compose::NODE_1925925280800[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2e}},
	{{0, 1, L6, KEY_TILDE}, {0x323}},
	{{0, 1, L1, KEY_SPACE}, {0x2e}},
	{{0, 1, L2, KEY_N}, {0x1e04}},
	{{0, 1, L1, KEY_N}, {0x1e05}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e0c}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e0d}},
	{{0, 1, L2, KEY_U}, {0x1e24}},
	{{0, 1, L1, KEY_U}, {0x1e25}},
	{{0, 1, L2, KEY_Y}, {0x1e32}},
	{{0, 1, L1, KEY_Y}, {0x1e33}},
	{{0, 1, L2, KEY_E}, {0x1e36}},
	{{0, 1, L1, KEY_E}, {0x1e37}},
	{{0, 1, L2, KEY_M}, {0x1e42}},
	{{0, 1, L1, KEY_M}, {0x1e43}},
	{{0, 1, L2, KEY_J}, {0x1e46}},
	{{0, 1, L1, KEY_J}, {0x1e47}},
	{{0, 1, L2, KEY_K}, {0x1e5a}},
	{{0, 1, L1, KEY_K}, {0x1e5b}},
	{{0, 1, L2, KEY_H}, {0x1e62}},
	{{0, 1, L1, KEY_H}, {0x1e63}},
	{{0, 1, L2, KEY_L}, {0x1e6c}},
	{{0, 1, L1, KEY_L}, {0x1e6d}},
	{{0, 1, L2, KEY_W}, {0x1e7e}},
	{{0, 1, L1, KEY_W}, {0x1e7f}},
	{{0, 1, L2, KEY_T}, {0x1e88}},
	{{0, 1, L1, KEY_T}, {0x1e89}},
	{{0, 1, L2, KEY_B}, {0x1e92}},
	{{0, 1, L1, KEY_B}, {0x1e93}},
	{{0, 1, L2, KEY_D}, {0x1ea0}},
	{{0, 1, L1, KEY_D}, {0x1ea1}},
	{{0, 1, L2, KEY_F}, {0x1eb8}},
	{{0, 1, L1, KEY_F}, {0x1eb9}},
	{{0, 1, L2, KEY_S}, {0x1eca}},
	{{0, 1, L1, KEY_S}, {0x1ecb}},
	{{0, 1, L2, KEY_G}, {0x1ecc}},
	{{0, 1, L1, KEY_G}, {0x1ecd}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1925925599968}},
	{{0, 1, L2, KEY_A}, {0x1ee4}},
	{{0, 1, L1, KEY_A}, {0x1ee5}},
	{{0, 1, L2, KEY_QUOTE}, {0x1ef4}},
	{{0, 1, L1, KEY_QUOTE}, {0x1ef5}},
	{{0, 1, L3, KEY_O}, {0x2a66}},
	{{1, 1, L6, KEY_3}, {0x27d1}},
};

const Node Compose::NODE_1925925599968[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ee2}},
	{{0, 1, L1, KEY_G}, {0x1ee3}},
	{{0, 1, L2, KEY_A}, {0x1ef0}},
	{{1, 1, L1, KEY_A}, {0x1ef1}},
};

const Node Compose::NODE_1925925281120[] PROGMEM = {
	{{0, 0, L1, KEY_G}, {(uint16_t) NODE_1925925281200}},
	{{0, 0, L3, KEY_Q}, {(uint16_t) NODE_1925925280960}},
	{{0, 0, L3, KEY_W}, {(uint16_t) NODE_1925925295424}},
	{{0, 0, L3, KEY_0}, {(uint16_t) NODE_1925925295104}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1925922759760}},
	{{0, 0, L2, KEY_H}, {(uint16_t) NODE_1925925192304}},
	{{0, 0, L1, KEY_H}, {(uint16_t) NODE_1925925192144}},
	{{0, 0, L2, KEY_L}, {(uint16_t) NODE_1925925192064}},
	{{0, 0, L1, KEY_L}, {(uint16_t) NODE_1925925191744}},
	{{0, 0, L2, KEY_F}, {(uint16_t) NODE_1925925318800}},
	{{0, 0, L2, KEY_E}, {(uint16_t) NODE_1925925318960}},
	{{0, 0, L1, KEY_E}, {(uint16_t) NODE_1925925319040}},
	{{0, 0, L1, KEY_S}, {(uint16_t) NODE_1925925319840}},
	{{0, 0, L2, KEY_S}, {(uint16_t) NODE_1925925319760}},
	{{0, 0, L1, KEY_B}, {(uint16_t) NODE_1925925320880}},
	{{0, 0, L1, KEY_O}, {(uint16_t) NODE_1925925321200}},
	{{0, 0, L2, KEY_O}, {(uint16_t) NODE_1925925321520}},
	{{0, 0, L3, KEY_LEFT_BRACE}, {(uint16_t) NODE_1925925321760}},
	{{0, 0, L2, KEY_SEMICOLON}, {(uint16_t) NODE_1925925322160}},
	{{0, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_1925925322400}},
	{{0, 0, L2, KEY_J}, {(uint16_t) NODE_1925925343856}},
	{{0, 0, L1, KEY_J}, {(uint16_t) NODE_1925925344096}},
	{{0, 0, L1, KEY_2}, {(uint16_t) NODE_1925925345216}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) NODE_1925925344336}},
	{{0, 0, L3, KEY_H}, {(uint16_t) NODE_1925925345456}},
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_1925925345776}},
	{{0, 0, L2, KEYPAD_9}, {(uint16_t) NODE_1925925346416}},
	{{0, 0, L5, KEY_SPACE}, {(uint16_t) NODE_1925925346896}},
	{{0, 0, L1, KEY_7}, {(uint16_t) NODE_1925925347136}},
	{{0, 0, L2, KEY_K}, {(uint16_t) NODE_1925925347056}},
	{{0, 0, L1, KEY_K}, {(uint16_t) NODE_1925925356624}},
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_1925925358064}},
	{{0, 0, L1, KEY_4}, {(uint16_t) NODE_1925925358144}},
	{{0, 0, L1, KEY_5}, {(uint16_t) NODE_1925925358464}},
	{{0, 0, L3, KEY_SEMICOLON}, {(uint16_t) NODE_1925925380160}},
	{{0, 0, L1, KEY_R}, {(uint16_t) NODE_1925925380400}},
	{{0, 0, L5, KEY_5}, {(uint16_t) NODE_1925925380480}},
	{{0, 0, L5, KEY_4}, {(uint16_t) NODE_1925925380720}},
	{{0, 1, L1, KEY_TAB}, {0x266b}},
	{{0, 1, L3, KEY_TAB}, {0x266b}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1925925381840}},
	{{0, 0, L2, KEY_R}, {(uint16_t) NODE_1925925382160}},
	{{0, 0, L3, KEY_E}, {(uint16_t) NODE_1925925382000}},
	{{0, 0, L6, KEYPAD_0}, {(uint16_t) NODE_1925925382400}},
	{{0, 0, L2, KEYPAD_7}, {(uint16_t) NODE_1925925382560}},
	{{0, 0, L2, KEYPAD_8}, {(uint16_t) NODE_1925925382880}},
	{{0, 0, L6, KEY_SEMICOLON}, {(uint16_t) NODE_1925925382960}},
	{{0, 0, L2, KEYPAD_0}, {(uint16_t) NODE_1925925383360}},
	{{0, 0, L1, KEY_V}, {(uint16_t) NODE_1925925383440}},
	{{0, 0, L1, KEY_PERIOD}, {(uint16_t) NODE_1925925405056}},
	{{0, 0, L2, KEY_PERIOD}, {(uint16_t) NODE_1925925405296}},
	{{0, 0, L3, KEY_N}, {(uint16_t) NODE_1925925614432}},
	{{0, 0, L2, KEY_V}, {(uint16_t) NODE_1925925614752}},
	{{0, 0, L2, KEY_G}, {(uint16_t) NODE_1925925615552}},
	{{0, 0, L1, KEY_D}, {(uint16_t) NODE_1925925615632}},
	{{0, 0, L2, KEY_D}, {(uint16_t) NODE_1925925616112}},
	{{0, 0, L1, KEY_0}, {(uint16_t) NODE_1925925616672}},
	{{0, 0, L3, KEY_T}, {(uint16_t) NODE_1925925617072}},
	{{0, 0, L1, KEY_M}, {(uint16_t) NODE_1925925634912}},
	{{0, 0, L5, KEY_I}, {(uint16_t) NODE_1925925657792}},
	{{0, 0, L2, KEY_W}, {(uint16_t) NODE_1925925658512}},
	{{0, 0, L1, KEY_W}, {(uint16_t) NODE_1925925658352}},
	{{0, 0, L1, KEY_SLASH}, {(uint16_t) NODE_1925925675792}},
	{{0, 0, L2, KEY_SLASH}, {(uint16_t) NODE_1925925675952}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1925925676512}},
	{{0, 0, L3, KEY_S}, {(uint16_t) NODE_1925925676912}},
	{{0, 0, L3, KEY_O}, {(uint16_t) NODE_1925925695712}},
	{{0, 0, L2, KEY_B}, {(uint16_t) NODE_1925925698272}},
	{{0, 0, L2, KEY_N}, {(uint16_t) NODE_1925925699312}},
	{{0, 0, L2, KEY_I}, {(uint16_t) NODE_1925925699472}},
	{{0, 0, L2, KEY_U}, {(uint16_t) NODE_1925925716032}},
	{{0, 0, L2, KEY_QUOTE}, {(uint16_t) NODE_1925925716512}},
	{{0, 0, L5, KEY_D}, {(uint16_t) NODE_1925925716592}},
	{{0, 0, L5, KEY_F}, {(uint16_t) NODE_1925925717072}},
	{{0, 0, L5, KEY_P}, {(uint16_t) NODE_1925925717232}},
	{{0, 0, L5, KEY_QUOTE}, {(uint16_t) NODE_1925925717392}},
	{{0, 0, L1, KEY_I}, {(uint16_t) NODE_1925925718832}},
	{{0, 0, L3, KEY_J}, {(uint16_t) NODE_1925925719312}},
	{{0, 0, L1, KEY_Q}, {(uint16_t) NODE_1925925719712}},
	{{0, 0, L3, KEY_PERIOD}, {(uint16_t) NODE_1925925736672}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1925925752896}},
	{{0, 0, L1, KEY_EQUAL}, {(uint16_t) NODE_1925925753056}},
	{{0, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925753136}},
	{{0, 0, L5, KEY_G}, {(uint16_t) NODE_1925925795216}},
	{{0, 0, L2, KEY_Q}, {(uint16_t) NODE_1925925795536}},
	{{0, 0, L1, KEY_U}, {(uint16_t) NODE_1925925796896}},
	{{0, 0, L2, KEY_T}, {(uint16_t) NODE_1925925796976}},
	{{0, 0, L1, KEY_T}, {(uint16_t) NODE_1925925797296}},
	{{0, 0, L1, KEY_QUOTE}, {(uint16_t) NODE_1925925797616}},
	{{0, 0, L6, KEY_W}, {(uint16_t) NODE_1925925211808}},
	{{0, 0, L6, KEY_S}, {(uint16_t) NODE_1925925818832}},
	{{0, 0, L3, KEY_I}, {(uint16_t) NODE_1925925820512}},
	{{0, 0, L3, KEY_V}, {(uint16_t) NODE_1925925821072}},
	{{0, 0, L2, KEY_1}, {(uint16_t) NODE_1925925843248}},
	{{0, 0, L3, KEY_MINUS}, {(uint16_t) NODE_1925925844288}},
	{{0, 0, L6, KEY_2}, {(uint16_t) NODE_1925925846128}},
	{{0, 0, L6, KEY_3}, {(uint16_t) NODE_1925925846208}},
	{{0, 0, L6, KEY_V}, {(uint16_t) NODE_1925925846608}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1925925859712}},
	{{0, 0, L3, KEY_A}, {(uint16_t) NODE_1925925860192}},
	{{0, 0, L3, KEY_G}, {(uint16_t) NODE_1925925862832}},
	{{0, 0, L1, KEY_F}, {(uint16_t) NODE_1925925943392}},
	{{0, 0, L3, KEY_K}, {(uint16_t) NODE_1925925961872}},
	{{0, 0, L3, KEY_R}, {(uint16_t) NODE_1925925962272}},
	{{0, 0, L3, KEY_D}, {(uint16_t) NODE_1925925962512}},
	{{1, 0, L3, KEY_F}, {(uint16_t) NODE_1925925962832}},
};

const Node Compose::NODE_1925925281200[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x25cc}},
	{{0, 0, L1, KEY_V}, {(uint16_t) NODE_1925925383920}},
	{{0, 1, L1, KEY_F}, {0x153}},
	{{0, 1, L6, KEY_S}, {0x222e}},
	{{0, 0, L1, KEY_2}, {(uint16_t) NODE_1925925819792}},
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_1925925820112}},
	{{0, 1, L3, KEY_N}, {0x2295}},
	{{0, 1, L1, KEY_MINUS}, {0x2296}},
	{{0, 1, L3, KEY_MINUS}, {0x2296}},
	{{0, 1, L3, KEY_G}, {0x2297}},
	{{0, 1, L3, KEY_S}, {0x2298}},
	{{0, 1, L1, KEY_PERIOD}, {0x2299}},
	{{0, 1, L2, KEY_1}, {0x229a}},
	{{0, 1, L3, KEY_O}, {0x229c}},
	{{0, 1, L3, KEY_U}, {0x29c0}},
	{{1, 1, L3, KEY_I}, {0x29c1}},
};

const Node Compose::NODE_1925925383920[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0x2325}},
};

const Node Compose::NODE_1925925819792[] PROGMEM = {
	{{1, 1, L6, KEY_S}, {0x222f}},
};

const Node Compose::NODE_1925925820112[] PROGMEM = {
	{{1, 1, L6, KEY_S}, {0x2230}},
};

const Node Compose::NODE_1925925280960[] PROGMEM = {
	{{0, 1, L1, KEY_G}, {0x25cc}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1925925346816}},
	{{0, 1, L6, KEY_3}, {0x2234}},
	{{0, 1, L6, KEY_2}, {0x2235}},
	{{0, 0, L1, KEY_W}, {(uint16_t) NODE_1925925903072}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1925925903152}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1925925903312}},
	{{0, 1, L3, KEY_S}, {0x22f0}},
	{{1, 1, L3, KEY_A}, {0x22f1}},
};

const Node Compose::NODE_1925925346816[] PROGMEM = {
	{{1, 1, L3, KEY_T}, {0x21e1}},
};

const Node Compose::NODE_1925925903072[] PROGMEM = {
	{{1, 1, L3, KEY_C}, {0x21e3}},
};

const Node Compose::NODE_1925925903152[] PROGMEM = {
	{{1, 1, L3, KEY_I}, {0x21e2}},
};

const Node Compose::NODE_1925925903312[] PROGMEM = {
	{{1, 1, L1, KEY_MINUS}, {0x21e0}},
};

const Node Compose::NODE_1925925295424[] PROGMEM = {
	{{0, 1, L3, KEY_W}, {0x332}},
	{{0, 1, L1, KEY_0}, {0x2080}},
	{{0, 1, L1, KEY_1}, {0x2081}},
	{{0, 1, L1, KEY_2}, {0x2082}},
	{{0, 1, L1, KEY_3}, {0x2083}},
	{{0, 1, L1, KEY_4}, {0x2084}},
	{{0, 1, L1, KEY_5}, {0x2085}},
	{{0, 1, L1, KEY_6}, {0x2086}},
	{{0, 1, L1, KEY_7}, {0x2087}},
	{{0, 1, L1, KEY_8}, {0x2088}},
	{{0, 1, L1, KEY_9}, {0x2089}},
	{{0, 1, L3, KEY_N}, {0x208a}},
	{{0, 1, L3, KEY_O}, {0x208c}},
	{{0, 1, L3, KEY_J}, {0x208d}},
	{{0, 1, L3, KEY_K}, {0x208e}},
	{{0, 1, L3, KEY_PERIOD}, {0x2cc}},
	{{0, 1, L3, KEY_EQUAL}, {0x325}},
	{{0, 1, L4, KEY_EQUAL}, {0x324}},
	{{0, 1, L2, KEY_RIGHT_BRACE}, {0x330}},
	{{0, 1, L6, KEY_RIGHT_BRACE}, {0x32f}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1925925739392}},
	{{0, 1, L2, KEY_TILDE}, {0x32c}},
	{{0, 1, L1, KEY_M}, {0x33c}},
	{{0, 1, L3, KEY_C}, {0x329}},
	{{0, 1, L6, KEY_EQUAL}, {0x331}},
	{{0, 1, L1, KEY_R}, {0x31c}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1925925740192}},
	{{0, 1, L6, KEYPAD_0}, {0x33b}},
	{{0, 1, L3, KEY_E}, {0x230a}},
	{{0, 1, L3, KEY_R}, {0x230b}},
	{{0, 1, L6, KEY_S}, {0x2a1c}},
	{{0, 1, L3, KEY_G}, {0x2a31}},
	{{0, 1, L1, KEY_MINUS}, {0x208b}},
	{{0, 1, L3, KEY_MINUS}, {0x208b}},
	{{0, 1, L1, KEY_D}, {0x2090}},
	{{0, 1, L1, KEY_F}, {0x2091}},
	{{0, 1, L1, KEY_U}, {0x2095}},
	{{0, 1, L1, KEY_S}, {0x1d62}},
	{{0, 1, L1, KEY_SLASH}, {0x2c7c}},
	{{0, 1, L1, KEY_Y}, {0x2096}},
	{{0, 1, L1, KEY_E}, {0x2097}},
	{{0, 1, L1, KEY_J}, {0x2099}},
	{{0, 1, L1, KEY_G}, {0x2092}},
	{{0, 1, L1, KEY_V}, {0x209a}},
	{{0, 1, L1, KEY_K}, {0x1d63}},
	{{0, 1, L1, KEY_H}, {0x209b}},
	{{0, 1, L1, KEY_L}, {0x209c}},
	{{0, 1, L1, KEY_A}, {0x1d64}},
	{{0, 1, L1, KEY_W}, {0x1d65}},
	{{0, 1, L1, KEY_Q}, {0x2093}},
	{{0, 1, L5, KEY_N}, {0x1d66}},
	{{0, 1, L5, KEY_I}, {0x1d67}},
	{{1, 1, L5, KEY_P}, {0x1d69}},
};

const Node Compose::NODE_1925925739392[] PROGMEM = {
	{{0, 1, L1, KEY_TILDE}, {0x32d}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e12}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e13}},
	{{0, 1, L2, KEY_E}, {0x1e3c}},
	{{0, 1, L1, KEY_E}, {0x1e3d}},
	{{0, 1, L2, KEY_J}, {0x1e4a}},
	{{0, 1, L1, KEY_J}, {0x1e4b}},
	{{0, 1, L2, KEY_L}, {0x1e70}},
	{{0, 1, L1, KEY_L}, {0x1e71}},
	{{0, 1, L2, KEY_F}, {0x1e18}},
	{{0, 1, L1, KEY_F}, {0x1e19}},
	{{0, 1, L2, KEY_A}, {0x1e76}},
	{{1, 1, L1, KEY_A}, {0x1e77}},
};

const Node Compose::NODE_1925925740192[] PROGMEM = {
	{{0, 1, L1, KEY_R}, {0x339}},
	{{0, 1, L3, KEY_R}, {0x33a}},
	{{1, 1, L3, KEY_E}, {0x32a}},
};

const Node Compose::NODE_1925925295104[] PROGMEM = {
	{{0, 1, L3, KEY_0}, {0x2bc}},
	{{1, 1, L1, KEY_J}, {0x149}},
};

const Node Compose::NODE_1925922759760[] PROGMEM = {
	{{0, 1, L2, KEY_U}, {0x126}},
	{{0, 1, L1, KEY_U}, {0x127}},
	{{0, 1, L4, KEY_6}, {0x20a4}},
	{{0, 1, L3, KEY_N}, {0xb1}},
	{{0, 1, L3, KEY_SEMICOLON}, {0xf7}},
	{{0, 1, L2, KEY_N}, {0x243}},
	{{0, 1, L2, KEY_S}, {0x197}},
	{{0, 1, L2, KEY_SLASH}, {0x248}},
	{{0, 1, L1, KEY_SLASH}, {0x249}},
	{{0, 1, L2, KEY_E}, {0x23d}},
	{{0, 1, L1, KEY_E}, {0x19a}},
	{{0, 1, L1, KEY_G}, {0x275}},
	{{0, 1, L2, KEY_G}, {0x19f}},
	{{0, 1, L2, KEY_V}, {0x2c63}},
	{{0, 0, L1, KEY_V}, {(uint16_t) NODE_1925925696352}},
	{{0, 1, L2, KEY_K}, {0x24c}},
	{{0, 1, L1, KEY_K}, {0x24d}},
	{{0, 1, L1, KEY_A}, {0x289}},
	{{0, 1, L2, KEY_A}, {0x244}},
	{{0, 1, L2, KEY_QUOTE}, {0x24e}},
	{{0, 1, L1, KEY_QUOTE}, {0x24f}},
	{{0, 1, L1, KEY_2}, {0x1bb}},
	{{0, 1, L5, KEY_S}, {0x1d7c}},
	{{0, 1, L5, KEY_QUOTE}, {0x1d7f}},
	{{0, 1, L3, KEY_C}, {0x22a3}},
	{{0, 1, L6, KEY_SEMICOLON}, {0x2a3a}},
	{{0, 1, L6, KEY_S}, {0x2a0d}},
	{{0, 1, L3, KEY_I}, {0x2192}},
	{{1, 1, L3, KEY_U}, {0x2919}},
};

const Node Compose::NODE_1925925696352[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x210f}},
};

const Node Compose::NODE_1925925192304[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x218}},
	{{0, 1, L2, KEY_H}, {0x1e9e}},
	{{1, 1, L2, KEY_U}, {0x1a9}},
};

const Node Compose::NODE_1925925192144[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x219}},
	{{0, 1, L1, KEY_L}, {0xfb06}},
	{{0, 1, L1, KEY_H}, {0xdf}},
	{{0, 1, L1, KEY_U}, {0x283}},
	{{0, 0, L1, KEY_A}, {(uint16_t) NODE_1925925844448}},
	{{1, 0, L1, KEY_R}, {(uint16_t) NODE_1925925942752}},
};

const Node Compose::NODE_1925925844448[] PROGMEM = {
	{{1, 1, L1, KEY_M}, {0x2211}},
};

const Node Compose::NODE_1925925942752[] PROGMEM = {
	{{0, 1, L1, KEY_I}, {0x210a}},
	{{0, 1, L2, KEY_U}, {0x210b}},
	{{0, 1, L2, KEY_S}, {0x2110}},
	{{0, 1, L2, KEY_E}, {0x2112}},
	{{0, 1, L1, KEY_E}, {0x2113}},
	{{0, 1, L2, KEY_V}, {0x2118}},
	{{0, 1, L2, KEY_K}, {0x211b}},
	{{0, 1, L2, KEY_N}, {0x212c}},
	{{0, 1, L1, KEY_F}, {0x212f}},
	{{0, 1, L2, KEY_F}, {0x2130}},
	{{0, 1, L2, KEY_O}, {0x2131}},
	{{0, 1, L2, KEY_M}, {0x2133}},
	{{1, 1, L1, KEY_G}, {0x2134}},
};

const Node Compose::NODE_1925925192064[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x21a}},
	{{0, 1, L1, KEY_E}, {0x1ae}},
	{{1, 1, L2, KEY_E}, {0x1ae}},
};

const Node Compose::NODE_1925925191744[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x21b}},
	{{0, 1, L1, KEY_M}, {0x2122}},
	{{0, 1, L1, KEY_E}, {0x288}},
	{{0, 1, L1, KEY_5}, {0x2e5}},
	{{0, 1, L1, KEY_4}, {0x2e6}},
	{{0, 1, L1, KEY_3}, {0x2e7}},
	{{0, 1, L1, KEY_2}, {0x2e8}},
	{{1, 1, L1, KEY_1}, {0x2e9}},
};

const Node Compose::NODE_1925925318800[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x18f}},
};

const Node Compose::NODE_1925925318960[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x13f}},
	{{0, 1, L2, KEY_SLASH}, {0x1c7}},
	{{0, 1, L1, KEY_SLASH}, {0x1c8}},
	{{1, 1, L2, KEY_E}, {0x29f}},
};

const Node Compose::NODE_1925925319040[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x140}},
	{{0, 1, L1, KEY_SLASH}, {0x1c9}},
	{{0, 1, L1, KEY_E}, {0x26d}},
	{{1, 1, L1, KEY_B}, {0x26e}},
};

const Node Compose::NODE_1925925319840[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0x131}},
	{{0, 1, L1, KEY_SLASH}, {0x133}},
	{{0, 1, L3, KEY_H}, {0x294}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1925925719952}},
	{{0, 1, L3, KEY_Y}, {0x1c3}},
	{{0, 1, L3, KEY_N}, {0x31f}},
	{{0, 1, L1, KEY_MINUS}, {0x320}},
	{{0, 0, L1, KEY_J}, {(uint16_t) NODE_1925925844208}},
	{{1, 1, L1, KEY_M}, {0x2111}},
};

const Node Compose::NODE_1925925719952[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x1c0}},
	{{1, 1, L3, KEY_C}, {0x1c1}},
};

const Node Compose::NODE_1925925844208[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0x222b}},
};

const Node Compose::NODE_1925925319760[] PROGMEM = {
	{{0, 1, L2, KEY_S}, {0x130}},
	{{0, 1, L2, KEY_SLASH}, {0x132}},
	{{0, 1, L1, KEY_SLASH}, {0x132}},
	{{1, 1, L1, KEY_M}, {0x2111}},
};

const Node Compose::NODE_1925925320880[] PROGMEM = {
	{{0, 1, L1, KEY_U}, {0x292}},
	{{1, 1, L1, KEY_B}, {0x292}},
};

const Node Compose::NODE_1925925321200[] PROGMEM = {
	{{0, 1, L1, KEY_O}, {0xfb00}},
	{{0, 1, L1, KEY_S}, {0xfb01}},
	{{1, 1, L1, KEY_E}, {0xfb02}},
};

const Node Compose::NODE_1925925321520[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0xfb03}},
	{{1, 1, L1, KEY_E}, {0xfb04}},
};

const Node Compose::NODE_1925925321760[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0xfb05}},
};

const Node Compose::NODE_1925925322160[] PROGMEM = {
	{{0, 1, L2, KEY_B}, {0x1f1}},
	{{0, 1, L1, KEY_B}, {0x1f2}},
	{{0, 1, L1, KEY_E}, {0x189}},
	{{1, 1, L2, KEY_E}, {0x189}},
};

const Node Compose::NODE_1925925322400[] PROGMEM = {
	{{0, 1, L1, KEY_B}, {0x1f3}},
	{{0, 0, L1, KEY_D}, {(uint16_t) NODE_1925925384080}},
	{{1, 1, L1, KEY_E}, {0x256}},
};

const Node Compose::NODE_1925925384080[] PROGMEM = {
	{{1, 1, L1, KEY_I}, {0x2020}},
};

const Node Compose::NODE_1925925343856[] PROGMEM = {
	{{0, 1, L2, KEY_SLASH}, {0x1ca}},
	{{0, 1, L1, KEY_SLASH}, {0x1cb}},
	{{0, 1, L2, KEY_F}, {0x18e}},
	{{0, 1, L2, KEY_J}, {0x274}},
	{{1, 1, L3, KEY_C}, {0x220}},
};

const Node Compose::NODE_1925925344096[] PROGMEM = {
	{{0, 1, L1, KEY_SLASH}, {0x1cc}},
	{{0, 1, L1, KEY_F}, {0x1dd}},
	{{0, 1, L1, KEY_E}, {0x273}},
	{{1, 1, L3, KEY_C}, {0x19e}},
};

const Node Compose::NODE_1925925345216[] PROGMEM = {
	{{0, 1, L3, KEY_Y}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2047}},
	{{0, 1, L1, KEY_3}, {0x2154}},
	{{0, 1, L1, KEY_5}, {0x2156}},
	{{0, 1, L3, KEY_T}, {0xb2}},
	{{0, 1, L6, KEY_S}, {0x222c}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2237}},
	{{0, 1, L3, KEY_I}, {0x226b}},
	{{0, 1, L3, KEY_U}, {0x226a}},
	{{1, 1, L3, KEY_O}, {0x2a75}},
};

const Node Compose::NODE_1925925344336[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2049}},
	{{0, 1, L6, KEY_SEMICOLON}, {0x26a0}},
	{{1, 1, L3, KEY_Y}, {0xa1}},
};

const Node Compose::NODE_1925925345456[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x2047}},
	{{0, 1, L3, KEY_Y}, {0x2048}},
	{{0, 1, L3, KEY_H}, {0xbf}},
	{{0, 1, L3, KEY_O}, {0x225f}},
	{{0, 1, L3, KEY_U}, {0x2a7b}},
	{{1, 1, L3, KEY_I}, {0x2a7c}},
};

const Node Compose::NODE_1925925345776[] PROGMEM = {
	{{0, 0, L3, KEY_H}, {(uint16_t) NODE_1925925345936}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) NODE_1925925345856}},
	{{0, 0, L4, KEY_H}, {(uint16_t) NODE_1925925346096}},
	{{0, 0, L4, KEY_Y}, {(uint16_t) NODE_1925925346256}},
	{{0, 1, L1, KEY_3}, {0x2153}},
	{{0, 1, L1, KEY_5}, {0x2155}},
	{{0, 1, L1, KEY_6}, {0x2159}},
	{{0, 1, L1, KEY_8}, {0x215b}},
	{{0, 1, L3, KEY_S}, {0x215f}},
	{{0, 1, L1, KEY_4}, {0xbc}},
	{{0, 1, L1, KEY_2}, {0xbd}},
	{{0, 1, L1, KEY_7}, {0x2150}},
	{{0, 1, L1, KEY_9}, {0x2151}},
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_1925925616432}},
	{{1, 1, L3, KEY_T}, {0xb9}},
};

const Node Compose::NODE_1925925345936[] PROGMEM = {
	{{1, 1, L3, KEY_Y}, {0x203d}},
};

const Node Compose::NODE_1925925345856[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x203d}},
};

const Node Compose::NODE_1925925346096[] PROGMEM = {
	{{1, 1, L4, KEY_Y}, {0x2e18}},
};

const Node Compose::NODE_1925925346256[] PROGMEM = {
	{{1, 1, L4, KEY_H}, {0x2e18}},
};

const Node Compose::NODE_1925925616432[] PROGMEM = {
	{{1, 1, L1, KEY_0}, {0x2152}},
};

const Node Compose::NODE_1925925346416[] PROGMEM = {
	{{1, 1, L2, KEYPAD_9}, {0x2021}},
};

const Node Compose::NODE_1925925346896[] PROGMEM = {
	{{1, 1, L5, KEY_SPACE}, {0x2d}},
};

const Node Compose::NODE_1925925347136[] PROGMEM = {
	{{0, 1, L1, KEY_7}, {0x204a}},
	{{1, 1, L1, KEY_8}, {0x215e}},
};

const Node Compose::NODE_1925925347056[] PROGMEM = {
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_1925925355664}},
	{{0, 1, L1, KEY_2}, {0x2161}},
	{{0, 1, L1, KEY_3}, {0x2162}},
	{{0, 1, L1, KEY_4}, {0x2163}},
	{{0, 1, L1, KEY_5}, {0x2164}},
	{{0, 1, L1, KEY_6}, {0x2165}},
	{{0, 1, L1, KEY_7}, {0x2166}},
	{{0, 1, L1, KEY_8}, {0x2167}},
	{{0, 1, L1, KEY_9}, {0x2168}},
	{{0, 1, L2, KEY_K}, {0x280}},
	{{1, 1, L1, KEY_F}, {0x211c}},
};

const Node Compose::NODE_1925925355664[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2160}},
	{{0, 1, L1, KEY_0}, {0x2169}},
	{{0, 1, L1, KEY_1}, {0x216a}},
	{{1, 1, L1, KEY_2}, {0x216b}},
};

const Node Compose::NODE_1925925356624[] PROGMEM = {
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_1925925356784}},
	{{0, 1, L1, KEY_2}, {0x2171}},
	{{0, 1, L1, KEY_3}, {0x2172}},
	{{0, 1, L1, KEY_4}, {0x2173}},
	{{0, 1, L1, KEY_5}, {0x2174}},
	{{0, 1, L1, KEY_6}, {0x2175}},
	{{0, 1, L1, KEY_7}, {0x2176}},
	{{0, 1, L1, KEY_8}, {0x2177}},
	{{0, 1, L1, KEY_9}, {0x2178}},
	{{0, 1, L3, KEY_W}, {0x27e}},
	{{0, 1, L1, KEY_K}, {0x27c}},
	{{1, 1, L1, KEY_F}, {0x211c}},
};

const Node Compose::NODE_1925925356784[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2170}},
	{{0, 1, L1, KEY_0}, {0x2179}},
	{{0, 1, L1, KEY_1}, {0x217a}},
	{{1, 1, L1, KEY_2}, {0x217b}},
};

const Node Compose::NODE_1925925358064[] PROGMEM = {
	{{0, 1, L1, KEY_5}, {0x2157}},
	{{0, 1, L1, KEY_8}, {0x215c}},
	{{0, 1, L1, KEY_4}, {0xbe}},
	{{0, 1, L3, KEY_T}, {0xb3}},
	{{0, 1, L1, KEY_3}, {0x25c}},
	{{0, 1, L6, KEY_W}, {0x221b}},
	{{0, 1, L6, KEY_S}, {0x222d}},
	{{0, 1, L3, KEY_I}, {0x22d9}},
	{{0, 1, L3, KEY_U}, {0x22d8}},
	{{1, 1, L3, KEY_O}, {0x2a76}},
};

const Node Compose::NODE_1925925358144[] PROGMEM = {
	{{0, 1, L1, KEY_5}, {0x2158}},
	{{0, 1, L6, KEY_W}, {0x221c}},
	{{1, 1, L6, KEY_S}, {0x2a0c}},
};

const Node Compose::NODE_1925925358464[] PROGMEM = {
	{{0, 1, L1, KEY_6}, {0x215a}},
	{{1, 1, L1, KEY_8}, {0x215d}},
};

const Node Compose::NODE_1925925380160[] PROGMEM = {
	{{0, 1, L3, KEY_K}, {0x263a}},
	{{0, 1, L3, KEY_J}, {0x2639}},
	{{0, 1, L1, KEY_MINUS}, {0xf7}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2d0}},
	{{1, 1, L3, KEY_O}, {0x2254}},
};

const Node Compose::NODE_1925925380400[] PROGMEM = {
	{{1, 0, L3, KEY_S}, {(uint16_t) NODE_1925925380560}},
};

const Node Compose::NODE_1925925380560[] PROGMEM = {
	{{1, 1, L1, KEY_G}, {0x2105}},
};

const Node Compose::NODE_1925925380480[] PROGMEM = {
	{{0, 1, L5, KEY_5}, {0x26a2}},
	{{1, 1, L5, KEY_4}, {0x26a4}},
};

const Node Compose::NODE_1925925380720[] PROGMEM = {
	{{0, 1, L5, KEY_4}, {0x26a3}},
	{{1, 1, L5, KEY_5}, {0x26a4}},
};

const Node Compose::NODE_1925925381840[] PROGMEM = {
	{{0, 1, L1, KEY_3}, {0x2665}},
	{{0, 1, L1, KEY_PERIOD}, {0x2235}},
	{{0, 1, L3, KEY_O}, {0x2264}},
	{{0, 1, L3, KEY_C}, {0x22b2}},
	{{0, 1, L3, KEY_U}, {0x226a}},
	{{0, 1, L3, KEY_K}, {0x2aa6}},
	{{0, 1, L3, KEY_H}, {0x2a7b}},
	{{0, 1, L3, KEY_I}, {0x2260}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925882592}},
	{{1, 1, L1, KEY_MINUS}, {0x2190}},
};

const Node Compose::NODE_1925925882592[] PROGMEM = {
	{{1, 1, L3, KEY_RIGHT_BRACE}, {0x226e}},
};

const Node Compose::NODE_1925925382160[] PROGMEM = {
	{{0, 0, L2, KEY_J}, {(uint16_t) NODE_1925925382240}},
	{{1, 1, L3, KEY_C}, {0x2c6d}},
};

const Node Compose::NODE_1925925382240[] PROGMEM = {
	{{1, 1, L2, KEY_SEMICOLON}, {0x262e}},
};

const Node Compose::NODE_1925925382000[] PROGMEM = {
	{{0, 1, L3, KEY_R}, {0x25a1}},
	{{1, 1, L3, KEY_E}, {0x27e6}},
};

const Node Compose::NODE_1925925382400[] PROGMEM = {
	{{0, 1, L2, KEYPAD_7}, {0x2611}},
	{{1, 1, L2, KEYPAD_8}, {0x2612}},
};

const Node Compose::NODE_1925925382560[] PROGMEM = {
	{{1, 1, L6, KEYPAD_0}, {0x2611}},
};

const Node Compose::NODE_1925925382880[] PROGMEM = {
	{{1, 1, L6, KEYPAD_0}, {0x2612}},
};

const Node Compose::NODE_1925925382960[] PROGMEM = {
	{{0, 1, L3, KEY_Y}, {0x26a0}},
	{{0, 1, L3, KEY_O}, {0x225c}},
	{{0, 1, L3, KEY_N}, {0x2a39}},
	{{0, 1, L1, KEY_MINUS}, {0x2a3a}},
	{{1, 1, L3, KEY_G}, {0x2a3b}},
};

const Node Compose::NODE_1925925383360[] PROGMEM = {
	{{1, 1, L2, KEYPAD_0}, {0x237d}},
};

const Node Compose::NODE_1925925383440[] PROGMEM = {
	{{0, 1, L1, KEY_O}, {0x20b0}},
	{{0, 0, L1, KEY_G}, {(uint16_t) NODE_1925925383840}},
	{{0, 1, L3, KEY_Y}, {0xb6}},
	{{0, 0, L1, KEY_K}, {(uint16_t) NODE_1925925844608}},
	{{1, 0, L1, KEY_U}, {(uint16_t) NODE_1925925963152}},
};

const Node Compose::NODE_1925925383840[] PROGMEM = {
	{{1, 1, L1, KEY_S}, {0x2318}},
};

const Node Compose::NODE_1925925844608[] PROGMEM = {
	{{1, 0, L1, KEY_G}, {(uint16_t) NODE_1925925844848}},
};

const Node Compose::NODE_1925925844848[] PROGMEM = {
	{{0, 1, L1, KEY_SEMICOLON}, {0x220f}},
	{{1, 1, L1, KEY_V}, {0x221d}},
};

const Node Compose::NODE_1925925963152[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x210e}},
	{{0, 1, L1, KEY_MINUS}, {0x210f}},
	{{1, 1, L3, KEY_MINUS}, {0x210f}},
};

const Node Compose::NODE_1925925405056[] PROGMEM = {
	{{0, 0, L3, KEY_S}, {(uint16_t) NODE_1925925405136}},
	{{1, 1, L1, KEY_0}, {0x298}},
};

const Node Compose::NODE_1925925405136[] PROGMEM = {
	{{1, 1, L1, KEY_PERIOD}, {0x2052}},
};

const Node Compose::NODE_1925925405296[] PROGMEM = {
	{{1, 1, L2, KEY_PERIOD}, {0x2023}},
};

const Node Compose::NODE_1925925614432[] PROGMEM = {
	{{0, 1, L1, KEY_MINUS}, {0xb1}},
	{{0, 1, L3, KEY_MINUS}, {0xb1}},
	{{1, 1, L6, KEY_SEMICOLON}, {0x2a39}},
};

const Node Compose::NODE_1925925614752[] PROGMEM = {
	{{1, 1, L3, KEY_Y}, {0xb6}},
};

const Node Compose::NODE_1925925615552[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x152}},
	{{0, 0, L2, KEY_G}, {(uint16_t) NODE_1925925716672}},
	{{0, 1, L2, KEY_A}, {0x222}},
	{{1, 1, L1, KEY_G}, {0x2c7a}},
};

const Node Compose::NODE_1925925716672[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x276}},
};

const Node Compose::NODE_1925925615632[] PROGMEM = {
	{{0, 1, L1, KEY_F}, {0xe6}},
	{{0, 1, L1, KEY_D}, {0x251}},
	{{0, 1, L1, KEY_0}, {0x660}},
	{{0, 1, L1, KEY_1}, {0x661}},
	{{0, 1, L1, KEY_2}, {0x662}},
	{{0, 1, L1, KEY_3}, {0x663}},
	{{0, 1, L1, KEY_4}, {0x664}},
	{{0, 1, L1, KEY_5}, {0x665}},
	{{0, 1, L1, KEY_6}, {0x666}},
	{{0, 1, L1, KEY_7}, {0x667}},
	{{0, 1, L1, KEY_8}, {0x668}},
	{{0, 1, L1, KEY_9}, {0x669}},
	{{1, 1, L1, KEY_Q}, {0x221d}},
};

const Node Compose::NODE_1925925616112[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0xc6}},
};

const Node Compose::NODE_1925925616672[] PROGMEM = {
	{{0, 1, L1, KEY_3}, {0x2189}},
	{{0, 1, L1, KEY_PERIOD}, {0x298}},
	{{1, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925860592}},
};

const Node Compose::NODE_1925925860592[] PROGMEM = {
	{{1, 1, L3, KEY_RIGHT_BRACE}, {0x2205}},
};

const Node Compose::NODE_1925925617072[] PROGMEM = {
	{{0, 1, L1, KEY_0}, {0x2070}},
	{{0, 0, L3, KEY_W}, {(uint16_t) NODE_1925925617392}},
	{{0, 1, L1, KEY_2}, {0xb2}},
	{{0, 1, L1, KEY_3}, {0xb3}},
	{{0, 1, L1, KEY_1}, {0xb9}},
	{{0, 1, L1, KEY_4}, {0x2074}},
	{{0, 1, L1, KEY_5}, {0x2075}},
	{{0, 1, L1, KEY_6}, {0x2076}},
	{{0, 1, L1, KEY_7}, {0x2077}},
	{{0, 1, L1, KEY_8}, {0x2078}},
	{{0, 1, L1, KEY_9}, {0x2079}},
	{{0, 1, L3, KEY_N}, {0x207a}},
	{{0, 1, L3, KEY_O}, {0x207c}},
	{{0, 1, L3, KEY_J}, {0x207d}},
	{{0, 1, L3, KEY_K}, {0x207e}},
	{{0, 1, L3, KEY_G}, {0x33d}},
	{{0, 1, L3, KEY_E}, {0x2308}},
	{{0, 1, L3, KEY_R}, {0x2309}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1925925900752}},
	{{0, 0, L3, KEY_A}, {(uint16_t) NODE_1925925901232}},
	{{0, 1, L3, KEY_I}, {0x20d7}},
	{{0, 1, L3, KEY_U}, {0x20d6}},
	{{0, 1, L1, KEY_MINUS}, {0x207b}},
	{{0, 1, L3, KEY_MINUS}, {0x207b}},
	{{0, 1, L1, KEY_D}, {0x1d43}},
	{{0, 1, L1, KEY_N}, {0x1d47}},
	{{0, 1, L1, KEY_R}, {0x1d9c}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1d48}},
	{{0, 1, L1, KEY_F}, {0x1d49}},
	{{0, 1, L1, KEY_O}, {0x1da0}},
	{{0, 1, L1, KEY_I}, {0x1d4d}},
	{{0, 1, L1, KEY_U}, {0x2b0}},
	{{0, 1, L1, KEY_S}, {0x2071}},
	{{0, 1, L1, KEY_SLASH}, {0x2b2}},
	{{0, 1, L1, KEY_Y}, {0x1d4f}},
	{{0, 1, L1, KEY_E}, {0x2e1}},
	{{0, 1, L1, KEY_M}, {0x1d50}},
	{{0, 1, L1, KEY_J}, {0x207f}},
	{{0, 1, L1, KEY_G}, {0x1d52}},
	{{0, 1, L1, KEY_V}, {0x1d56}},
	{{0, 1, L1, KEY_K}, {0x2b3}},
	{{0, 1, L1, KEY_H}, {0x2e2}},
	{{0, 1, L1, KEY_L}, {0x1d57}},
	{{0, 1, L1, KEY_A}, {0x1d58}},
	{{0, 1, L1, KEY_W}, {0x1d5b}},
	{{0, 1, L1, KEY_T}, {0x2b7}},
	{{0, 1, L1, KEY_Q}, {0x2e3}},
	{{0, 1, L1, KEY_QUOTE}, {0x2b8}},
	{{0, 1, L1, KEY_B}, {0x1dbb}},
	{{0, 1, L2, KEY_D}, {0x1d2c}},
	{{0, 1, L2, KEY_N}, {0x1d2e}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1d30}},
	{{0, 1, L2, KEY_F}, {0x1d31}},
	{{0, 1, L2, KEY_I}, {0x1d33}},
	{{0, 1, L2, KEY_U}, {0x1d34}},
	{{0, 1, L2, KEY_S}, {0x1d35}},
	{{0, 1, L2, KEY_SLASH}, {0x1d36}},
	{{0, 1, L2, KEY_Y}, {0x1d37}},
	{{0, 1, L2, KEY_E}, {0x1d38}},
	{{0, 1, L2, KEY_M}, {0x1d39}},
	{{0, 1, L2, KEY_J}, {0x1d3a}},
	{{0, 1, L2, KEY_G}, {0x1d3c}},
	{{0, 1, L2, KEY_V}, {0x1d3e}},
	{{0, 1, L2, KEY_K}, {0x1d3f}},
	{{0, 1, L2, KEY_L}, {0x1d40}},
	{{0, 1, L2, KEY_A}, {0x1d41}},
	{{0, 1, L2, KEY_W}, {0x2c7d}},
	{{0, 1, L2, KEY_T}, {0x1d42}},
	{{0, 1, L5, KEY_D}, {0x1d45}},
	{{0, 1, L5, KEY_N}, {0x1d5d}},
	{{0, 1, L5, KEY_I}, {0x1d5e}},
	{{0, 1, L5, KEY_F}, {0x1d4b}},
	{{0, 1, L5, KEY_P}, {0x1d60}},
	{{1, 1, L5, KEY_QUOTE}, {0x1db7}},
};

const Node Compose::NODE_1925925617392[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0x2071}},
	{{1, 1, L1, KEY_J}, {0x207f}},
};

const Node Compose::NODE_1925925900752[] PROGMEM = {
	{{1, 1, L1, KEY_W}, {0x2195}},
};

const Node Compose::NODE_1925925901232[] PROGMEM = {
	{{1, 1, L1, KEY_W}, {0x2921}},
};

const Node Compose::NODE_1925925634912[] PROGMEM = {
	{{0, 1, L1, KEY_A}, {0xb5}},
	{{1, 0, L1, KEY_S}, {(uint16_t) NODE_1925925963952}},
};

const Node Compose::NODE_1925925963952[] PROGMEM = {
	{{1, 0, L1, KEY_R}, {(uint16_t) NODE_1925925964112}},
};

const Node Compose::NODE_1925925964112[] PROGMEM = {
	{{1, 0, L1, KEY_K}, {(uint16_t) NODE_1925925964032}},
};

const Node Compose::NODE_1925925964032[] PROGMEM = {
	{{1, 1, L1, KEY_G}, {0xb5}},
};

const Node Compose::NODE_1925925657792[] PROGMEM = {
	{{1, 1, L5, KEY_I}, {0x263}},
};

const Node Compose::NODE_1925925658512[] PROGMEM = {
	{{1, 1, L3, KEY_K}, {0x1b2}},
};

const Node Compose::NODE_1925925658352[] PROGMEM = {
	{{0, 1, L3, KEY_K}, {0x28b}},
	{{0, 1, L3, KEY_C}, {0x2193}},
	{{1, 0, L3, KEY_S}, {(uint16_t) NODE_1925925901312}},
};

const Node Compose::NODE_1925925901312[] PROGMEM = {
	{{1, 1, L3, KEY_T}, {0x2922}},
};

const Node Compose::NODE_1925925675792[] PROGMEM = {
	{{0, 1, L2, KEY_J}, {0x19d}},
	{{0, 1, L1, KEY_J}, {0x272}},
	{{1, 1, L1, KEY_O}, {0x284}},
};

const Node Compose::NODE_1925925675952[] PROGMEM = {
	{{1, 1, L2, KEY_J}, {0x19d}},
};

const Node Compose::NODE_1925925676512[] PROGMEM = {
	{{1, 0, L1, KEY_U}, {(uint16_t) NODE_1925925676592}},
};

const Node Compose::NODE_1925925676592[] PROGMEM = {
	{{0, 1, L1, KEY_SLASH}, {0x267}},
	{{1, 1, L1, KEY_I}, {0x267}},
};

const Node Compose::NODE_1925925676912[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x23a}},
	{{0, 1, L1, KEY_D}, {0x2c65}},
	{{0, 1, L2, KEY_R}, {0x23b}},
	{{0, 1, L1, KEY_R}, {0x23c}},
	{{0, 1, L2, KEY_F}, {0x246}},
	{{0, 1, L1, KEY_F}, {0x247}},
	{{0, 1, L2, KEY_L}, {0x23e}},
	{{0, 1, L1, KEY_L}, {0x2c66}},
	{{0, 1, L5, KEY_E}, {0x19b}},
	{{0, 1, L3, KEY_LEFT_BRACE}, {0x1e9c}},
	{{0, 1, L1, KEY_0}, {0x2205}},
	{{0, 1, L6, KEY_S}, {0x2a0f}},
	{{0, 1, L3, KEY_O}, {0x2260}},
	{{0, 1, L3, KEY_C}, {0x2224}},
	{{0, 1, L3, KEY_V}, {0x2241}},
	{{0, 1, L3, KEY_U}, {0x226e}},
	{{0, 1, L3, KEY_I}, {0x226f}},
	{{0, 1, L3, KEY_T}, {0x2197}},
	{{1, 1, L1, KEY_W}, {0x2199}},
};

const Node Compose::NODE_1925925695712[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x2c60}},
	{{0, 1, L1, KEY_E}, {0x2c61}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1925925719472}},
	{{0, 1, L3, KEY_V}, {0x2245}},
	{{0, 1, L3, KEY_O}, {0x2261}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2255}},
	{{0, 1, L3, KEY_I}, {0x2265}},
	{{0, 1, L3, KEY_U}, {0x2264}},
	{{0, 1, L2, KEY_1}, {0x2257}},
	{{0, 1, L3, KEY_T}, {0x2259}},
	{{0, 1, L6, KEY_SEMICOLON}, {0x225c}},
	{{0, 1, L3, KEY_H}, {0x225f}},
	{{0, 1, L6, KEY_S}, {0x2a0e}},
	{{1, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925881472}},
};

const Node Compose::NODE_1925925719472[] PROGMEM = {
	{{0, 1, L3, KEY_U}, {0x22b4}},
	{{1, 1, L3, KEY_I}, {0x22b5}},
};

const Node Compose::NODE_1925925881472[] PROGMEM = {
	{{1, 1, L3, KEY_RIGHT_BRACE}, {0x2260}},
};

const Node Compose::NODE_1925925698272[] PROGMEM = {
	{{0, 1, L2, KEY_U}, {0x1b7}},
	{{1, 1, L2, KEY_B}, {0x1b7}},
};

const Node Compose::NODE_1925925699312[] PROGMEM = {
	{{1, 1, L2, KEY_N}, {0x299}},
};

const Node Compose::NODE_1925925699472[] PROGMEM = {
	{{0, 1, L2, KEY_I}, {0x262}},
	{{1, 1, L2, KEY_A}, {0x222}},
};

const Node Compose::NODE_1925925716032[] PROGMEM = {
	{{0, 1, L2, KEY_U}, {0x29c}},
	{{0, 1, L2, KEY_W}, {0x1f6}},
	{{1, 1, L1, KEY_W}, {0x1f6}},
};

const Node Compose::NODE_1925925716512[] PROGMEM = {
	{{0, 1, L2, KEY_QUOTE}, {0x28f}},
	{{0, 1, L2, KEY_I}, {0x21c}},
	{{1, 1, L1, KEY_I}, {0x21c}},
};

const Node Compose::NODE_1925925716592[] PROGMEM = {
	{{1, 1, L5, KEY_D}, {0x251}},
};

const Node Compose::NODE_1925925717072[] PROGMEM = {
	{{1, 1, L5, KEY_F}, {0x25b}},
};

const Node Compose::NODE_1925925717232[] PROGMEM = {
	{{1, 1, L5, KEY_P}, {0x278}},
};

const Node Compose::NODE_1925925717392[] PROGMEM = {
	{{1, 1, L5, KEY_QUOTE}, {0x28a}},
};

const Node Compose::NODE_1925925718832[] PROGMEM = {
	{{0, 1, L1, KEY_I}, {0x261}},
	{{0, 1, L2, KEY_A}, {0x222}},
	{{1, 1, L1, KEY_A}, {0x223}},
};

const Node Compose::NODE_1925925719312[] PROGMEM = {
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_1925925719552}},
	{{0, 1, L3, KEY_I}, {0x2aa7}},
	{{1, 1, L3, KEY_J}, {0x2985}},
};

const Node Compose::NODE_1925925719552[] PROGMEM = {
	{{1, 1, L1, KEY_SPACE}, {0x25e}},
};

const Node Compose::NODE_1925925719712[] PROGMEM = {
	{{0, 1, L3, KEY_W}, {0x264}},
	{{1, 1, L3, KEY_H}, {0x242}},
};

const Node Compose::NODE_1925925736672[] PROGMEM = {
	{{1, 1, L3, KEY_PERIOD}, {0x2c8}},
};

const Node Compose::NODE_1925925752896[] PROGMEM = {
	{{0, 1, L1, KEY_RIGHT_BRACE}, {0x1dc4}},
	{{1, 1, L1, KEY_EQUAL}, {0x1dc6}},
};

const Node Compose::NODE_1925925753056[] PROGMEM = {
	{{0, 1, L6, KEY_EQUAL}, {0x1dc5}},
	{{1, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925753456}},
};

const Node Compose::NODE_1925925753456[] PROGMEM = {
	{{1, 1, L1, KEY_EQUAL}, {0x1dc8}},
};

const Node Compose::NODE_1925925753136[] PROGMEM = {
	{{0, 1, L6, KEY_EQUAL}, {0x1dc7}},
	{{1, 0, L1, KEY_EQUAL}, {(uint16_t) NODE_1925925753536}},
};

const Node Compose::NODE_1925925753536[] PROGMEM = {
	{{1, 1, L1, KEY_RIGHT_BRACE}, {0x1dc9}},
};

const Node Compose::NODE_1925925795216[] PROGMEM = {
	{{1, 1, L5, KEY_QUOTE}, {0x223}},
};

const Node Compose::NODE_1925925795536[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x241}},
};

const Node Compose::NODE_1925925796896[] PROGMEM = {
	{{0, 1, L1, KEY_W}, {0x195}},
	{{0, 1, L1, KEY_D}, {0x2135}},
	{{0, 1, L1, KEY_N}, {0x2136}},
	{{0, 1, L1, KEY_I}, {0x2137}},
	{{1, 1, L1, KEY_SEMICOLON}, {0x2138}},
};

const Node Compose::NODE_1925925796976[] PROGMEM = {
	{{0, 1, L2, KEY_QUOTE}, {0x1f7}},
	{{1, 1, L1, KEY_QUOTE}, {0x1f7}},
};

const Node Compose::NODE_1925925797296[] PROGMEM = {
	{{0, 1, L1, KEY_QUOTE}, {0x1bf}},
	{{0, 0, L1, KEY_S}, {(uint16_t) NODE_1925925901392}},
	{{0, 1, L1, KEY_V}, {0x2118}},
	{{0, 1, L2, KEY_1}, {0xb0}},
	{{0, 1, L3, KEY_PERIOD}, {0x2032}},
	{{0, 1, L1, KEY_3}, {0x2034}},
	{{1, 1, L1, KEY_4}, {0x2057}},
};

const Node Compose::NODE_1925925901392[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x21af}},
};

const Node Compose::NODE_1925925797616[] PROGMEM = {
	{{1, 1, L1, KEY_I}, {0x21d}},
};

const Node Compose::NODE_1925925211808[] PROGMEM = {
	{{0, 1, L1, KEY_3}, {0x221b}},
	{{1, 1, L1, KEY_4}, {0x221c}},
};

const Node Compose::NODE_1925925818832[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x222c}},
	{{0, 1, L6, KEY_S}, {0x222c}},
	{{0, 1, L1, KEY_3}, {0x222d}},
	{{0, 1, L1, KEY_4}, {0x2a0c}},
	{{0, 1, L3, KEY_O}, {0x2a0e}},
	{{1, 1, L3, KEY_G}, {0x2a18}},
};

const Node Compose::NODE_1925925820512[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x2234}},
	{{0, 1, L3, KEY_O}, {0x2265}},
	{{0, 1, L3, KEY_I}, {0x226b}},
	{{0, 1, L3, KEY_H}, {0x2a7c}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925882992}},
	{{1, 1, L1, KEY_MINUS}, {0x291a}},
};

const Node Compose::NODE_1925925882992[] PROGMEM = {
	{{1, 1, L3, KEY_RIGHT_BRACE}, {0x226f}},
};

const Node Compose::NODE_1925925821072[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0x2245}},
	{{0, 1, L3, KEY_V}, {0x2248}},
	{{1, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925882352}},
};

const Node Compose::NODE_1925925882352[] PROGMEM = {
	{{1, 1, L3, KEY_RIGHT_BRACE}, {0x2241}},
};

const Node Compose::NODE_1925925843248[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0x2257}},
	{{0, 1, L2, KEY_R}, {0x2103}},
	{{1, 1, L2, KEY_O}, {0x2109}},
};

const Node Compose::NODE_1925925844288[] PROGMEM = {
	{{0, 1, L3, KEY_N}, {0x2213}},
	{{1, 0, L1, KEY_V}, {(uint16_t) NODE_1925925963472}},
};

const Node Compose::NODE_1925925963472[] PROGMEM = {
	{{1, 1, L1, KEY_U}, {0x210f}},
};

const Node Compose::NODE_1925925846128[] PROGMEM = {
	{{0, 1, L3, KEY_W}, {0x22bb}},
	{{1, 1, L6, KEY_2}, {0x22c1}},
};

const Node Compose::NODE_1925925846208[] PROGMEM = {
	{{0, 1, L3, KEY_W}, {0x2a5f}},
	{{1, 1, L6, KEY_3}, {0x22c0}},
};

const Node Compose::NODE_1925925846608[] PROGMEM = {
	{{1, 1, L6, KEY_V}, {0x220f}},
};

const Node Compose::NODE_1925925859712[] PROGMEM = {
	{{0, 1, L3, KEY_U}, {0x22b2}},
	{{0, 1, L3, KEY_I}, {0x22b3}},
	{{0, 1, L1, KEY_SPACE}, {0x2223}},
	{{0, 1, L3, KEY_C}, {0x2016}},
	{{0, 1, L1, KEY_MINUS}, {0x22a2}},
	{{0, 1, L3, KEY_O}, {0x22a8}},
	{{0, 0, L3, KEY_G}, {(uint16_t) NODE_1925925880912}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1925925881952}},
	{{0, 1, L3, KEY_T}, {0x2191}},
	{{0, 0, L3, KEY_A}, {(uint16_t) NODE_1925925901632}},
	{{0, 0, L3, KEY_S}, {(uint16_t) NODE_1925925901792}},
	{{0, 1, L2, KEY_R}, {0x2102}},
	{{0, 1, L2, KEY_U}, {0x210d}},
	{{0, 1, L2, KEY_J}, {0x2115}},
	{{0, 1, L2, KEY_V}, {0x2119}},
	{{0, 1, L2, KEY_P}, {0x211a}},
	{{0, 1, L2, KEY_K}, {0x211d}},
	{{0, 1, L2, KEY_B}, {0x2124}},
	{{0, 1, L5, KEY_I}, {0x213d}},
	{{0, 1, L5, KEY_V}, {0x213c}},
	{{0, 1, L6, KEY_V}, {0x213f}},
	{{0, 1, L3, KEY_J}, {0x2985}},
	{{0, 1, L3, KEY_K}, {0x2986}},
	{{0, 1, L3, KEY_E}, {0x27e6}},
	{{0, 1, L3, KEY_R}, {0x27e7}},
	{{0, 1, L3, KEY_D}, {0x2983}},
	{{1, 1, L3, KEY_F}, {0x2984}},
};

const Node Compose::NODE_1925925880912[] PROGMEM = {
	{{0, 1, L3, KEY_C}, {0x22c8}},
	{{1, 1, L1, KEY_SPACE}, {0x22c9}},
};

const Node Compose::NODE_1925925881952[] PROGMEM = {
	{{1, 1, L3, KEY_RIGHT_BRACE}, {0x2224}},
};

const Node Compose::NODE_1925925901632[] PROGMEM = {
	{{0, 1, L3, KEY_T}, {0x21d6}},
	{{1, 1, L1, KEY_W}, {0x21d8}},
};

const Node Compose::NODE_1925925901792[] PROGMEM = {
	{{0, 1, L3, KEY_T}, {0x21d7}},
	{{1, 1, L1, KEY_W}, {0x21d9}},
};

const Node Compose::NODE_1925925860192[] PROGMEM = {
	{{0, 1, L3, KEY_A}, {0x2216}},
	{{0, 1, L3, KEY_T}, {0x2196}},
	{{1, 1, L1, KEY_W}, {0x2198}},
};

const Node Compose::NODE_1925925862832[] PROGMEM = {
	{{0, 1, L6, KEY_SEMICOLON}, {0x2a3b}},
	{{0, 1, L6, KEY_S}, {0x2a18}},
	{{0, 1, L3, KEY_G}, {0x2a2f}},
	{{1, 1, L3, KEY_C}, {0x22ca}},
};

const Node Compose::NODE_1925925943392[] PROGMEM = {
	{{1, 0, L1, KEY_E}, {(uint16_t) NODE_1925925943552}},
};

const Node Compose::NODE_1925925943552[] PROGMEM = {
	{{1, 1, L1, KEY_E}, {0x2113}},
};

const Node Compose::NODE_1925925961872[] PROGMEM = {
	{{1, 1, L3, KEY_K}, {0x2986}},
};

const Node Compose::NODE_1925925962272[] PROGMEM = {
	{{1, 1, L3, KEY_R}, {0x27e7}},
};

const Node Compose::NODE_1925925962512[] PROGMEM = {
	{{1, 1, L3, KEY_D}, {0x2983}},
};

const Node Compose::NODE_1925925962832[] PROGMEM = {
	{{1, 1, L3, KEY_F}, {0x2984}},
};


/*
 * Mapping of Keys which exist multiple times on keyboard
 * left Sequence will be remapped right sequence for lookup
*/
const LayeredKey Compose::aliases[][2] {
	{{L3, KEY_L}, {L1, KEY_MINUS}},
	{{L1, KEYPAD_SUBTRACT}, {L1, KEY_MINUS}},
	{{L1, KEYPAD_1}, {L1, KEY_1}},
	{{L1, KEYPAD_2}, {L1, KEY_2}},
	{{L1, KEYPAD_3}, {L1, KEY_3}},
	{{L1, KEYPAD_4}, {L1, KEY_4}},
	{{L1, KEYPAD_5}, {L1, KEY_5}},
	{{L1, KEYPAD_6}, {L1, KEY_6}},
	{{L1, KEYPAD_7}, {L1, KEY_7}},
	{{L1, KEYPAD_8}, {L1, KEY_8}},
	{{L1, KEYPAD_9}, {L1, KEY_9}},
	{{L1, KEYPAD_0}, {L1, KEY_0}},
	{{L1, KEYPAD_DIVIDE}, {L3, KEY_S}},
	{{L1, KEYPAD_MULTIPLY}, {L3, KEY_G}},
	{{L1, KEYPAD_ADD}, {L3, KEY_N}},
};

LayeredKey Compose::getAlias(uint8_t layer, uint8_t key) {
	for(int16_t i = 0; i < (sizeof(aliases) / sizeof(aliases[0])); i++){
		if(layer == aliases[i][0].layer && key == aliases[i][0].key){
			return aliases[i][1];
		}
	}
	return {0,0};
}

uint16_t Compose::transition(uint8_t layer, uint8_t key) {
	Node* cur = currentNode;
	Node val_cur;
	
	LayeredKey alias = getAlias(layer, key);
	if(alias.layer != 0 && alias.key != 0){
		layer = alias.layer;
		key = alias.key;
	}
	
	do {
		memcpy_P(&val_cur, cur, sizeof(val_cur));
		if (val_cur.layeredKey.layer == layer && val_cur.layeredKey.keycode == key) { //found
			if (val_cur.layeredKey.isLeaf) {
				currentNode = const_cast<Node*>(root);
				return val_cur.payload.unicode;
				
				} else { //found, waiting for next key
				currentNode = const_cast<Node*>(val_cur.payload.nodes);
				return 1;
			}
		}
		cur++;
	} while (val_cur.layeredKey.isLastElement == 0);
	
	//not found
	currentNode = const_cast<Node*>(root);
	return 0;
}

void Compose::reset(){
	currentNode = const_cast<Node*>(root);
}