/***********************************************************************/
/******************* This file is generated by *************************/
/******************* the Compose Generator *****************************/
/***********************************************************************/

#ifndef __COMPOSE_H__
#define __COMPOSE_H__

#include "NeoIncludes.h"

/*
 * The tree is static, therefore no methods for removing/adding elements,
 * to not make life too complicated, this file is generated by a script.
 * 
 * Pointer points to either next node or unicode symbol. This is detected by
 * address range comparison.

*/

struct Node {
	struct {
		uint8_t isLastElement : 1;
		uint8_t isLeaf : 1;
		uint8_t layer : 6;
		uint8_t keycode : 8;
	} layeredKey;
	union {
		uint16_t unicode;
		Node* nodes;
	} payload;
};


class Compose
{
	private:
	Node* currentNode;

	const static Node root[] PROGMEM;
	const static Node OBJ_3084155333744[] PROGMEM;
	const static Node OBJ_3084155333664[] PROGMEM;
	const static Node OBJ_3084155431888[] PROGMEM;
	const static Node OBJ_3084155432128[] PROGMEM;
	const static Node OBJ_3084155432288[] PROGMEM;
	const static Node OBJ_3084155333584[] PROGMEM;
	const static Node OBJ_3084155333984[] PROGMEM;
	const static Node OBJ_3084155159632[] PROGMEM;
	const static Node OBJ_3084155429888[] PROGMEM;
	const static Node OBJ_3084155430048[] PROGMEM;
	const static Node OBJ_3084155430128[] PROGMEM;
	const static Node OBJ_3084155334304[] PROGMEM;
	const static Node OBJ_3084155334544[] PROGMEM;
	const static Node OBJ_3084155396320[] PROGMEM;
	const static Node OBJ_3084155396400[] PROGMEM;
	const static Node OBJ_3084155398000[] PROGMEM;
	const static Node OBJ_3084155399360[] PROGMEM;
	const static Node OBJ_3084155396240[] PROGMEM;
	const static Node OBJ_3084155396560[] PROGMEM;
	const static Node OBJ_3084155396720[] PROGMEM;
	const static Node OBJ_3084155396880[] PROGMEM;
	const static Node OBJ_3084155410768[] PROGMEM;
	const static Node OBJ_3084155429568[] PROGMEM;
	const static Node OBJ_3084155429808[] PROGMEM;
	const static Node OBJ_3084155429648[] PROGMEM;
	const static Node OBJ_3084155397280[] PROGMEM;
	const static Node OBJ_3084155397440[] PROGMEM;
	const static Node OBJ_3084155397760[] PROGMEM;
	const static Node OBJ_3084155397680[] PROGMEM;
	const static Node OBJ_3084155397600[] PROGMEM;
	const static Node OBJ_3084155398160[] PROGMEM;
	const static Node OBJ_3084155398400[] PROGMEM;
	const static Node OBJ_3084155398720[] PROGMEM;
	const static Node OBJ_3084155398800[] PROGMEM;
	const static Node OBJ_3084155528032[] PROGMEM;
	const static Node OBJ_3084155398560[] PROGMEM;
	const static Node OBJ_3084155408928[] PROGMEM;
	const static Node OBJ_3084155408608[] PROGMEM;
	const static Node OBJ_3084155160512[] PROGMEM;
	const static Node OBJ_3084155285232[] PROGMEM;
	const static Node OBJ_3084155285072[] PROGMEM;
	const static Node OBJ_3084155284992[] PROGMEM;
	const static Node OBJ_3084155284592[] PROGMEM;
	const static Node OBJ_3084155411728[] PROGMEM;
	const static Node OBJ_3084155411888[] PROGMEM;
	const static Node OBJ_3084155411968[] PROGMEM;
	const static Node OBJ_3084155429248[] PROGMEM;
	const static Node OBJ_3084155429168[] PROGMEM;
	const static Node OBJ_3084155430288[] PROGMEM;
	const static Node OBJ_3084155430608[] PROGMEM;
	const static Node OBJ_3084155430928[] PROGMEM;
	const static Node OBJ_3084155431168[] PROGMEM;
	const static Node OBJ_3084155431568[] PROGMEM;
	const static Node OBJ_3084155431808[] PROGMEM;
	const static Node OBJ_3084155528192[] PROGMEM;
	const static Node OBJ_3084155432688[] PROGMEM;
	const static Node OBJ_3084155453504[] PROGMEM;
	const static Node OBJ_3084155455344[] PROGMEM;
	const static Node OBJ_3084155455424[] PROGMEM;
	const static Node OBJ_3084155455504[] PROGMEM;
	const static Node OBJ_3084155455904[] PROGMEM;
	const static Node OBJ_3084155456384[] PROGMEM;
	const static Node OBJ_3084155456544[] PROGMEM;
	const static Node OBJ_3084155456464[] PROGMEM;
	const static Node OBJ_3084155457104[] PROGMEM;
	const static Node OBJ_3084155457264[] PROGMEM;
	const static Node OBJ_3084155456704[] PROGMEM;
	const static Node OBJ_3084155456944[] PROGMEM;
	const static Node OBJ_3084155456864[] PROGMEM;
	const static Node OBJ_3084155457424[] PROGMEM;
	const static Node OBJ_3084155465872[] PROGMEM;
	const static Node OBJ_3084155466032[] PROGMEM;
	const static Node OBJ_3084155466512[] PROGMEM;
	const static Node OBJ_3084155466752[] PROGMEM;
	const static Node OBJ_3084155466672[] PROGMEM;
	const static Node OBJ_3084155467152[] PROGMEM;
	const static Node OBJ_3084155467072[] PROGMEM;
	const static Node OBJ_3084155468112[] PROGMEM;
	const static Node OBJ_3084155469152[] PROGMEM;
	const static Node OBJ_3084155469312[] PROGMEM;
	const static Node OBJ_3084155482656[] PROGMEM;
	const static Node OBJ_3084155484016[] PROGMEM;
	const static Node OBJ_3084155484096[] PROGMEM;
	const static Node OBJ_3084155484416[] PROGMEM;
	const static Node OBJ_3084155485376[] PROGMEM;
	const static Node OBJ_3084155485456[] PROGMEM;
	const static Node OBJ_3084155485776[] PROGMEM;
	const static Node OBJ_3084155511648[] PROGMEM;
	const static Node OBJ_3084155511888[] PROGMEM;
	const static Node OBJ_3084155512048[] PROGMEM;
	const static Node OBJ_3084155511968[] PROGMEM;
	const static Node OBJ_3084155512208[] PROGMEM;
	const static Node OBJ_3084155513568[] PROGMEM;
	const static Node OBJ_3084155513808[] PROGMEM;
	const static Node OBJ_3084155513968[] PROGMEM;
	const static Node OBJ_3084155513888[] PROGMEM;
	const static Node OBJ_3084155514128[] PROGMEM;
	const static Node OBJ_3084155514288[] PROGMEM;
	const static Node OBJ_3084155514608[] PROGMEM;
	const static Node OBJ_3084155514688[] PROGMEM;
	const static Node OBJ_3084155527472[] PROGMEM;
	const static Node OBJ_3084155527552[] PROGMEM;
	const static Node OBJ_3084155527952[] PROGMEM;
	const static Node OBJ_3084155528592[] PROGMEM;
	const static Node OBJ_3084155528672[] PROGMEM;
	const static Node OBJ_3084155528512[] PROGMEM;
	const static Node OBJ_3084155528832[] PROGMEM;

	public:
	Compose() : currentNode(const_cast<Node*>(root)){}
		
	uint16_t transition(uint8_t layer, uint8_t key);
	void reset();
	


}; //Compose

#endif //__COMPOSE_H__