/* 
* Neo2Map.cpp
*
* Created: 20.11.2021 10:45:50
* Author: Jonas
*/


#include "Neo2Map.h"


const uint8_t Neo2Map::neoMap[] = {
	//KEY_RESERVED		KEY_ERROR_ROLLOVER	KEY_POST_FAIL		KEY_ERROR_UNDEFINED	KEY_A				KEY_B				KEY_C				KEY_D
	KEY_RESERVED,		KEY_ERROR_ROLLOVER,	KEY_POST_FAIL,		KEY_ERROR_UNDEFINED,KEY_U,				KEY_Y,				KEY_QUOTE,			KEY_A,
	
	//KEY_E				KEY_F				KEY_G				KEY_H				KEY_I				KEY_J				KEY_K				KEY_L
	KEY_L,				KEY_E,				KEY_O,				KEY_S,				KEY_G,				KEY_N,				KEY_R,				KEY_T,
	
	//KEY_M				KEY_N				KEY_O				KEY_P				KEY_Q				KEY_R				KEY_S				KEY_T
	KEY_M,				KEY_B,				KEY_F,				KEY_Q,				KEY_X,				KEY_C,				KEY_I,				KEY_W,
	
	//KEY_U				KEY_V				KEY_W				KEY_X				KEY_Y				KEY_Z				KEY_1				KEY_2
	KEY_H,				KEY_P,				KEY_V,				KEY_SEMICOLON,		KEY_K,				KEY_LEFT_BRACE,		KEY_1,				KEY_2,
	
	//KEY_3				KEY_4				KEY_5				KEY_6				KEY_7				KEY_8				KEY_9				KEY_0
	KEY_3,				KEY_4,				KEY_5,				KEY_6,				KEY_7,				KEY_8,				KEY_9,				KEY_0,
	
	//KEY_ENTER			KEY_ESC				KEY_BACKSPACE		KEY_TAB				KEY_SPACE			KEY_MINUS			KEY_EQUAL			KEY_LEFT_BRACE
	KEY_ENTER,			KEY_ESC,			KEY_BACKSPACE,		KEY_TAB,			KEY_SPACE,			KEY_SLASH,			KEY_RIGHT_BRACE,	KEY_MINUS,
	
	//KEY_RIGHT_BRACE		KEY_BACKSLASH		KEY_NON_US_NUM		KEY_SEMICOLON		KEY_QUOTE			KEY_TILDE			KEY_COMMA			KEY_PERIOD
	KEY_EQUAL,			KEY_BACKSLASH,		KEY_NON_US_NUM,		KEY_D,				KEY_Z,				KEY_TILDE,			KEY_COMMA,			KEY_PERIOD,
	
	//KEY_SLASH			KEY_CAPS_LOCK		KEY_F1				KEY_F2				KEY_F3				KEY_F4				KEY_F5				KEY_F6
	KEY_J,				KEY_CAPS_LOCK,		KEY_F1,				KEY_F2,				KEY_F3,				KEY_F4,				KEY_F5,				KEY_F6,
	
	//KEY_F7				KEY_F8				KEY_F9				KEY_F10				KEY_F11				KEY_F12				KEY_PRINT			KEY_SCROLL_LOCK
	KEY_F7,				KEY_F8,				KEY_F9,				KEY_F10,			KEY_F11,			KEY_F12,			KEY_PRINTSCREEN,	KEY_SCROLL_LOCK,
	
	//KEY_PAUSE			KEY_INSERT			KEY_HOME			KEY_PAGE_UP			KEY_DELETE			KEY_END				KEY_PAGE_DOWN		KEY_RIGHT_ARROW
	KEY_PAUSE,			KEY_INSERT,			KEY_HOME,			KEY_PAGE_UP,		KEY_DELETE,			KEY_END,			KEY_PAGE_DOWN,		KEY_RIGHT_ARROW,
	
	//KEY_LEFT_ARROW		KEY_DOWN_ARROW		KEY_UP_ARROW		KEY_NUM_LOCK		KEYPAD_DIVIDE		KEYPAD_MULTIPLY		KEYPAD_SUBTRACT		KEYPAD_ADD
	KEY_LEFT_ARROW,		KEY_DOWN_ARROW,		KEY_UP_ARROW,		KEY_TAB,			KEYPAD_DIVIDE,		KEYPAD_MULTIPLY,	KEYPAD_SUBTRACT,	KEYPAD_ADD,
	
	//KEYPAD_ENTER		KEYPAD_1			KEYPAD_2			KEYPAD_3			KEYPAD_4			KEYPAD_5			KEYPAD_6			KEYPAD_7
	KEYPAD_ENTER,		KEYPAD_1,			KEYPAD_2,			KEYPAD_3,			KEYPAD_4,			KEYPAD_5,			KEYPAD_6,			KEYPAD_7,
	
	//KEYPAD_8			KEYPAD_9			KEYPAD_0			KEYPAD_DOT
	KEYPAD_8,			KEYPAD_9,			KEYPAD_0,			KEYPAD_DOT
};

const InputSequence Neo2Map::neoMapL2[] PROGMEM = {
	//KEY_1							KEY_2							KEY_3							KEY_4
	{KEY_LEFT_SHIFT, KEY_TILDE},	{KEY_LEFT_SHIFT, KEY_3},		{KEY_UNICODE, 0x2113},			{KEY_UNICODE, 0xBB},
	
	//KEY_5							KEY_6							KEY_7							KEY_8
	{KEY_UNICODE, 0xAB},			{KEY_LEFT_SHIFT, KEY_4},		{KEY_RIGHT_ALT, KEY_E},			{KEY_UNICODE, 0x201E},
	
	//KEY_9							KEY_0							KEY_ENTER						KEY_ESC
	{KEY_UNICODE, 0x201C},			{KEY_UNICODE, 0x201D},			{0, 0},							{0, 0},
	
	//KEY_BACKSPACE					KEY_TAB							KEY_SPACE						KEY_MINUS
	{0, 0},							{0, 0},							{0, 0},							{KEY_UNICODE, 0x2014},

	//KEY_EQUAL						KEY_LEFT_BRACE					KEY_RIGHT_BRACE					KEY_BACKSLASH
	{KEY_UNICODE, 0xB8},			{KEY_UNICODE, 0x1E9E},			{KEY_UNICODE, 0x2DC},			{0, 0},
	
	//KEY_NON_US_NUM					KEY_SEMICOLON					KEY_QUOTE						KEY_TILDE
	{0, 0},							{0, 0},							{0, 0},							{KEY_UNICODE, 0x2C7},
	
	//KEY_COMMA						KEY_PERIOD						KEY_SLASH						KEY_CAPS_LOCK
	{KEY_UNICODE, 0x2013},			{KEY_UNICODE, 0x2022},			{0, 0},							{0, 0},
	
	//KEY_F1							KEY_F2							KEY_F3							KEY_F4
	{0, 0},							{0, 0},							{0, 0},							{0, 0},
	
	//KEY_F5							KEY_F6							KEY_F7							KEY_F8
	{0, 0},							{0, 0},							{0, 0},							{0, 0},
	
	//KEY_F9							KEY_F10							KEY_F11							KEY_F12
	{0, 0},							{0, 0},							{0, 0},							{0, 0},
	
	//KEY_PRINT						KEY_SCROLL_LOCK					KEY_PAUSE						KEY_INSERT
	{0, 0},							{0, 0},							{0, 0},							{0, 0},
	
	//KEY_HOME						KEY_PAGE_UP						KEY_DELETE						KEY_END
	{0, 0},							{0, 0},							{0, 0},							{0, 0},
	
	//KEY_PAGE_DOWN					KEY_RIGHT_ARROW					KEY_LEFT_ARROW					KEY_DOWN_ARROW
	{0, 0},							{0, 0},							{0, 0},							{0, 0},
	
	//KEY_UP_ARROW					KEY_NUM_LOCK					KEYPAD_DIVIDE					KEYPAD_MULTIPLY
	{0, 0},							{0, 0},							{0, 0},							{0, 0},

	//KEYPAD_SUBTRACT					KEYPAD_ADD						KEYPAD_ENTER					KEYPAD_1
	{0, 0},							{0, 0},							{0, 0},							{KEY_UNICODE, 0x2666},
	
	//KEYPAD_2						KEYPAD_3						KEYPAD_4						KEYPAD_5
	{KEY_UNICODE, 0x2665},			{KEY_UNICODE, 0x2660},			{KEY_UNICODE, 0x2663},			{KEY_RIGHT_ALT, KEY_E},
	
	//KEYPAD_6						KEYPAD_7						KEYPAD_8						KEYPAD_9
	{KEY_UNICODE, 0x2023},			{KEY_UNICODE, 0x2714},			{KEY_UNICODE, 0x2718},			{KEY_UNICODE, 0x2020},
	
	//KEYPAD_0						KEYPAD_DOT
	{KEY_UNICODE, 0x2423},			{KEY_RESERVED, KEY_PERIOD}
};

const InputSequence Neo2Map::neoMapL3[] PROGMEM = {
	//KEY_RESERVED					KEY_ERROR_ROLLOVER	KEY_POST_FAIL								KEY_ERROR_UNDEFINED
	{0, 0},							{0, 0},							{0, 0},							{0, 0},
	
	//KEY_A							KEY_B							KEY_C							KEY_D
	{KEY_RIGHT_ALT, KEY_MINUS},		{KEY_UNICODE, 0x60},			{KEY_RIGHT_ALT, KEY_NON_US},	{KEY_RIGHT_ALT, KEY_7},
	
	//KEY_E							KEY_F							KEY_G							KEY_H
	{KEY_RIGHT_ALT, KEY_8},			{KEY_RIGHT_ALT, KEY_0},		{KEY_LEFT_SHIFT, KEY_RIGHT_BRACE},	{KEY_LEFT_SHIFT, KEY_MINUS},
	
	//KEY_I							KEY_J							KEY_K							KEY_L
	{KEY_LEFT_SHIFT, KEY_NON_US},	{KEY_LEFT_SHIFT, KEY_8},		{KEY_LEFT_SHIFT, KEY_9},		{KEY_RESERVED, KEY_SLASH},
	
	//KEY_M							KEY_N							KEY_O							KEY_P
	{KEY_LEFT_SHIFT, KEY_5},		{KEY_RESERVED, KEY_RIGHT_BRACE},{KEY_LEFT_SHIFT, KEY_0},		{KEY_LEFT_SHIFT, KEY_6},
	
	//KEY_Q							KEY_R							KEY_S							KEY_T
	{KEY_UNICODE, 0x2026},			{KEY_RIGHT_ALT, KEY_9},			{KEY_LEFT_SHIFT, KEY_7},		{KEY_UNICODE, 0x5E},
	
	//KEY_U							KEY_V							KEY_W							KEY_X
	{KEY_RESERVED, KEY_NON_US},	{KEY_RIGHT_ALT, KEY_RIGHT_BRACE},	{KEY_LEFT_SHIFT, KEY_SLASH},	{KEY_LEFT_SHIFT, KEY_4},
	
	//KEY_Y							KEY_Z							KEY_1							KEY_2
	{KEY_LEFT_SHIFT, KEY_1},		{KEY_RESERVED, KEY_NON_US_NUM},	{KEY_UNICODE, 0xB9},			{KEY_RIGHT_ALT, KEY_2},
	
	//KEY_3							KEY_4							KEY_5							KEY_6
	{KEY_RIGHT_ALT, KEY_3},			{KEY_UNICODE, 0x203A},			{KEY_UNICODE, 0x2039},			{KEY_UNICODE, 0xA2},
	
	//KEY_7							KEY_8							KEY_9							KEY_0
	{KEY_UNICODE, 0xA5},			{KEY_UNICODE, 0x201A},			{KEY_UNICODE, 0x2018},			{KEY_UNICODE, 0x2019},
	
	//KEY_ENTER						KEY_ESC							KEY_BACKSPACE					KEY_TAB
	{KEY_RESERVED, KEY_ENTER},		{KEY_RESERVED, KEY_ESC},		{KEY_RESERVED, KEY_BACKSPACE},	{KEY_UNICODE, 0x266B},
	
	//KEY_SPACE						KEY_MINUS						KEY_EQUAL						KEY_LEFT_BRACE
	{KEY_RESERVED, KEY_SPACE},		{KEY_UNICODE, 0x2014},			{KEY_UNICODE, 0x2DA},			{KEY_UNICODE, 0x17F},
	
	//KEY_RIGHT_BRACE					KEY_BACKSLASH					KEY_NON_US_NUM					KEY_SEMICOLON
	{KEY_UNICODE, 0x2011},			{0, 0},							{0, 0},							{KEY_LEFT_SHIFT, KEY_PERIOD},
	
	//KEY_QUOTE						KEY_TILDE						KEY_COMMA						KEY_PERIOD
	{KEY_RIGHT_ALT, KEY_Q},			{KEY_UNICODE, 0x21BB},			{KEY_LEFT_SHIFT, KEY_2},		{KEY_LEFT_SHIFT, KEY_NON_US_NUM},

	//KEY_SLASH						KEY_CAPS_LOCK					KEY_F1							KEY_F2
	{KEY_LEFT_SHIFT, KEY_COMMA},	{0, 0},							{KEY_RESERVED, KEY_F1},			{KEY_RESERVED, KEY_F2},
	
	//KEY_F3							KEY_F4							KEY_F5							KEY_F6
	{KEY_RESERVED, KEY_F3},			{KEY_RESERVED, KEY_F4},			{KEY_RESERVED, KEY_F5},			{KEY_RESERVED, KEY_F6},
	
	//KEY_F7							KEY_F8							KEY_F9							KEY_F10
	{KEY_RESERVED, KEY_F7},			{KEY_RESERVED, KEY_F8},			{KEY_RESERVED, KEY_F9},			{KEY_RESERVED, KEY_F10},
	
	//KEY_F11							KEY_F12							KEY_PRINT						KEY_SCROLL_LOCK
	{KEY_RESERVED, KEY_F11},		{KEY_RESERVED, KEY_F12},		{KEY_RESERVED, KEY_PRINT},		{KEY_RESERVED, KEY_SCROLL_LOCK},
	
	//KEY_PAUSE						KEY_INSERT						KEY_HOME						KEY_PAGE_UP
	{KEY_RESERVED, KEY_PAUSE},		{KEY_RESERVED, KEY_INSERT},		{KEY_RESERVED, KEY_HOME},		{KEY_RESERVED, KEY_PAGE_UP},
	
	//KEY_DELETE						KEY_END							KEY_PAGE_DOWN					KEY_RIGHT_ARROW
	{KEY_RESERVED, KEY_DELETE},		{KEY_RESERVED, KEY_END},		{KEY_RESERVED, KEY_PAGE_DOWN},	{KEY_RESERVED, KEY_RIGHT_ARROW},
	
	//KEY_LEFT_ARROW					KEY_DOWN_ARROW					KEY_UP_ARROW					KEY_NUM_LOCK
	{KEY_RESERVED, KEY_LEFT_ARROW},		{KEY_RESERVED, KEY_DOWN_ARROW},	{KEY_RESERVED, KEY_UP_ARROW},	{KEY_LEFT_SHIFT, KEY_0},
	
	//KEYPAD_DIVIDE					KEYPAD_MULTIPLY					KEYPAD_SUBTRACT					KEYPAD_ADD
	{KEY_UNICODE, 0xF7},			{KEY_UNICODE, 0x22C5},			{KEY_UNICODE, 0x2212},			{KEY_UNICODE, 0xB1},
	
	//KEYPAD_ENTER					KEYPAD_1						KEYPAD_2						KEYPAD_3
	{KEY_RESERVED, KEYPAD_ENTER},	{KEY_UNICODE, 0x2194},			{KEY_UNICODE, 0x2193},			{KEY_UNICODE, 0x21CC},
	
	//KEYPAD_4						KEYPAD_5						KEYPAD_6						KEYPAD_7
	{KEY_UNICODE, 0x2190},			{KEY_LEFT_SHIFT, KEY_PERIOD},	{KEY_UNICODE, 0x2192},			{KEY_UNICODE, 0x2195},
	
	//KEYPAD_8						KEYPAD_9						KEYPAD_0						KEYPAD_DOT
	{KEY_UNICODE, 0x2191},			{KEY_UNICODE, 0x20D7},			{KEY_LEFT_SHIFT, KEY_5},		{KEY_RESERVED, KEYPAD_DOT}
};

const InputSequence Neo2Map::neoMapL4[] PROGMEM = {
	//KEY_RESERVED					KEY_ERROR_ROLLOVER	KEY_POST_FAIL								KEY_ERROR_UNDEFINED
	{0, 0},							{0, 0},							{0, 0},							{0, 0},
	
	//KEY_A							KEY_B							KEY_C							KEY_D
	{KEY_RESERVED, KEY_HOME},		{KEY_LEFT_CTRL, KEY_Y},			{KEY_RESERVED, KEY_INSERT},		{KEY_RESERVED, KEY_DOWN_ARROW},
	
	//KEY_E							KEY_F							KEY_G							KEY_H
	{KEY_RESERVED, KEY_UP_ARROW},	{KEY_RESERVED, KEY_RIGHT_ARROW},{KEY_RESERVED, KEY_END},		{KEY_UNICODE, 0xBF},
	
	//KEY_I							KEY_J							KEY_K							KEY_L
	{KEY_RESERVED, KEYPAD_8},		{KEY_RESERVED, KEYPAD_4},		{KEY_RESERVED, KEYPAD_5},		{KEY_RESERVED, KEYPAD_6},
	
	//KEY_M							KEY_N							KEY_O							KEY_P
	{KEY_RESERVED, KEYPAD_1},		{KEY_LEFT_SHIFT, KEY_PERIOD},	{KEY_RESERVED, KEY_9},			{KEY_RESERVED, KEYPAD_ADD},
	
	//KEY_Q							KEY_R							KEY_S							KEY_T
	{KEY_RESERVED, KEY_PAGE_UP},	{KEY_RESERVED, KEY_DELETE},		{KEY_RESERVED, KEY_LEFT_ARROW},	{KEY_RESERVED, KEY_PAGE_DOWN},
	
	//KEY_U							KEY_V							KEY_W							KEY_X
	{KEY_RESERVED, KEYPAD_7},		{KEY_RESERVED, KEY_ENTER},		{KEY_RESERVED, KEY_BACKSPACE},	{KEY_RESERVED, KEY_TAB},
	
	//KEY_Y							KEY_Z							KEY_1							KEY_2
	{KEY_UNICODE, 0xA1},			{KEY_RESERVED, KEY_ESC},		{KEY_UNICODE, 0xAA},			{KEY_UNICODE, 0xBA},
	
	//KEY_3							KEY_4							KEY_5							KEY_6
	{KEY_UNICODE, 0x2116},			{0, 0},							{KEY_UNICODE, 0xB7},			{KEY_UNICODE, 0xA3},
	
	//KEY_7							KEY_8							KEY_9							KEY_0
	{KEY_UNICODE, 0xA4},			{KEY_RESERVED, KEY_TAB},		{KEY_RESERVED, KEYPAD_DIVIDE},	{KEY_RESERVED, KEYPAD_MULTIPLY},
	
	//KEY_ENTER						KEY_ESC							KEY_BACKSPACE					KEY_TAB
	{KEY_RESERVED, KEYPAD_ENTER},	{KEY_RESERVED, KEY_ESC},		{KEY_RESERVED, KEY_BACKSPACE},	{KEY_RESERVED, KEY_TAB},
	
	//KEY_SPACE						KEY_MINUS						KEY_EQUAL						KEY_LEFT_BRACE
	{KEY_RESERVED, KEYPAD_0},		{KEY_RESERVED, KEYPAD_SUBTRACT},{KEY_UNICODE, 0xA8},			{KEY_UNICODE, 0x2212},
	
	//KEY_RIGHT_BRACE					KEY_BACKSLASH					KEY_NON_US_NUM					KEY_SEMICOLON
	{KEY_UNICODE, 0x2DD},			{0, 0},							{0, 0},							{KEY_RESERVED, KEY_COMMA},
	
	//KEY_QUOTE						KEY_TILDE						KEY_COMMA						KEY_PERIOD
	{KEY_RESERVED, KEY_PERIOD},		{KEY_UNICODE, 0x2D9},			{KEY_RESERVED, KEYPAD_2},		{KEY_RESERVED, KEYPAD_3},

	//KEY_SLASH						KEY_CAPS_LOCK					KEY_F1							KEY_F2
	{KEY_LEFT_SHIFT, KEY_COMMA},	{0, 0},							{KEY_RESERVED, KEY_F1},			{KEY_RESERVED, KEY_F2},
	
	//KEY_F3							KEY_F4							KEY_F5							KEY_F6
	{KEY_RESERVED, KEY_F3},			{KEY_RESERVED, KEY_F4},			{KEY_RESERVED, KEY_F5},			{KEY_RESERVED, KEY_F6},
	
	//KEY_F7							KEY_F8							KEY_F9							KEY_F10
	{KEY_RESERVED, KEY_F7},			{KEY_RESERVED, KEY_F8},			{KEY_RESERVED, KEY_F9},			{KEY_RESERVED, KEY_F10},
	
	//KEY_F11							KEY_F12							KEY_PRINT						KEY_SCROLL_LOCK
	{KEY_RESERVED, KEY_F11},		{KEY_RESERVED, KEY_F12},		{KEY_RESERVED, KEY_PRINT},		{KEY_RESERVED, KEY_SCROLL_LOCK},
	
	//KEY_PAUSE						KEY_INSERT						KEY_HOME						KEY_PAGE_UP
	{KEY_RESERVED, KEY_PAUSE},		{KEY_CONSUMER, MEDIA_VOL_MUTE},	{KEY_CONSUMER, MEDIA_PREV},		{KEY_CONSUMER, MEDIA_VOL_UP},
	
	//KEY_DELETE						KEY_END							KEY_PAGE_DOWN					KEY_RIGHT_ARROW
	{KEY_CONSUMER, MEDIA_PLAY_PAUSE},{KEY_CONSUMER, MEDIA_NEXT},	{KEY_CONSUMER, MEDIA_VOL_DOWN},	{KEY_RESERVED, KEY_RIGHT_ARROW},
	
	//KEY_LEFT_ARROW					KEY_DOWN_ARROW					KEY_UP_ARROW					KEY_NUM_LOCK
	{KEY_RESERVED, KEY_LEFT_ARROW},	{KEY_RESERVED, KEY_DOWN_ARROW},	{KEY_RESERVED, KEY_UP_ARROW},	{KEY_UNICODE, 0x2260},
	
	//KEYPAD_DIVIDE					KEYPAD_MULTIPLY					KEYPAD_SUBTRACT					KEYPAD_ADD
	{KEY_UNICODE, 0x2044},			{KEY_UNICODE, 0xD7},			{KEY_UNICODE, 0x2216},			{KEY_UNICODE, 0x2213},
	
	//KEYPAD_ENTER					KEYPAD_1						KEYPAD_2						KEYPAD_3
	{KEY_RESERVED, KEYPAD_ENTER},	{KEY_RESERVED, KEY_END},		{KEY_RESERVED, KEY_DOWN},		{KEY_RESERVED, KEY_PAGE_DOWN},
	
	//KEYPAD_4						KEYPAD_5						KEYPAD_6						KEYPAD_7
	{KEY_RESERVED, KEY_LEFT_ARROW},	{KEY_RESERVED, KEY_APPLICATION},{KEY_RESERVED, KEY_RIGHT_ARROW},{KEY_RESERVED, KEY_HOME},
	
	//KEYPAD_8						KEYPAD_9						KEYPAD_0						KEYPAD_DOT
	{KEY_RESERVED, KEY_UP_ARROW},	{KEY_RESERVED, KEY_PAGE_UP},	{KEY_RESERVED, KEY_INSERT},		{KEY_RESERVED, KEY_DELETE}
};

const uint16_t Neo2Map::neoMapL5[] PROGMEM = {
	//KEY_RESERVED		KEY_ERROR_ROLLOVER	KEY_POST_FAIL		KEY_ERROR_UNDEFINED	KEY_A				KEY_B				KEY_C				KEY_D
	0,					0,					0,					0,					0,					0x3B6,				0x3B7,				0x3B1,
	
	//KEY_E				KEY_F				KEY_G				KEY_H				KEY_I				KEY_J				KEY_K				KEY_L
	0x3BB,				0x3B5,				0x3BF,				0x3C3,				0x3B3,				0x3BD,				0x3C1,				0x3C4,
	
	//KEY_M				KEY_N				KEY_O				KEY_P				KEY_Q				KEY_R				KEY_S				KEY_T
	0xB5,				0x3B2,				0x3C6,				0x3D5,				0x3BE,				0x3C7,				0x3B9,				0x3C9,
	
	//KEY_U				KEY_V				KEY_W				KEY_X				KEY_Y				KEY_Z				KEY_1				KEY_2
	0x3C8,				0x3C0,				0,					0x3F5,				0x3BA,				0,					0x2081,				0x2082,
	
	//KEY_3				KEY_4				KEY_5				KEY_6				KEY_7				KEY_8				KEY_9				KEY_0
	0x2083,				0x2640,				0x2642,				0x26A5,				0x3F0,				0x27E8,				0x27E9,				0x2080,
	
	//KEY_ENTER			KEY_ESC				KEY_BACKSPACE		KEY_TAB				KEY_SPACE			KEY_MINUS			KEY_EQUAL			KEY_LEFT_BRACE
	0,					0,					0,					0,					0xA0,				0x2011,				0x1FFE,				0x3C2,
	
	//KEY_RIGHT_BRACE		KEY_BACKSLASH		KEY_NON_US_NUM		KEY_SEMICOLON		KEY_QUOTE			KEY_TILDE			KEY_COMMA			KEY_PERIOD
	0x1FBF,				0,					0,					0x3B4,				0x3C5,				0x2DE,				0x3F1,				0x3D1,
	
	//KEY_SLASH			KEY_CAPS_LOCK		KEY_F1				KEY_F2				KEY_F3				KEY_F4				KEY_F5				KEY_F6
	0x3B8,				0,					0,					0,					0,					0,					0,					0,
	
	//KEY_F7				KEY_F8				KEY_F9				KEY_F10				KEY_F11				KEY_F12				KEY_PRINT			KEY_SCROLL_LOCK
	0,					0,					0,					0,					0,					0,					0,					0,
	
	//KEY_PAUSE			KEY_INSERT			KEY_HOME			KEY_PAGE_UP			KEY_DELETE			KEY_END				KEY_PAGE_DOWN		KEY_RIGHT_ARROW
	0,					0,					0,					0,					0,					0,					0,					0,
	
	//KEY_LEFT_ARROW		KEY_DOWN_ARROW		KEY_UP_ARROW		KEY_NUM_LOCK		KEYPAD_DIVIDE		KEYPAD_MULTIPLY		KEYPAD_SUBTRACT		KEYPAD_ADD
	0,					0,					0,					0x2248,				0x2300,				0x2299,				0x2296,				0x2295,
	
	//KEYPAD_ENTER		KEYPAD_1			KEYPAD_2			KEYPAD_3			KEYPAD_4			KEYPAD_5			KEYPAD_6			KEYPAD_7
	0,					0x2264,				0x222A,				0x2265,				0x2282,				0x22B6,				0x2283,				0x226A,
	
	//KEYPAD_8			KEYPAD_9			KEYPAD_0			KEYPAD_DOT
	0x2229,				0x226B,				0x2030,				0x2032
};

const uint16_t Neo2Map::neoMapL6[] PROGMEM = {
	//KEY_RESERVED		KEY_ERROR_ROLLOVER	KEY_POST_FAIL		KEY_ERROR_UNDEFINED	KEY_A				KEY_B				KEY_C				KEY_D
	0,					0,					0,					0,					0x2282,				0x2124,				0x2135,				0x2200,
	
	//KEY_E				KEY_F				KEY_G				KEY_H				KEY_I				KEY_J				KEY_K				KEY_L
	0x39B,				0x2203,				0x2208,				0x3A3,				0x393,				0x2115,				0x211D,				0x2202,
	
	//KEY_M				KEY_N				KEY_O				KEY_P				KEY_Q				KEY_R				KEY_S				KEY_T
	0x21D4,				0x21D0,				0x3A6,				0x211A,				0x39E,				0x2102,				0x222B,				0x3A9,
	
	//KEY_U				KEY_V				KEY_W				KEY_X				KEY_Y				KEY_Z				KEY_1				KEY_2
	0x3A8,				0x3A0,				0x221A,				0x2229,				0x00D7,				0x222A,				0xAC,				0x2228,
	
	//KEY_3				KEY_4				KEY_5				KEY_6				KEY_7				KEY_8				KEY_9				KEY_0
	0x2227,				0x22A5,				0x2221,				0x2225,				0x2192,				0x221E,				0x221D,				0x2205,
	
	//KEY_ENTER			KEY_ESC				KEY_BACKSPACE		KEY_TAB				KEY_SPACE			KEY_MINUS			KEY_EQUAL			KEY_LEFT_BRACE
	0,					0,					0,					0,					0x202F,				0xAD,				0xAF,				0x2218,
	
	//KEY_RIGHT_BRACE		KEY_BACKSLASH		KEY_NON_US_NUM		KEY_SEMICOLON		KEY_QUOTE			KEY_TILDE			KEY_COMMA			KEY_PERIOD
	0x2D8,				0,					0,					0x394,				0x2207,				0x2E,				0x21D2,				0x21A6,
	
	//KEY_SLASH			KEY_CAPS_LOCK		KEY_F1				KEY_F2				KEY_F3				KEY_F4				KEY_F5				KEY_F6
	0x3B8,				0,					0,					0,					0,					0,					0,					0,
	
	//KEY_F7				KEY_F8				KEY_F9				KEY_F10				KEY_F11				KEY_F12				KEY_PRINT			KEY_SCROLL_LOCK
	0,					0,					0,					0,					0,					0,					0,					0,
	
	//KEY_PAUSE			KEY_INSERT			KEY_HOME			KEY_PAGE_UP			KEY_DELETE			KEY_END				KEY_PAGE_DOWN		KEY_RIGHT_ARROW
	0,					0,					0,					0,					0,					0,					0,					0,
	
	//KEY_LEFT_ARROW		KEY_DOWN_ARROW		KEY_UP_ARROW		KEY_NUM_LOCK		KEYPAD_DIVIDE		KEYPAD_MULTIPLY		KEYPAD_SUBTRACT		KEYPAD_ADD
	0,					0,					0,					0x2261,				0x2223,				0x2297,				0x2238,				0x2214,
	
	//KEYPAD_ENTER		KEYPAD_1			KEYPAD_2			KEYPAD_3			KEYPAD_4			KEYPAD_5			KEYPAD_6			KEYPAD_7
	0,					0x230A,				0x222A,				0x230B,				0x2286,				0x22B7,				0x2287,				0x2308,
	
	//KEYPAD_8			KEYPAD_9			KEYPAD_0			KEYPAD_DOT
	0x22C2,				0x2309,				0x25A1,				0x2033
};

const uint8_t Neo2Map::L4Shift_Map[] = {
	0<<7 | 0<<6 | 0<<5 | 0<<4 | 1<<3 | 0<<2 | 0<<1 | 1, //KEY_RESERVED - KEY_D
	1<<7 | 1<<6 | 1<<5 | 0<<4 | 0<<3 | 0<<2 | 0<<1 | 0, //KEY_E - KEY_L
	0<<7 | 1<<6 | 0<<5 | 0<<4 | 1<<3 | 1<<2 | 1<<1 | 1, //KEY_M - KEY_T
	0<<7 | 1<<6 | 1<<5 | 1<<4 | 0<<3 | 1<<2 | 0<<1 | 0, //KEY_U - KEY_2
	0<<7 | 0<<6 | 0<<5 | 0<<4 | 0<<3 | 1<<2 | 0<<1 | 0, //KEY_3 - KEY_0
	1<<7 | 1<<6 | 1<<5 | 1<<4 | 0<<3 | 0<<2 | 0<<1 | 0, //KEY_ENTER - KEY_LEFT_BRACE
	0<<7 | 0<<6 | 0<<5 | 0<<4 | 0<<3 | 0<<2 | 0<<1 | 0, //KEY_RIGHT_BRACE - KEY_PERIOD
	1<<7 | 0<<6 | 1<<5 | 1<<4 | 1<<3 | 1<<2 | 1<<1 | 1, //KEY_SLASH - KEY_F6
	1<<7 | 1<<6 | 1<<5 | 1<<4 | 1<<3 | 1<<2 | 1<<1 | 1, //KEY_F7 - KEY_SCROLL_LOCK
	0<<7 | 0<<6 | 0<<5 | 0<<4 | 0<<3 | 0<<2 | 0<<1 | 0, //KEY_PAUSE - KEY_RIGHT_ARROW
	1<<7 | 1<<6 | 1<<5 | 0<<4 | 0<<3 | 0<<2 | 0<<1 | 0, //KEY_LEFT_ARROW - KEYPAD_ADD
	0<<7 | 1<<6 | 1<<5 | 1<<4 | 1<<3 | 0<<2 | 1<<1 | 1, //KEYPAD_ENTER - KEYPAD_7
	1<<7 | 1<<6 | 1<<5 | 0<<4                           //KEYPAD_8 - KEYPAD_DOT
};
